<?php $h = fn($value) => htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); ?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= $h($appName) ?></title><meta name="csrf-token" content="<?= $h($_SESSION['csrf']) ?>"><link rel="stylesheet" href="public/assets/app.css?v=20"></head><body>
<header><a class="site-home-link" href="https://hirokazu-watabe.jp/travel-compass/">✈ <?= $h($appName) ?></a><span>旅をもっとシンプルに</span></header><main>
<section class="hero"><small>PLAN YOUR NEXT JOURNEY</small><h1>旅の比較を、<br>ひとつの画面から。</h1><p>条件を入力して、航空券やホテルの候補を比較できます。</p></section>
<section class="panel">
<div class="search-tabs" role="tablist" aria-label="検索タイプ">
<button type="button" class="search-tab<?= $activeTab === 'flight' ? ' is-active' : '' ?>" id="flight-tab" role="tab" aria-selected="<?= $activeTab === 'flight' ? 'true' : 'false' ?>" aria-controls="flight-panel" data-tab="flight-panel"<?= $activeTab !== 'flight' ? ' tabindex="-1"' : '' ?>>✈ 航空券</button>
<button type="button" class="search-tab<?= $activeTab === 'hotel' ? ' is-active' : '' ?>" id="hotel-tab" role="tab" aria-selected="<?= $activeTab === 'hotel' ? 'true' : 'false' ?>" aria-controls="hotel-panel" data-tab="hotel-panel"<?= $activeTab !== 'hotel' ? ' tabindex="-1"' : '' ?>>▣ ホテル</button></div>
<div class="tab-panel" id="flight-panel" role="tabpanel" aria-labelledby="flight-tab"<?= $activeTab !== 'flight' ? ' hidden' : '' ?>>
<?php if ($errors): ?><div class="errors"><b>入力内容をご確認ください</b><ul><?php foreach ($errors as $error): ?><li><?= $h($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" class="flight-search-form"><input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><input type="hidden" name="search_type" value="flight">
<fieldset class="trip-type"><legend>旅行タイプ</legend><label><input type="radio" name="trip_type" value="roundtrip" <?= $values['return_date'] !== '' || $_SERVER['REQUEST_METHOD'] !== 'POST' ? 'checked' : '' ?>> 往復</label><label><input type="radio" name="trip_type" value="oneway" <?= $values['return_date'] === '' && $_SERVER['REQUEST_METHOD'] === 'POST' && $activeTab === 'flight' ? 'checked' : '' ?>> 片道</label></fieldset>
<label>出発地<input name="origin" value="<?= $h($values['origin']) ?>" placeholder="例：東京" required></label><label>目的地<input name="destination" value="<?= $h($values['destination']) ?>" placeholder="例：バンコク" required></label><label>出発日<input type="date" name="departure_date" value="<?= $h($values['departure_date']) ?>" required></label><label>帰着日<input type="date" name="return_date" value="<?= $h($values['return_date']) ?>"></label><label>人数<select name="travelers"><?php for ($i=1;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$values['travelers']===$i?'selected':'' ?>><?= $i ?></option><?php endfor ?></select></label><button>航空券を検索</button></form></div>
<div class="tab-panel" id="hotel-panel" role="tabpanel" aria-labelledby="hotel-tab"<?= $activeTab !== 'hotel' ? ' hidden' : '' ?>>
<div class="hotel-provider-tabs" role="tablist" aria-label="ホテル検索サービス"><button type="button" class="hotel-provider-tab<?= in_array($activeHotelProvider,['google','rakuten'],true)?' is-active':'' ?>" id="google-hotel-tab" role="tab" aria-selected="<?= in_array($activeHotelProvider,['google','rakuten'],true)?'true':'false' ?>" aria-controls="google-hotel-panel" data-provider-panel="google-hotel-panel" data-result-provider="<?= $activeHotelProvider==='rakuten'?'rakuten':'google' ?>">Googleホテル・楽天トラベル</button><button type="button" class="hotel-provider-tab" id="trip-hotel-tab" role="tab" aria-selected="false" aria-controls="trip-hotel-panel" data-provider-panel="trip-hotel-panel" tabindex="-1">Trip.com</button><button type="button" class="hotel-provider-tab" id="expedia-hotel-tab" role="tab" aria-selected="false" aria-controls="expedia-hotel-panel" data-provider-panel="expedia-hotel-panel" tabindex="-1">Expedia</button></div>
<div class="hotel-provider-panel" id="google-hotel-panel" role="tabpanel" aria-labelledby="google-hotel-tab"<?= !in_array($activeHotelProvider,['google','rakuten'],true)?' hidden':'' ?>>
<?php if ($hotelErrors||$rakutenErrors): ?><div class="errors"><b>入力内容をご確認ください</b><ul><?php foreach (array_merge($hotelErrors,$rakutenErrors) as $error): ?><li><?= $h($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" class="hotel-search-form hotel-search-form-shared"><input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><label>目的地<input name="hotel_destination" value="<?= $h($hotelValues['hotel_destination']) ?>" placeholder="例：札幌、パリ" required></label><label>チェックイン<input type="date" name="check_in_date" value="<?= $h($hotelValues['check_in_date']) ?>" required></label><label>チェックアウト<input type="date" name="check_out_date" value="<?= $h($hotelValues['check_out_date']) ?>" required></label><label>大人<select name="hotel_adults"><?php for($i=1;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$hotelValues['hotel_adults']===$i?'selected':'' ?>><?= $i ?>名</option><?php endfor ?></select></label><label>子供<select name="hotel_children"><?php for($i=0;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$hotelValues['hotel_children']===$i?'selected':'' ?>><?= $i ?>名</option><?php endfor ?></select></label><div class="hotel-search-actions"><button name="search_type" value="hotel">Googleホテルで検索</button><button name="search_type" value="rakuten_hotel">楽天トラベルで検索</button></div></form></div>
<div class="hotel-provider-panel trip-hotel-widget" id="trip-hotel-panel" role="tabpanel" aria-labelledby="trip-hotel-tab" hidden><iframe src="https://jp.trip.com/partners/ad/S19265451?Allianceid=6026343&amp;SID=169869421&amp;trip_sub1=" title="Trip.com ホテル検索" frameborder="0" scrolling="no" loading="lazy" style="width:100%;max-width:900px;height:200px;border:none" id="S19265451"></iframe></div>
<div class="hotel-provider-panel expedia-hotel-widget" id="expedia-hotel-panel" role="tabpanel" aria-labelledby="expedia-hotel-tab" hidden><div class="eg-widget" data-widget="search" data-program="jp-expedia" data-lobs="stays" data-network="pz" data-camref="1011l5PxNZ" data-pubref=""></div></div>
</div></section>

<?php if ($result): ?><section class="result"><small>YOUR PLAN</small><h2><?= $h($values['origin']) ?> → <?= $h($values['destination']) ?></h2><p><?= $h($values['departure_date']) ?><?= $values['return_date']?' 〜 '.$h($values['return_date']):'' ?>・<?= $values['return_date']!==''?'往復':'片道' ?>・<?= $h($values['travelers']) ?>名</p>
<?php if ($flightOffers): ?><div class="flight-offers" aria-label="参考フライト"><?php foreach($flightOffers as $offerIndex=>$offer): ?><article class="flight-offer"<?= $offerIndex>=6?' hidden data-extra-offer':'' ?>><div class="flight-carrier"><?php if($offer['airline_logo']!==''): ?><img src="<?= $h($offer['airline_logo']) ?>" alt="" width="70" height="70" loading="lazy"><?php elseif($offer['carrier_code']!==''): ?><span class="carrier-code"><?= $h($offer['carrier_code']) ?></span><?php endif ?><b><?= $h($offer['carrier_name']) ?></b><span class="flight-stops"><?= $offer['stops']===0?'直行便':$h($offer['stops']).'回乗継' ?></span></div><div class="flight-price"><small>参考価格</small><strong><?= $offer['currency']==='JPY'?'¥':$h($offer['currency']).' ' ?><?= $h($offer['price']) ?></strong></div></article><?php endforeach ?></div><?php if(count($flightOffers)>6): ?><button type="button" class="flight-offers-toggle" aria-expanded="false">もっと見る</button><?php endif ?><p class="price-note">表示価格はGoogle Flightsの検索結果です。最新の価格・空席は各予約サイトでご確認ください。</p>
<?php elseif($flightOffersStatus!=='idle'): ?><div class="flight-offers-message"><?= $flightOffersStatus==='not_configured'?'参考価格を表示するにはSerpApi APIキーが必要です。':($flightOffersStatus==='unsupported_route'?'入力された都市の空港コードを確認できませんでした。':($flightOffersStatus==='empty'?'条件に一致する便が見つかりませんでした。':'参考便を取得できませんでした。')) ?></div><?php endif ?>
<section class="booking-sites"><h3>予約サイト</h3><p>同じ条件を各予約サイトで確認できます。</p><div class="booking-site-links"><a href="<?= $h($result['flight']) ?>" target="_blank" rel="sponsored noopener">Trip.com</a><a href="<?= $h($result['bookingcom']) ?>" target="_blank" rel="sponsored noopener">Booking.com</a><a href="<?= $h($result['expedia']) ?>" target="_blank" rel="noopener">Expedia</a><a href="<?= $h($result['agoda']) ?>" target="_blank" rel="noopener">Agoda</a><a href="<?= $h($result['ena']) ?>" target="_blank" rel="noopener">ena</a><?php if($isDomesticFlight&&isset($result['sakura'])): ?><a href="<?= $h($result['sakura']) ?>" target="_blank" rel="noopener">さくらトラベル</a><a href="<?= $h($result['airtrip']) ?>" target="_blank" rel="noopener">エアトリ</a><?php endif ?></div></section><div class="actions"><a href="<?= $h($result['maps']) ?>" target="_blank" rel="noopener">Google Maps</a></div><em>予約・決済は各提携先サイトで行われます。</em></section><?php endif ?>

<?php if($activeTab==='hotel'&&!$hotelErrors&&($activeHotelProvider==='google'||$hotelResultsStatus!=='idle')): ?><section class="result hotel-result-section" data-provider-results="google"<?= $activeHotelProvider!=='google'?' hidden':'' ?>><small>HOTEL RESULTS</small><div class="hotel-result-heading"><div><h2><?= $h($hotelValues['hotel_destination']) ?>のホテル</h2><p><?= $h($hotelValues['check_in_date']) ?> 〜 <?= $h($hotelValues['check_out_date']) ?>・大人<?= $h($hotelValues['hotel_adults']) ?>名・子供<?= $h($hotelValues['hotel_children']) ?>名・おすすめ順</p></div></div>
<?php if($hotelResults): ?><div class="hotel-sort"><label for="hotel-sort">並び順</label><select id="hotel-sort"><option value="recommended">おすすめ順</option><option value="price">参考価格が安い順</option><option value="rating">評価が高い順</option></select></div><div class="hotel-results" aria-label="ホテル検索結果" data-hotel-destination="<?= $h($hotelValues['hotel_destination']) ?>" data-check-in="<?= $h($hotelValues['check_in_date']) ?>" data-check-out="<?= $h($hotelValues['check_out_date']) ?>" data-adults="<?= $h($hotelValues['hotel_adults']) ?>" data-children="<?= $h($hotelValues['hotel_children']) ?>"><?php foreach($hotelResults as $hotelIndex=>$hotel): ?><article class="hotel-summary-card" data-property-token="<?= $h($hotel['property_token']) ?>" data-nights="<?= $hotel['nights'] ?>" data-recommended="<?= $hotelIndex ?>" data-price="<?= $hotel['lowest']['nightly'] ?? '' ?>" data-rating="<?= $h($hotel['rating_10']) ?>"<?= $hotelIndex>=5?' hidden data-extra-hotel data-detail-pending':'' ?>>
<div class="hotel-summary-photo-wrap"><?php if($hotel['image']!==''): ?><img class="hotel-summary-photo" src="<?= $h($hotel['image']) ?>" alt="<?= $h($hotel['name']) ?>" loading="lazy"><?php else: ?><div class="hotel-summary-photo hotel-summary-photo-placeholder" aria-label="画像なし">No image</div><?php endif ?><?php if($hotel['image_count']>1): ?><span class="hotel-photo-count">1 / <?= number_format($hotel['image_count']) ?></span><?php endif ?></div><div class="hotel-summary-main"><h3><?= $h($hotel['name']) ?></h3><p class="hotel-class-row"><?php if($hotel['stars']>0): ?><span class="hotel-stars" aria-label="<?= $hotel['stars'] ?>つ星"><?= str_repeat('★',$hotel['stars']) ?></span><?php endif ?><span><?= $h($hotel['type']) ?></span></p><?php if($hotel['rating_10']!==''): ?><p class="hotel-review-row"><b><?= $h($hotel['rating_10']) ?></b><strong><?= $h($hotel['rating_label']) ?></strong><?php if($hotel['reviews']>0): ?><span>（<?= number_format($hotel['reviews']) ?>件の評価）</span><?php endif ?></p><?php endif ?><?php if($hotel['area']!==''): ?><p class="hotel-location-row">⌖ <?= $h($hotel['area']) ?></p><?php endif ?><?php if($hotel['access']!==''): ?><p class="hotel-access-row">◇ <?= $h(mb_strimwidth($hotel['access'],0,80,'…')) ?></p><?php endif ?><?php if($hotel['amenities']): ?><p class="hotel-summary-amenities"><?= $h(implode(' / ',array_slice($hotel['amenities'],0,4))) ?></p><?php endif ?></div>
<div class="hotel-summary-price" data-offer-panel><?php if($hotel['lowest']): ?><div class="hotel-best-offer"><span class="hotel-reference-title">参考最安値</span><b data-best-site><?= $h($hotel['lowest']['site']) ?></b><span class="hotel-cancellation" data-cancellation<?= $hotel['lowest']['free_cancellation']?'':' hidden' ?>>✓ キャンセル無料</span><div class="hotel-price-action"><div><strong data-best-nightly>¥<?= number_format($hotel['lowest']['nightly']) ?> / 泊</strong><small data-best-total><?= $hotel['nights'] ?>泊参考 ¥<?= number_format($hotel['lowest']['total']) ?></small></div><a class="hotel-compare-button" data-best-link href="<?= $h($hotel['lowest']['url']) ?>" target="_blank" rel="sponsored noopener">料金プランを見る ›</a></div><small class="google-price-note">Google Hotels掲載価格より</small></div><div class="hotel-compare-prices" data-other-prices<?= count($hotel['offers'])>1?'':' hidden' ?>><small>その他の掲載価格</small><?php foreach(array_slice($hotel['offers'],1,2) as $offer): ?><span><b><?= $h($offer['site']) ?></b> ¥<?= number_format($offer['nightly']) ?> / 泊</span><?php endforeach ?></div><?php else: ?><p class="hotel-no-price" data-no-price>参考価格は取得できませんでした</p><?php endif ?></div></article><?php endforeach ?></div><?php if(count($hotelResults)>5): ?><button type="button" class="hotel-results-toggle" data-step="5">もっと見る</button><?php endif ?><p class="price-note">料金は検索時点の参考価格です。税・サービス料、空室状況、プラン条件等により実際の料金は異なる場合があります。最終的な料金・条件は各予約サイトでご確認ください。</p>
<?php elseif($hotelResultsStatus!=='idle'): ?><div class="flight-offers-message"><?= $hotelResultsStatus==='not_configured'?'ホテル候補と料金を表示するにはSerpApi APIキーが必要です。下のリンクから各予約サイトを検索できます。':($hotelResultsStatus==='empty'?'条件に一致するホテル料金が見つかりませんでした。下の予約サイトでもご確認ください。':'ホテル情報を取得できませんでした。時間を置いて再度お試しください。') ?></div><?php endif ?>
<?php if($hotelBookingSites&&!$hotelResults): ?><section class="booking-sites"><h3>各予約サイトで確認</h3><div class="booking-site-links"><?php foreach($hotelBookingSites as $site): ?><a href="<?= $h($site['url']) ?>" target="_blank" rel="sponsored noopener"><?= $h($site['name']) ?></a><?php endforeach ?></div></section><?php endif ?></section><?php endif ?>
<?php if($activeTab==='hotel'&&$activeHotelProvider==='rakuten'&&!$rakutenErrors): ?><section class="result rakuten-result-section" data-provider-results="rakuten"><small>RAKUTEN TRAVEL RESULTS</small><h2><?= $h($rakutenValues['rakuten_destination']) ?>のホテル</h2><p class="rakuten-result-conditions"><?= $h($rakutenValues['rakuten_check_in']) ?> 〜 <?= $h($rakutenValues['rakuten_check_out']) ?>・大人<?= $h($rakutenValues['rakuten_adults']) ?>名・子供<?= $h($rakutenValues['rakuten_children']) ?>名</p><?php if($rakutenHotels): ?><div class="rakuten-hotel-results"><?php foreach($rakutenHotels as $rakutenIndex=>$rakutenHotel): ?><article class="rakuten-hotel-card"<?= $rakutenIndex>=5?' hidden data-extra-rakuten-hotel':'' ?>><div class="rakuten-hotel-photo-wrap"><?php if($rakutenHotel['image']!==''): ?><img class="rakuten-hotel-photo" src="<?= $h($rakutenHotel['image']) ?>" alt="<?= $h($rakutenHotel['name']) ?>" loading="lazy"><?php else: ?><div class="rakuten-hotel-photo rakuten-hotel-photo-placeholder">No image</div><?php endif ?></div><div class="rakuten-hotel-main"><h3><?= $h($rakutenHotel['name']) ?></h3><?php if($rakutenHotel['rating']!==''): ?><p class="rakuten-rating"><b><?= $h($rakutenHotel['rating']) ?></b> / 5<?php if($rakutenHotel['reviews']>0): ?> <span>（<?= number_format($rakutenHotel['reviews']) ?>件）</span><?php endif ?></p><?php endif ?><?php if($rakutenHotel['address']!==''): ?><p>📍 <?= $h($rakutenHotel['address']) ?></p><?php endif ?><?php if($rakutenHotel['access']!==''): ?><p><?= $h($rakutenHotel['access']) ?></p><?php endif ?><?php if($rakutenHotel['description']!==''): ?><p class="rakuten-description"><?= $h(mb_strimwidth($rakutenHotel['description'],0,130,'…')) ?></p><?php endif ?><?php if($rakutenHotel['facilities']): ?><p class="rakuten-facilities"><?= $h(implode(' / ',$rakutenHotel['facilities'])) ?></p><?php endif ?></div><aside class="rakuten-hotel-price"><?php if($rakutenHotel['price']>0): ?><small>1室1泊あたり参考</small><strong>¥<?= number_format($rakutenHotel['price']) ?>〜</strong><?php else: ?><p>料金は楽天トラベルでご確認ください</p><?php endif ?><a href="<?= $h($rakutenHotel['url']) ?>" target="_blank" rel="sponsored noopener">楽天トラベルで見る</a></aside></article><?php endforeach ?></div><?php if(count($rakutenHotels)>5): ?><button type="button" class="rakuten-results-toggle" data-step="5">もっと見る</button><?php endif ?><p class="price-note">料金・空室状況・プラン条件は検索時点から変わる場合があります。楽天トラベルで最終条件をご確認ください。</p><?php elseif($rakutenStatus!=='idle'): ?><div class="flight-offers-message"><?= $rakutenStatus==='not_configured'?'.envに楽天APIのApplication IDとAccess Keyを設定してください。':($rakutenStatus==='empty'?'条件に一致するホテルが見つかりませんでした。':'楽天トラベルのホテル情報を取得できませんでした。時間を置いて再度お試しください。') ?></div><?php endif ?></section><?php endif ?>
<?php if($recent&&$activeTab==='flight'): ?><section class="history"><small>RECENT SEARCHES</small><h2>最近の検索</h2><div class="cards"><?php foreach($recent as $recentSearch): ?><button type="button" class="recent-search-card" data-origin="<?= $h($recentSearch['origin']) ?>" data-destination="<?= $h($recentSearch['destination']) ?>" data-departure-date="<?= $h($recentSearch['departure_date']) ?>" data-return-date="<?= $h($recentSearch['return_date'] ?? '') ?>" data-travelers="<?= $h($recentSearch['travelers']) ?>"><b><?= $h($recentSearch['origin']) ?> → <?= $h($recentSearch['destination']) ?></b><span><?= $h($recentSearch['departure_date']) ?><?= !empty($recentSearch['return_date'])?' 〜 '.$h($recentSearch['return_date']):'' ?>・<?= $h($recentSearch['travelers']) ?>名</span></button><?php endforeach ?></div></section><?php endif ?>
</main><footer class="site-footer"><div class="site-footer-inner"><div><strong>✈ <?= $h($appName) ?></strong><p>航空券とホテルを比較できる旅行検索サービス</p></div><div class="site-footer-credit"><span>Created by Hirokazu WATABE</span><small>© <?= date('Y') ?> Hirokazu WATABE</small></div></div></footer><script class="eg-widgets-script" src="https://creator.expediagroup.com/products/widgets/assets/eg-widgets.js"></script><script src="public/assets/app.js?v=12"></script></body></html>
