CREATE TABLE flight_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 visitor_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 origin VARCHAR(100) NOT NULL,
 destination VARCHAR(100) NOT NULL,
 departure_date DATE NOT NULL,
 return_date DATE NULL,
 travelers TINYINT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_created_at (created_at),
 KEY idx_visitor_created (visitor_id, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE hotel_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 visitor_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 destination VARCHAR(150) NOT NULL,
 check_in DATE NOT NULL,
 check_out DATE NOT NULL,
 adults TINYINT UNSIGNED NOT NULL DEFAULT 1,
 children TINYINT UNSIGNED NOT NULL DEFAULT 0,
 guests TINYINT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_created_at (created_at),
 KEY idx_visitor_created (visitor_id, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- phpMyAdmin SQL Dump
-- version 5.2.1-1.el7.remi
-- https://www.phpmyadmin.net/
--
-- ホスト: localhost
-- 生成日時: 2026 年 8 月 19 日 11:04
-- サーバのバージョン： 5.7.44-log
-- PHP のバージョン: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- データベース: `8kk9t_ne7ffc63`
--

-- --------------------------------------------------------

--
-- テーブルの構造 `iata_cities`
--

CREATE TABLE `iata_cities` (
  `id` int(10) UNSIGNED NOT NULL,
  `city` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iata` char(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code_type` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `airports` json DEFAULT NULL,
  `aliases` json DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- テーブルのデータのダンプ `iata_cities`
--

INSERT INTO `iata_cities` (`id`, `city`, `country`, `iata`, `code_type`, `airports`, `aliases`) VALUES
(1, 'Aalborg', 'DK', 'AAL', 'airport_as_city', '[\"AAL\"]', '[\"オールボー\"]'),
(2, 'Aarhus', 'DK', 'AAR', 'airport_as_city', '[\"AAR\"]', '[\"オーフス\"]'),
(3, 'Abadan', 'IR', 'ABD', 'airport_as_city', '[\"ABD\"]', '[\"アバダン\"]'),
(4, 'Abakan', 'RU', 'ABA', 'airport_as_city', '[\"ABA\"]', '[\"アバカン\"]'),
(5, 'Aberdeen', 'GB', 'ABZ', 'airport_as_city', '[\"ABZ\"]', '[\"アバディーン\"]'),
(6, 'Abha', 'SA', 'AHB', 'airport_as_city', '[\"AHB\"]', '[\"アブハ\"]'),
(7, 'Abidjan', 'CI', 'ABJ', 'airport_as_city', '[\"ABJ\"]', '[\"アビジャン\"]'),
(8, 'Abu Dhabi', 'AE', 'AUH', 'airport_as_city', '[\"AUH\"]', '[\"アブダビ\"]'),
(9, 'Abuja', 'NG', 'ABV', 'airport_as_city', '[\"ABV\"]', '[\"アブジャ\"]'),
(10, 'Acapulco', 'MX', 'ACA', 'airport_as_city', '[\"ACA\"]', '[\"アカプルコ\"]'),
(11, 'Accra', 'GH', 'ACC', 'airport_as_city', '[\"ACC\"]', '[\"アクラ\"]'),
(12, 'Ad Dammam', 'SA', 'DMM', 'airport_as_city', '[\"DMM\"]', '[\"アド ダンマーム\"]'),
(13, 'Addis Ababa', 'ET', 'ADD', 'airport_as_city', '[\"ADD\"]', '[\"アディスアベバ\"]'),
(14, 'Adelaide', 'AU', 'ADL', 'airport_as_city', '[\"ADL\"]', '[\"アデレード\"]'),
(15, 'Aden', 'YE', 'ADE', 'airport_as_city', '[\"ADE\"]', '[\"アデン\"]'),
(16, 'Agadir (Temsia)', 'MA', 'AGA', 'airport_as_city', '[\"AGA\"]', '[\"アガディール (テムシア)\"]'),
(17, 'Aguascalientes', 'MX', 'AGU', 'airport_as_city', '[\"AGU\"]', '[\"アグアスカリエンテス\"]'),
(18, 'Ahl Angad', 'MA', 'OUD', 'airport_as_city', '[\"OUD\"]', '[\"アル・アンガド\"]'),
(19, 'Ahmedabad', 'IN', 'AMD', 'airport_as_city', '[\"AMD\"]', '[\"アーメダバード\"]'),
(20, 'Ahvaz', 'IR', 'AWZ', 'airport_as_city', '[\"AWZ\"]', '[\"アフヴァーズ\"]'),
(21, 'Aktau', 'KZ', 'SCO', 'airport_as_city', '[\"SCO\"]', '[\"アクタウ\"]'),
(22, 'Aktobe', 'KZ', 'AKX', 'airport_as_city', '[\"AKX\"]', '[\"アクトベ\"]'),
(23, 'Akureyri', 'IS', 'AEY', 'airport_as_city', '[\"AEY\"]', '[\"アークレイリ\"]'),
(24, 'Al Aaroui', 'MA', 'NDR', 'airport_as_city', '[\"NDR\"]', '[\"アル・アールイ\"]'),
(25, 'Al Ain', 'AE', 'AAN', 'airport_as_city', '[\"AAN\"]', '[\"アル・アイン\"]'),
(26, 'Al Albraq', 'LY', 'LAQ', 'airport_as_city', '[\"LAQ\"]', '[\"アル・アルブラック\"]'),
(27, 'Al-Jawf', 'SA', 'AJF', 'airport_as_city', '[\"AJF\"]', '[\"アル・ジャウフ\"]'),
(28, 'Al Jiza', 'EG', 'SPX', 'airport_as_city', '[\"SPX\"]', '[\"アル・ジザ\"]'),
(29, 'Al-Ula', 'SA', 'ULH', 'airport_as_city', '[\"ULH\"]', '[\"アル・ウラ\"]'),
(30, 'Albany', 'US', 'ALB', 'airport_as_city', '[\"ALB\"]', '[\"オールバニ\"]'),
(31, 'Albuquerque', 'US', 'ABQ', 'airport_as_city', '[\"ABQ\"]', '[\"アルバカーキ\"]'),
(32, 'Aleppo', 'SY', 'ALP', 'airport_as_city', '[\"ALP\"]', '[\"アレッポ\"]'),
(33, 'Ålesund', 'NO', 'AES', 'airport_as_city', '[\"AES\"]', '[\"オーレスン\"]'),
(34, 'Alexandria', 'EG', 'HBE', 'airport_as_city', '[\"HBE\"]', '[\"アレクサンドリア\"]'),
(35, 'Algiers', 'DZ', 'ALG', 'airport_as_city', '[\"ALG\"]', '[\"アルジェ\"]'),
(36, 'Alicante', 'ES', 'ALC', 'airport_as_city', '[\"ALC\"]', '[\"アリカンテ\"]'),
(37, 'Almaty', 'KZ', 'ALA', 'airport_as_city', '[\"ALA\"]', '[\"アルマトイ\"]'),
(38, 'Ambon', 'ID', 'AMQ', 'airport_as_city', '[\"AMQ\"]', '[\"アンボン\"]'),
(39, 'Amman', 'JO', 'ADJ', 'airport_as_city', '[\"ADJ\"]', '[\"アンマン\"]'),
(40, 'Amritsar', 'IN', 'ATQ', 'airport_as_city', '[\"ATQ\"]', '[\"アムリトサル\"]'),
(41, 'Amsterdam', 'NL', 'AMS', 'airport_as_city', '[\"AMS\"]', '[\"アムステルダム\"]'),
(42, 'Anchorage', 'US', 'ANC', 'airport_as_city', '[\"ANC\"]', '[\"アンカレッジ\"]'),
(43, 'Ankara', 'TR', 'ANK', 'metropolitan', '[\"ANK\", \"ESB\"]', '[\"アンカラ\"]'),
(44, 'Annaba', 'DZ', 'AAE', 'airport_as_city', '[\"AAE\"]', '[\"アンナバ\"]'),
(45, 'Antalya', 'TR', 'AYT', 'airport_as_city', '[\"AYT\"]', '[\"アンタルヤ\"]'),
(46, 'Antananarivo', 'MG', 'TNR', 'airport_as_city', '[\"TNR\"]', '[\"アンタナナリボ\"]'),
(47, 'Antofagasta', 'CL', 'ANF', 'airport_as_city', '[\"ANF\"]', '[\"アントファガスタ\"]'),
(48, 'Aomori', 'JP', 'AOJ', 'airport_as_city', '[\"AOJ\"]', '[\"青森\", \"あおもり\"]'),
(49, 'Apia', 'WS', 'APW', 'airport_as_city', '[\"APW\"]', '[\"アピア\"]'),
(50, 'Aqaba', 'JO', 'AQJ', 'airport_as_city', '[\"AQJ\"]', '[\"アカバ\"]'),
(51, 'Arbil', 'IQ', 'EBL', 'airport_as_city', '[\"EBL\"]', '[\"アルビル\"]'),
(52, 'Arequipa', 'PE', 'AQP', 'airport_as_city', '[\"AQP\"]', '[\"アレキパ\"]'),
(53, 'Artyom', 'RU', 'VVO', 'airport_as_city', '[\"VVO\"]', '[\"ウラジオストク\",\"アルチョム\"]'),
(54, 'Arusha', 'TZ', 'JRO', 'airport_as_city', '[\"JRO\"]', '[\"アルーシャ\"]'),
(55, 'Asaba', 'NG', 'ABB', 'airport_as_city', '[\"ABB\"]', '[\"浅羽\"]'),
(56, 'Ashgabat', 'TM', 'ASB', 'airport_as_city', '[\"ASB\"]', '[\"アシガバート\"]'),
(57, 'Astana', 'KZ', 'NQZ', 'airport_as_city', '[\"NQZ\"]', '[\"アスタナ\"]'),
(58, 'Astrakhan', 'RU', 'ASF', 'airport_as_city', '[\"ASF\"]', '[\"アストラハン\"]'),
(59, 'Asunción', 'PY', 'ASU', 'airport_as_city', '[\"ASU\"]', '[\"アスンシオン\"]'),
(60, 'Aswan', 'EG', 'ASW', 'airport_as_city', '[\"ASW\"]', '[\"アスワン\"]'),
(61, 'Asyut', 'EG', 'ATZ', 'airport_as_city', '[\"ATZ\"]', '[\"アシュート\"]'),
(62, 'Atlanta', 'US', 'ATL', 'airport_as_city', '[\"ATL\"]', '[\"アトランタ\"]'),
(63, 'Attock', 'PK', 'ISB', 'airport_as_city', '[\"ISB\"]', '[\"攻撃する\"]'),
(64, 'Atyrau', 'KZ', 'GUW', 'airport_as_city', '[\"GUW\"]', '[\"アティラウ\"]'),
(65, 'Auckland', 'NZ', 'AKL', 'airport_as_city', '[\"AKL\"]', '[\"オークランド\"]'),
(66, 'Austin', 'US', 'AUS', 'airport_as_city', '[\"AUS\"]', '[\"オースティン\"]'),
(67, 'Avarua', 'CK', 'RAR', 'airport_as_city', '[\"RAR\"]', '[\"アバルア\"]'),
(68, 'Babelthuap Island', 'PW', 'ROR', 'airport_as_city', '[\"ROR\"]', '[\"バベルスアップ島\"]'),
(69, 'Bacău', 'RO', 'BCM', 'airport_as_city', '[\"BCM\"]', '[\"バカウ\"]'),
(70, 'Bacolod City', 'PH', 'BCD', 'airport_as_city', '[\"BCD\"]', '[\"バコロド市\"]'),
(71, 'Baghdad', 'IQ', 'BGW', 'airport_as_city', '[\"BGW\"]', '[\"バグダッド\"]'),
(72, 'Baikonur', 'KZ', 'BXY', 'airport_as_city', '[\"BXY\"]', '[\"バイコヌール\"]'),
(73, 'Baku', 'AZ', 'GYD', 'airport_as_city', '[\"GYD\"]', '[\"バクー\"]'),
(74, 'Bâle / Mulhouse', 'FR', 'BSL', 'airport_as_city', '[\"BSL\"]', '[\"バーゼル\",\"ミュルーズ\"]'),
(75, 'Balice', 'PL', 'KRK', 'airport_as_city', '[\"KRK\"]', '[\"クラクフ\",\"バリツェ\"]'),
(76, 'Balikpapan', 'ID', 'BPN', 'airport_as_city', '[\"BPN\"]', '[\"バリクパパン\"]'),
(77, 'Baltimore', 'US', 'BWI', 'airport_as_city', '[\"BWI\"]', '[\"ボルチモア\"]'),
(78, 'Bamako', 'ML', 'BKO', 'airport_as_city', '[\"BKO\"]', '[\"バマコ\"]'),
(79, 'Banda Aceh', 'ID', 'BTJ', 'airport_as_city', '[\"BTJ\"]', '[\"バンダ・アチェ\"]'),
(80, 'Bandar Abbas', 'IR', 'BND', 'airport_as_city', '[\"BND\"]', '[\"バンダル・アッバス\"]'),
(81, 'Bandar Seri Begawan', 'BN', 'BWN', 'airport_as_city', '[\"BWN\"]', '[\"バンダル・スリ・ブガワン\"]'),
(82, 'Bangkok', 'TH', 'BKK', 'metropolitan', '[\"BKK\", \"DMK\"]', '[\"バンコク\"]'),
(83, 'Bangui', 'CF', 'BGF', 'airport_as_city', '[\"BGF\"]', '[\"バンギ\"]'),
(84, 'Banjarbaru', 'ID', 'BDJ', 'airport_as_city', '[\"BDJ\"]', '[\"バンジャルバル\"]'),
(85, 'Banjul (Yundum)', 'GM', 'BJL', 'airport_as_city', '[\"BJL\"]', '[\"バンジュール（ユンドゥム）\"]'),
(86, 'Baotou', 'CN', 'BAV', 'airport_as_city', '[\"BAV\"]', '[\"包頭\", \"包头\"]'),
(87, 'Barcelona', 'ES', 'BCN', 'airport_as_city', '[\"BCN\"]', '[\"バルセロナ\"]'),
(88, 'Barcelona', 'VE', 'BLA', 'airport_as_city', '[\"BLA\"]', '[\"バルセロナ\"]'),
(89, 'Bari', 'IT', 'BRI', 'airport_as_city', '[\"BRI\"]', '[\"バーリ\"]'),
(90, 'Barnaul', 'RU', 'BAX', 'airport_as_city', '[\"BAX\"]', '[\"バルナウル\"]'),
(91, 'Barquisimeto', 'VE', 'BRM', 'airport_as_city', '[\"BRM\"]', '[\"バルキシメト\"]'),
(92, 'Barranquilla', 'CO', 'BAQ', 'airport_as_city', '[\"BAQ\"]', '[\"バランキージャ\"]'),
(93, 'Basra', 'IQ', 'BSR', 'airport_as_city', '[\"BSR\"]', '[\"バスラ\"]'),
(94, 'Basseterre', 'KN', 'SKB', 'airport_as_city', '[\"SKB\"]', '[\"バセテール\"]'),
(95, 'Bastia', 'FR', 'BIA', 'airport_as_city', '[\"BIA\"]', '[\"バスティア\"]'),
(96, 'Bata', 'GQ', 'BSG', 'airport_as_city', '[\"BSG\"]', '[\"バタ\"]'),
(97, 'Batam', 'ID', 'BTH', 'airport_as_city', '[\"BTH\"]', '[\"バタム島\"]'),
(98, 'Batna', 'DZ', 'BLJ', 'airport_as_city', '[\"BLJ\"]', '[\"バトナ\"]'),
(99, 'Batumi', 'GE', 'BUS', 'airport_as_city', '[\"BUS\"]', '[\"バトゥミ\"]'),
(100, 'Bauchi', 'NG', 'BCU', 'airport_as_city', '[\"BCU\"]', '[\"バウチ\"]'),
(101, 'Beauvais', 'FR', 'BVA', 'airport_as_city', '[\"BVA\"]', '[\"ボーヴェ\"]'),
(102, 'Beef Island', 'VG', 'EIS', 'airport_as_city', '[\"EIS\"]', '[\"ビーフアイランド\"]'),
(103, 'Beijing', 'CN', 'BJS', 'metropolitan', '[\"PEK\", \"PKX\"]', '[\"北京\", \"ペキン\"]'),
(104, 'Beira', 'MZ', 'BEW', 'airport_as_city', '[\"BEW\"]', '[\"ベイラ\"]'),
(105, 'Beirut', 'LB', 'BEY', 'airport_as_city', '[\"BEY\"]', '[\"ベイルート\"]'),
(106, 'Béjaïa', 'DZ', 'BJA', 'airport_as_city', '[\"BJA\"]', '[\"ベジャイア\"]'),
(107, 'Belém', 'BR', 'BEL', 'airport_as_city', '[\"BEL\"]', '[\"ベレン\"]'),
(108, 'Belfast', 'GB', 'BFS', 'metropolitan', '[\"BFS\", \"BHD\"]', '[\"ベルファスト\"]'),
(109, 'Belgrade', 'RS', 'BEG', 'airport_as_city', '[\"BEG\"]', '[\"ベオグラード\"]'),
(110, 'Belize City', 'BZ', 'BZE', 'airport_as_city', '[\"BZE\"]', '[\"ベリーズシティ\"]'),
(111, 'Belo Horizonte', 'BR', 'BHZ', 'metropolitan', '[\"CNF\", \"PLU\"]', '[\"ベロオリゾンテ\"]'),
(112, 'Bengaluru', 'IN', 'BLR', 'airport_as_city', '[\"BLR\"]', '[\"バンガロール\"]'),
(113, 'Benina', 'LY', 'BEN', 'airport_as_city', '[\"BEN\"]', '[\"ベニナ\"]'),
(114, 'Bergen', 'NO', 'BGO', 'airport_as_city', '[\"BGO\"]', '[\"ベルゲン\"]'),
(115, 'Beringin', 'ID', 'KNO', 'airport_as_city', '[\"KNO\"]', '[\"ベリンギン\"]'),
(116, 'Berlin', 'DE', 'BER', 'airport_as_city', '[\"BER\"]', '[\"ベルリン\"]'),
(117, 'Bhopal', 'IN', 'BHO', 'airport_as_city', '[\"BHO\"]', '[\"ボパール\"]'),
(118, 'Bhubaneswar', 'IN', 'BBI', 'airport_as_city', '[\"BBI\"]', '[\"ブバネシュワール\"]'),
(119, 'Bilbao', 'ES', 'BIO', 'airport_as_city', '[\"BIO\"]', '[\"ビルバオ\"]'),
(120, 'Billund', 'DK', 'BLL', 'airport_as_city', '[\"BLL\"]', '[\"ビルン\"]'),
(121, 'Birjand', 'IR', 'XBJ', 'airport_as_city', '[\"XBJ\"]', '[\"ビールジャンド\"]'),
(122, 'Birmingham', 'US', 'BHM', 'airport_as_city', '[\"BHM\"]', '[\"バーミングハム\"]'),
(123, 'Birmingham, West Midlands', 'GB', 'BHX', 'airport_as_city', '[\"BHX\"]', '[\"バーミンガム\"]'),
(124, 'Bishkek', 'KG', 'BSZ', 'airport_as_city', '[\"BSZ\"]', '[\"ビシュケク\"]'),
(125, 'Biskra', 'DZ', 'BSK', 'airport_as_city', '[\"BSK\"]', '[\"ビスクラ\"]'),
(126, 'Bissau', 'GW', 'OXB', 'airport_as_city', '[\"OXB\"]', '[\"ビサウ\"]'),
(127, 'Blantyre', 'MW', 'BLZ', 'airport_as_city', '[\"BLZ\"]', '[\"ブランタイヤ\"]'),
(128, 'Bloemfontein', 'ZA', 'BFN', 'airport_as_city', '[\"BFN\"]', '[\"ブルームフォンテーン\"]'),
(129, 'Boa Vista', 'BR', 'BVB', 'airport_as_city', '[\"BVB\"]', '[\"ボアビスタ\"]'),
(130, 'Bobo Dioulasso', 'BF', 'BOY', 'airport_as_city', '[\"BOY\"]', '[\"ボボ・ディウラッソ\"]'),
(131, 'Bodø', 'NO', 'BOO', 'airport_as_city', '[\"BOO\"]', '[\"ボードー\"]'),
(132, 'Bodrum', 'TR', 'BJV', 'airport_as_city', '[\"BJV\"]', '[\"ボドルム\"]'),
(133, 'Bogota', 'CO', 'BOG', 'airport_as_city', '[\"BOG\"]', '[\"ボゴタ\"]'),
(134, 'Boise', 'US', 'BOI', 'airport_as_city', '[\"BOI\"]', '[\"ボイシ\"]'),
(135, 'Bokhtar', 'TJ', 'KQT', 'airport_as_city', '[\"KQT\"]', '[\"ボクタル\"]'),
(136, 'Bologna', 'IT', 'BLQ', 'airport_as_city', '[\"BLQ\"]', '[\"ボローニャ\"]'),
(137, 'Bordeaux', 'FR', 'BOD', 'airport_as_city', '[\"BOD\"]', '[\"ボルドー\"]'),
(138, 'Bosaso', 'SO', 'BSA', 'airport_as_city', '[\"BSA\"]', '[\"ボサソ\"]'),
(139, 'Boston', 'US', 'BOS', 'airport_as_city', '[\"BOS\"]', '[\"ボストン\"]'),
(140, 'Brasília', 'BR', 'BSB', 'airport_as_city', '[\"BSB\"]', '[\"ブラジリア\"]'),
(141, 'Brașov (Ghimbav)', 'RO', 'GHV', 'airport_as_city', '[\"GHV\"]', '[\"ブラショフ\"]'),
(142, 'Bratislava', 'SK', 'BTS', 'airport_as_city', '[\"BTS\"]', '[\"ブラチスラバ\"]'),
(143, 'Brazzaville', 'CG', 'BZV', 'airport_as_city', '[\"BZV\"]', '[\"ブラザビル\"]'),
(144, 'Bremen', 'DE', 'BRE', 'airport_as_city', '[\"BRE\"]', '[\"ブレーメン\"]'),
(145, 'Brest', 'BY', 'BQT', 'airport_as_city', '[\"BQT\"]', '[\"ブレスト\"]'),
(146, 'Brest', 'FR', 'BES', 'airport_as_city', '[\"BES\"]', '[\"ブレスト\"]'),
(147, 'Bridgetown', 'BB', 'BGI', 'airport_as_city', '[\"BGI\"]', '[\"ブリッジタウン\"]'),
(148, 'Brindisi', 'IT', 'BDS', 'airport_as_city', '[\"BDS\"]', '[\"ブリンディジ\"]'),
(149, 'Brisbane', 'AU', 'BNE', 'airport_as_city', '[\"BNE\"]', '[\"ブリスベン\"]'),
(150, 'Bristol', 'GB', 'BRS', 'airport_as_city', '[\"BRS\"]', '[\"ブリストル\"]'),
(151, 'Broome', 'AU', 'BME', 'airport_as_city', '[\"BME\"]', '[\"ブルーム\"]'),
(152, 'Brussels', 'BE', 'BRU', 'metropolitan', '[\"BRU\", \"CRL\"]', '[\"ブリュッセル\"]'),
(153, 'Bucharest', 'RO', 'BBU', 'airport_as_city', '[\"BBU\"]', '[\"ブカレスト\"]'),
(154, 'Budapest', 'HU', 'BUD', 'airport_as_city', '[\"BUD\"]', '[\"ブダペスト\"]'),
(155, 'Buenos Aires', 'AR', 'BUE', 'metropolitan', '[\"AEP\", \"EZE\"]', '[\"ブエノスアイレス\"]'),
(156, 'Buenos Aires (Ezeiza)', 'AR', 'EZE', 'airport_as_city', '[\"EZE\"]', '[\"ブエノスアイレス (エセイサ)\"]'),
(157, 'Buffalo', 'US', 'BUF', 'airport_as_city', '[\"BUF\"]', '[\"バッファロー\"]'),
(158, 'Bujumbura', 'BI', 'BJM', 'airport_as_city', '[\"BJM\"]', '[\"ブジュンブラ\"]'),
(159, 'Bukhara', 'UZ', 'BHK', 'airport_as_city', '[\"BHK\"]', '[\"ブハラ\"]'),
(160, 'Bulawayo', 'ZW', 'BUQ', 'airport_as_city', '[\"BUQ\"]', '[\"ブラワヨ\"]'),
(161, 'Burbank', 'US', 'BUR', 'airport_as_city', '[\"BUR\"]', '[\"バーバンク\"]'),
(162, 'Büren', 'DE', 'PAD', 'airport_as_city', '[\"PAD\"]', '[\"パーダーボルン\",\"ビューレン\"]'),
(163, 'Burgas', 'BG', 'BOJ', 'airport_as_city', '[\"BOJ\"]', '[\"ブルガス\"]'),
(164, 'Busan', 'KR', 'PUS', 'airport_as_city', '[\"PUS\"]', '[\"釜山\", \"부산\"]'),
(165, 'Cabatuan', 'PH', 'ILO', 'airport_as_city', '[\"ILO\"]', '[\"カバトゥアン\"]'),
(166, 'Cagliari', 'IT', 'CAG', 'airport_as_city', '[\"CAG\"]', '[\"カリアリ\"]'),
(167, 'Cairns', 'AU', 'CNS', 'airport_as_city', '[\"CNS\"]', '[\"ケアンズ\"]'),
(168, 'Cairo', 'EG', 'CAI', 'airport_as_city', '[\"CAI\"]', '[\"カイロ\"]'),
(169, 'Calden', 'DE', 'KSF', 'airport_as_city', '[\"KSF\"]', '[\"カッセル\",\"カルデン\"]'),
(170, 'Calgary', 'CA', 'YYC', 'airport_as_city', '[\"YYC\"]', '[\"カルガリー\"]'),
(171, 'Cali', 'CO', 'CLO', 'airport_as_city', '[\"CLO\"]', '[\"カリ\"]'),
(172, 'Calicut', 'IN', 'CCJ', 'airport_as_city', '[\"CCJ\"]', '[\"カリカット\"]'),
(173, 'Camaguey', 'CU', 'CMW', 'airport_as_city', '[\"CMW\"]', '[\"カマグエイ\"]'),
(174, 'Campinas', 'BR', 'VCP', 'airport_as_city', '[\"VCP\"]', '[\"カンピナス\"]'),
(175, 'Can Tho', 'VN', 'VCA', 'airport_as_city', '[\"VCA\"]', '[\"カントー\"]'),
(176, 'Cancún', 'MX', 'CUN', 'airport_as_city', '[\"CUN\"]', '[\"カンクン\"]'),
(177, 'Cap Haitien', 'HT', 'CAP', 'airport_as_city', '[\"CAP\"]', '[\"カパイシャン\"]'),
(178, 'Cape Town', 'ZA', 'CPT', 'airport_as_city', '[\"CPT\"]', '[\"ケープタウン\"]'),
(179, 'Cardiff', 'GB', 'CWL', 'airport_as_city', '[\"CWL\"]', '[\"カーディフ\"]'),
(180, 'Cartagena', 'CO', 'CTG', 'airport_as_city', '[\"CTG\"]', '[\"カルタヘナ\"]'),
(181, 'Casablanca', 'MA', 'CMN', 'airport_as_city', '[\"CMN\"]', '[\"カサブランカ\"]'),
(182, 'Caselle Torinese (TO)', 'IT', 'TRN', 'airport_as_city', '[\"TRN\"]', '[\"トリノ\",\"カゼッレ・トリネーゼ\"]'),
(183, 'Caselle (VR)', 'IT', 'VRN', 'airport_as_city', '[\"VRN\"]', '[\"ヴェローナ\",\"カゼッレ\"]'),
(184, 'Castletown', 'IM', 'IOM', 'airport_as_city', '[\"IOM\"]', '[\"キャッスルタウン\"]'),
(185, 'Catania', 'IT', 'CTA', 'airport_as_city', '[\"CTA\"]', '[\"カターニア\"]'),
(186, 'Cebu City/Lapu-Lapu City', 'PH', 'CEB', 'airport_as_city', '[\"CEB\"]', '[\"セブ市/ラプラプ市\"]'),
(187, 'České Budějovice', 'CZ', 'JCL', 'airport_as_city', '[\"JCL\"]', '[\"チェスケー・ブジェヨヴィツェ\"]'),
(188, 'Chandigarh', 'IN', 'IXC', 'airport_as_city', '[\"IXC\"]', '[\"チャンディーガル\"]'),
(189, 'Changchun', 'CN', 'CGQ', 'airport_as_city', '[\"CGQ\"]', '[\"長春\", \"长春\"]'),
(190, 'Changsha (Changsha)', 'CN', 'CSX', 'airport_as_city', '[\"CSX\"]', '[\"長沙\", \"长沙\"]'),
(191, 'Charleroi', 'BE', 'CRL', 'airport_as_city', '[\"CRL\"]', '[\"シャルルロワ\"]'),
(192, 'Charleston', 'US', 'CHS', 'airport_as_city', '[\"CHS\"]', '[\"チャールストン\"]'),
(193, 'Charlestown', 'IE', 'NOC', 'airport_as_city', '[\"NOC\"]', '[\"ノック\",\"チャールズタウン\"]'),
(194, 'Charlotte', 'US', 'CLT', 'airport_as_city', '[\"CLT\"]', '[\"シャーロット\"]'),
(195, 'Charlotte Amalie', 'VI', 'STT', 'airport_as_city', '[\"STT\"]', '[\"シャーロット・アマリー\"]'),
(196, 'Chattogram (Chittagong)', 'BD', 'CGP', 'airport_as_city', '[\"CGP\"]', '[\"チャットグラム (チッタゴン)\"]'),
(197, 'Chelyabinsk', 'RU', 'CEK', 'airport_as_city', '[\"CEK\"]', '[\"チェリャビンスク\"]'),
(198, 'Chengdu (Jianyang)', 'CN', 'TFU', 'airport_as_city', '[\"TFU\"]', '[\"成都\"]'),
(199, 'Chengdu (Shuangliu)', 'CN', 'CTU', 'airport_as_city', '[\"CTU\"]', '[\"成都\"]'),
(200, 'Chennai', 'IN', 'MAA', 'airport_as_city', '[\"MAA\"]', '[\"チェンナイ\"]'),
(201, 'Cheongju', 'KR', 'CJJ', 'airport_as_city', '[\"CJJ\"]', '[\"清州\", \"청주\"]'),
(202, 'Chiang Mai', 'TH', 'CNX', 'airport_as_city', '[\"CNX\"]', '[\"チェンマイ\"]'),
(203, 'Chiang Rai', 'TH', 'CEI', 'airport_as_city', '[\"CEI\"]', '[\"チェンライ\"]'),
(204, 'Chicago', 'US', 'CHI', 'metropolitan', '[\"MDW\", \"ORD\"]', '[\"シカゴ\"]'),
(205, 'Chiclayo', 'PE', 'CIX', 'airport_as_city', '[\"CIX\"]', '[\"チクラーヨ\"]'),
(206, 'Chihuahua', 'MX', 'CUU', 'airport_as_city', '[\"CUU\"]', '[\"チワワ\"]'),
(207, 'Chişinău', 'MD', 'RMO', 'airport_as_city', '[\"RMO\"]', '[\"キシナウ\"]'),
(208, 'Chita', 'RU', 'HTA', 'airport_as_city', '[\"HTA\"]', '[\"チタ\"]'),
(209, 'Chlef', 'DZ', 'CFK', 'airport_as_city', '[\"CFK\"]', '[\"シュレフ\"]'),
(210, 'Chongqing', 'CN', 'CKG', 'airport_as_city', '[\"CKG\"]', '[\"重慶\", \"重庆\"]'),
(211, 'Christchurch', 'NZ', 'CHC', 'airport_as_city', '[\"CHC\"]', '[\"クライストチャーチ\"]'),
(212, 'Cincinnati / Covington', 'US', 'CVG', 'airport_as_city', '[\"CVG\"]', '[\"シンシナティ\",\"コビントン\"]'),
(213, 'Ciudad de la Costa', 'UY', 'MVD', 'airport_as_city', '[\"MVD\"]', '[\"シウダード・デ・ラ・コスタ\"]'),
(214, 'Ciudad del Este', 'PY', 'AGT', 'airport_as_city', '[\"AGT\"]', '[\"シウダー デル エステ\"]'),
(215, 'Ciudad Juárez', 'MX', 'CJS', 'airport_as_city', '[\"CJS\"]', '[\"シウダー・フアレス\"]'),
(216, 'Clermont-Ferrand', 'FR', 'CFE', 'airport_as_city', '[\"CFE\"]', '[\"クレルモン＝フェラン\"]'),
(217, 'Cleveland', 'US', 'CLE', 'airport_as_city', '[\"CLE\"]', '[\"クリーブランド\"]'),
(218, 'Cluj-Napoca', 'RO', 'CLJ', 'airport_as_city', '[\"CLJ\"]', '[\"クルジュ＝ナポカ\"]'),
(219, 'Cochabamba', 'BO', 'CBB', 'airport_as_city', '[\"CBB\"]', '[\"コチャバンバ\"]'),
(220, 'Coimbatore', 'IN', 'CJB', 'airport_as_city', '[\"CJB\"]', '[\"コインバトール\"]'),
(221, 'Colombier-Saugnieu, Rhône', 'FR', 'LYS', 'airport_as_city', '[\"LYS\"]', '[\"リヨン\",\"コロンビエ＝ソニュー\"]'),
(222, 'Colombo', 'LK', 'CMB', 'airport_as_city', '[\"CMB\"]', '[\"コロンボ\"]'),
(223, 'Colorado Springs', 'US', 'COS', 'airport_as_city', '[\"COS\"]', '[\"コロラドスプリングス\"]'),
(224, 'Columbus', 'US', 'CMH', 'airport_as_city', '[\"CMH\"]', '[\"コロンバス\"]'),
(225, 'Comodoro Rivadavia', 'AR', 'CRD', 'airport_as_city', '[\"CRD\"]', '[\"コモドロ リバダビア\"]'),
(226, 'Conakry', 'GN', 'CKY', 'airport_as_city', '[\"CKY\"]', '[\"コナクリ\"]'),
(227, 'Concepcion', 'CL', 'CCP', 'airport_as_city', '[\"CCP\"]', '[\"コンセプシオン\"]'),
(228, 'Constanța', 'RO', 'CND', 'airport_as_city', '[\"CND\"]', '[\"コンスタンツァ\"]'),
(229, 'Constantine', 'DZ', 'CZL', 'airport_as_city', '[\"CZL\"]', '[\"コンスタンティン\"]'),
(230, 'Copenhagen', 'DK', 'CPH', 'airport_as_city', '[\"CPH\"]', '[\"コペンハーゲン\"]'),
(231, 'Cordoba', 'AR', 'COR', 'airport_as_city', '[\"COR\"]', '[\"コルドバ\"]'),
(232, 'Corisco Island', 'GQ', 'OCS', 'airport_as_city', '[\"OCS\"]', '[\"コリスコ島\"]'),
(233, 'Cork', 'IE', 'ORK', 'airport_as_city', '[\"ORK\"]', '[\"コーク\"]'),
(234, 'Corvera', 'ES', 'RMU', 'airport_as_city', '[\"RMU\"]', '[\"ムルシア\",\"コルベラ\"]'),
(235, 'Cotonou', 'BJ', 'COO', 'airport_as_city', '[\"COO\"]', '[\"コトヌー\"]'),
(236, 'Coxen Hole', 'HN', 'RTB', 'airport_as_city', '[\"RTB\"]', '[\"コクセンホール\"]'),
(237, 'Cozumel', 'MX', 'CZM', 'airport_as_city', '[\"CZM\"]', '[\"コスメル\"]'),
(238, 'Craiova', 'RO', 'CRA', 'airport_as_city', '[\"CRA\"]', '[\"クラヨーヴァ\"]'),
(239, 'Cuiabá', 'BR', 'CGB', 'airport_as_city', '[\"CGB\"]', '[\"クイアバ\"]'),
(240, 'Culiacán', 'MX', 'CUL', 'airport_as_city', '[\"CUL\"]', '[\"クリアカン\"]'),
(241, 'Curitiba', 'BR', 'CWB', 'airport_as_city', '[\"CWB\"]', '[\"クリチバ\"]'),
(242, 'Cusco', 'PE', 'CUZ', 'airport_as_city', '[\"CUZ\"]', '[\"クスコ\"]'),
(243, 'Da Nang', 'VN', 'DAD', 'airport_as_city', '[\"DAD\"]', '[\"ダナン\"]'),
(244, 'Daegu', 'KR', 'TAE', 'airport_as_city', '[\"TAE\"]', '[\"大邱\", \"대구\"]'),
(245, 'Dakar', 'SN', 'DKR', 'metropolitan', '[\"DKR\", \"DSS\"]', '[\"ダカール\"]'),
(246, 'Dakhla', 'EH', 'VIL', 'airport_as_city', '[\"VIL\"]', '[\"ダフラ\"]'),
(247, 'Dalaman', 'TR', 'DLM', 'airport_as_city', '[\"DLM\"]', '[\"ダラマン\"]'),
(248, 'Dalian (Ganjingzi)', 'CN', 'DLC', 'airport_as_city', '[\"DLC\"]', '[\"大連\", \"大连\"]'),
(249, 'Dallas', 'US', 'DFW', 'metropolitan', '[\"DAL\", \"DFW\"]', '[\"ダラス\"]'),
(250, 'Dallas-Fort Worth', 'US', 'DFW', 'airport_as_city', '[\"DFW\"]', '[\"ダラス・フォートワース\",\"ダラスフォートワース\"]'),
(251, 'Damascus', 'SY', 'DAM', 'airport_as_city', '[\"DAM\"]', '[\"ダマスカス\"]'),
(252, 'Dar es Salaam', 'TZ', 'DAR', 'airport_as_city', '[\"DAR\"]', '[\"ダルエスサラーム\"]'),
(253, 'Darwin', 'AU', 'DRW', 'airport_as_city', '[\"DRW\"]', '[\"ダーウィン\"]'),
(254, 'Daşoguz', 'TM', 'TAZ', 'airport_as_city', '[\"TAZ\"]', '[\"ダショグズ\"]'),
(255, 'Datong', 'CN', 'DAT', 'airport_as_city', '[\"DAT\"]', '[\"大同\"]'),
(256, 'Davao', 'PH', 'DVO', 'airport_as_city', '[\"DVO\"]', '[\"ダバオ\"]'),
(257, 'Debrecen', 'HU', 'DEB', 'airport_as_city', '[\"DEB\"]', '[\"デブレツェン\"]'),
(258, 'Denver', 'US', 'DEN', 'airport_as_city', '[\"DEN\"]', '[\"デンバー\"]'),
(259, 'Des Moines', 'US', 'DSM', 'airport_as_city', '[\"DSM\"]', '[\"デモイン\"]'),
(260, 'Detroit', 'US', 'DTW', 'airport_as_city', '[\"DTW\"]', '[\"デトロイト\"]'),
(261, 'Dhaka', 'BD', 'DAC', 'airport_as_city', '[\"DAC\"]', '[\"ダッカ\"]'),
(262, 'Dili', 'TL', 'DIL', 'airport_as_city', '[\"DIL\"]', '[\"ディリ\"]'),
(263, 'Dire Dawa', 'ET', 'DIR', 'airport_as_city', '[\"DIR\"]', '[\"ディレ・ダワ\"]'),
(264, 'Djanet', 'DZ', 'DJG', 'airport_as_city', '[\"DJG\"]', '[\"ジャネット\"]'),
(265, 'Djibouti City', 'DJ', 'JIB', 'airport_as_city', '[\"JIB\"]', '[\"ジブチ市\"]'),
(266, 'Doha', 'QA', 'DIA', 'airport_as_city', '[\"DIA\"]', '[\"ドーハ\"]'),
(267, 'Dortmund', 'DE', 'DTM', 'airport_as_city', '[\"DTM\"]', '[\"ドルトムント\"]'),
(268, 'Douala', 'CM', 'DLA', 'airport_as_city', '[\"DLA\"]', '[\"ドゥアラ\"]'),
(269, 'Dresden', 'DE', 'DRS', 'airport_as_city', '[\"DRS\"]', '[\"ドレスデン\"]'),
(270, 'Dubai', 'AE', 'DXB', 'metropolitan', '[\"DWC\", \"DXB\"]', '[\"ドバイ\"]'),
(271, 'Dubai(Jebel Ali)', 'AE', 'DWC', 'airport_as_city', '[\"DWC\"]', '[\"ドバイ(ジェベル・アリ)\"]'),
(272, 'Dublin', 'IE', 'DUB', 'airport_as_city', '[\"DUB\"]', '[\"ダブリン\"]'),
(273, 'Dubrave Gornje', 'BA', 'TZL', 'airport_as_city', '[\"TZL\"]', '[\"トゥズラ\",\"ドゥブラヴェ・ゴルニェ\"]'),
(274, 'Dubrovnik', 'HR', 'DBV', 'airport_as_city', '[\"DBV\"]', '[\"ドゥブロヴニク\"]'),
(275, 'Dulles', 'US', 'IAD', 'airport_as_city', '[\"IAD\"]', '[\"ダレス\"]'),
(276, 'Dunhuang', 'CN', 'DNH', 'airport_as_city', '[\"DNH\"]', '[\"敦煌\"]'),
(277, 'Duqm', 'OM', 'DQM', 'airport_as_city', '[\"DQM\"]', '[\"ドゥクム\"]'),
(278, 'Durban', 'ZA', 'DUR', 'airport_as_city', '[\"DUR\"]', '[\"ダーバン\"]'),
(279, 'Dushanbe', 'TJ', 'DYU', 'airport_as_city', '[\"DYU\"]', '[\"ドゥシャンベ\"]'),
(280, 'Düsseldorf', 'DE', 'DUS', 'airport_as_city', '[\"DUS\"]', '[\"デュッセルドルフ\"]'),
(281, 'Dzaoudzi', 'YT', 'DZA', 'airport_as_city', '[\"DZA\"]', '[\"ザウジ\"]'),
(282, 'East London', 'ZA', 'ELS', 'airport_as_city', '[\"ELS\"]', '[\"イーストロンドン\"]'),
(283, 'Edmonton', 'CA', 'YEG', 'airport_as_city', '[\"YEG\"]', '[\"エドモントン\"]'),
(284, 'Edremit', 'TR', 'EDO', 'airport_as_city', '[\"EDO\"]', '[\"エドレミト\"]'),
(285, 'Eilat', 'IL', 'ETM', 'airport_as_city', '[\"ETM\"]', '[\"エイラート\"]'),
(286, 'Eindhoven', 'NL', 'EIN', 'airport_as_city', '[\"EIN\"]', '[\"アイントホーフェン\"]'),
(287, 'El Aaiún', 'EH', 'EUN', 'airport_as_city', '[\"EUN\"]', '[\"エル・アイウン\"]'),
(288, 'El Alamein', 'EG', 'DBB', 'airport_as_city', '[\"DBB\"]', '[\"エル・アラメイン\"]'),
(289, 'El Arish', 'EG', 'AAC', 'airport_as_city', '[\"AAC\"]', '[\"エル・アリシュ\"]'),
(290, 'El Matorral', 'ES', 'FUE', 'airport_as_city', '[\"FUE\"]', '[\"フエルテベントゥラ\",\"エル・マトラル\"]'),
(291, 'El Paso', 'US', 'ELP', 'airport_as_city', '[\"ELP\"]', '[\"エルパソ\"]'),
(292, 'Eldoret', 'KE', 'EDL', 'airport_as_city', '[\"EDL\"]', '[\"エルドレット\"]'),
(293, 'Encarnación', 'PY', 'ENO', 'airport_as_city', '[\"ENO\"]', '[\"エンカルナシオン\"]'),
(294, 'Enegu', 'NG', 'ENU', 'airport_as_city', '[\"ENU\"]', '[\"エネグ\"]'),
(295, 'Entebbe', 'UG', 'EBB', 'airport_as_city', '[\"EBB\"]', '[\"エンテベ\"]'),
(296, 'Erfurt', 'DE', 'ERF', 'airport_as_city', '[\"ERF\"]', '[\"エアフルト\"]'),
(297, 'Es-Sénia', 'DZ', 'ORN', 'airport_as_city', '[\"ORN\"]', '[\"エスセニア\"]'),
(298, 'Eskişehir', 'TR', 'AOE', 'airport_as_city', '[\"AOE\"]', '[\"エスキシェヒル\"]'),
(299, 'Espargos', 'CV', 'SID', 'airport_as_city', '[\"SID\"]', '[\"エスパルゴス\"]'),
(300, 'Evenes', 'NO', 'EVE', 'airport_as_city', '[\"EVE\"]', '[\"ハルスター\",\"エヴェネス\"]'),
(301, 'Ezhou', 'CN', 'EHU', 'airport_as_city', '[\"EHU\"]', '[\"鄂州\"]'),
(302, 'Faisalabad', 'PK', 'LYP', 'airport_as_city', '[\"LYP\"]', '[\"ファイサラーバード\"]'),
(303, 'Faro', 'PT', 'FAO', 'airport_as_city', '[\"FAO\"]', '[\"ファロ\"]'),
(304, 'Feldkirchen bei Graz', 'AT', 'GRZ', 'airport_as_city', '[\"GRZ\"]', '[\"グラーツ\",\"フェルトキルヒェン・バイ・グラーツ\"]'),
(305, 'Ferno (VA)', 'IT', 'MXP', 'airport_as_city', '[\"MXP\"]', '[\"ミラノ\",\"マルペンサ\",\"フェルノ\"]'),
(306, 'Figari', 'FR', 'FSC', 'airport_as_city', '[\"FSC\"]', '[\"フィガリ\"]'),
(307, 'Firenze (FI)', 'IT', 'FLR', 'airport_as_city', '[\"FLR\"]', '[\"フィレンツェ\"]'),
(308, 'Florianópolis', 'BR', 'FLN', 'airport_as_city', '[\"FLN\"]', '[\"フロリアノポリス\"]'),
(309, 'Fort-de-France', 'MQ', 'FDF', 'airport_as_city', '[\"FDF\"]', '[\"フォール・ド・フランス\"]'),
(310, 'Fort Lauderdale', 'US', 'FLL', 'airport_as_city', '[\"FLL\"]', '[\"フォートローダーデール\"]'),
(311, 'Fort Myers', 'US', 'RSW', 'airport_as_city', '[\"RSW\"]', '[\"フォートマイヤーズ\"]'),
(312, 'Fortaleza', 'BR', 'FOR', 'airport_as_city', '[\"FOR\"]', '[\"フォルタレザ\"]'),
(313, 'Foz do Iguaçu', 'BR', 'IGU', 'airport_as_city', '[\"IGU\"]', '[\"フォス ド イグアス\"]'),
(314, 'Francistown', 'BW', 'FRW', 'airport_as_city', '[\"FRW\"]', '[\"フランシスタウン\"]'),
(315, 'Frankfurt am Main', 'DE', 'FRA', 'airport_as_city', '[\"FRA\"]', '[\"フランクフルト\"]'),
(316, 'Frankfurt am Main (Lautzenhausen)', 'DE', 'HHN', 'airport_as_city', '[\"HHN\"]', '[\"フランクフルト\",\"ハーン\"]'),
(317, 'Freeport', 'BS', 'FPO', 'airport_as_city', '[\"FPO\"]', '[\"フリーポート\"]'),
(318, 'Freetown (Lungi-Town)', 'SL', 'FNA', 'airport_as_city', '[\"FNA\"]', '[\"フリータウン (ルンギタウン)\"]'),
(319, 'Fresno', 'US', 'FAT', 'airport_as_city', '[\"FAT\"]', '[\"フレズノ\"]'),
(320, 'Friedrichshafen', 'DE', 'FDH', 'airport_as_city', '[\"FDH\"]', '[\"フリードリヒスハーフェン\"]'),
(321, 'Fujairah', 'AE', 'FJR', 'airport_as_city', '[\"FJR\"]', '[\"フジャイラ\"]'),
(322, 'Fukuoka', 'JP', 'FUK', 'airport_as_city', '[\"FUK\"]', '[\"福岡\", \"ふくおか\"]'),
(323, 'Funchal', 'PT', 'FNC', 'airport_as_city', '[\"FNC\"]', '[\"フンシャル\"]'),
(324, 'Fuzhou (Changle)', 'CN', 'FOC', 'airport_as_city', '[\"FOC\"]', '[\"福州\"]'),
(325, 'Gaborone', 'BW', 'GBE', 'airport_as_city', '[\"GBE\"]', '[\"ハボローネ\"]'),
(326, 'Gan', 'MV', 'GAN', 'airport_as_city', '[\"GAN\"]', '[\"ガン\"]'),
(327, 'Ganja', 'AZ', 'GNJ', 'airport_as_city', '[\"GNJ\"]', '[\"ガンジャ\"]'),
(328, 'Garoua', 'CM', 'GOU', 'airport_as_city', '[\"GOU\"]', '[\"ガルア\"]'),
(329, 'Gautam Buddha Nagar', 'IN', 'DXN', 'airport_as_city', '[\"DXN\"]', '[\"ゴータマ・ブッダ・ナガル\"]'),
(330, 'Gaziantep', 'TR', 'GZT', 'airport_as_city', '[\"GZT\"]', '[\"ガズィアンテプ\"]'),
(331, 'Gaziemir', 'TR', 'ADB', 'airport_as_city', '[\"ADB\"]', '[\"イズミル\",\"ガジエミル\"]'),
(332, 'Gdańsk', 'PL', 'GDN', 'airport_as_city', '[\"GDN\"]', '[\"グダニスク\"]'),
(333, 'Geelong/Melbourne', 'AU', 'AVV', 'airport_as_city', '[\"AVV\"]', '[\"ジーロング\",\"メルボルン\"]'),
(334, 'General Santos', 'PH', 'GES', 'airport_as_city', '[\"GES\"]', '[\"ジェネラル・サントス\"]'),
(335, 'Geneva', 'CH', 'GVA', 'airport_as_city', '[\"GVA\"]', '[\"ジュネーヴ\"]'),
(336, 'Genova (GE)', 'IT', 'GOA', 'airport_as_city', '[\"GOA\"]', '[\"ジェノヴァ\"]'),
(337, 'George', 'ZA', 'GRJ', 'airport_as_city', '[\"GRJ\"]', '[\"ジョージ\"]'),
(338, 'George Town', 'KY', 'GCM', 'airport_as_city', '[\"GCM\"]', '[\"ジョージタウン\"]'),
(339, 'Georgetown', 'GY', 'GEO', 'airport_as_city', '[\"GEO\"]', '[\"ジョージタウン\"]'),
(340, 'Gerald\'s Park', 'MS', 'MNI', 'airport_as_city', '[\"MNI\"]', '[\"ジェラルズ パーク\"]'),
(341, 'Gibraltar', 'GI', 'GIB', 'airport_as_city', '[\"GIB\"]', '[\"ジブラルタル\"]'),
(342, 'Girona', 'ES', 'GRO', 'airport_as_city', '[\"GRO\"]', '[\"ジローナ\"]'),
(343, 'Glasgow', 'GB', 'GLA', 'airport_as_city', '[\"GLA\"]', '[\"グラスゴー\"]'),
(344, 'Goiânia', 'BR', 'GYN', 'airport_as_city', '[\"GYN\"]', '[\"ゴイアニア\"]'),
(345, 'Gold Coast', 'AU', 'OOL', 'airport_as_city', '[\"OOL\"]', '[\"ゴールドコースト\"]'),
(346, 'Goma', 'CD', 'GOM', 'airport_as_city', '[\"GOM\"]', '[\"ゴマ\"]'),
(347, 'Gonghang-ro', 'KR', 'YNY', 'airport_as_city', '[\"YNY\"]', '[\"襄陽\", \"양양\"]'),
(348, 'Göteborg', 'SE', 'GOT', 'airport_as_city', '[\"GOT\"]', '[\"ヨーテボリ\",\"ゴセンバーグ\"]'),
(349, 'Gqeberha (Port Elizabeth)', 'ZA', 'PLZ', 'airport_as_city', '[\"PLZ\"]', '[\"グケベラ (ポートエリザベス)\"]'),
(350, 'Gran Canaria Island', 'ES', 'LPA', 'airport_as_city', '[\"LPA\"]', '[\"グラン・カナリア島\"]'),
(351, 'Grand Rapids', 'US', 'GRR', 'airport_as_city', '[\"GRR\"]', '[\"グランドラピッズ\"]'),
(352, 'Greensboro', 'US', 'GSO', 'airport_as_city', '[\"GSO\"]', '[\"グリーンズボロ\"]'),
(353, 'Greven', 'DE', 'FMO', 'airport_as_city', '[\"FMO\"]', '[\"ミュンスター\",\"グレーヴェン\"]'),
(354, 'Groningen', 'NL', 'GRQ', 'airport_as_city', '[\"GRQ\"]', '[\"フローニンゲン\"]'),
(355, 'Grozny', 'RU', 'GRV', 'airport_as_city', '[\"GRV\"]', '[\"グロズヌイ\"]'),
(356, 'Guadalajara', 'MX', 'GDL', 'airport_as_city', '[\"GDL\"]', '[\"グアダラハラ\"]'),
(357, 'Guangzhou (Huadu)', 'CN', 'CAN', 'airport_as_city', '[\"CAN\"]', '[\"広州\", \"廣州\", \"广州\"]'),
(358, 'Guatemala City', 'GT', 'GUA', 'airport_as_city', '[\"GUA\"]', '[\"グアテマラシティ\"]'),
(359, 'Guayaquil', 'EC', 'GYE', 'airport_as_city', '[\"GYE\"]', '[\"グアヤキル\"]'),
(360, 'Guilin (Lingui)', 'CN', 'KWL', 'airport_as_city', '[\"KWL\"]', '[\"桂林\"]'),
(361, 'Guiyang (Nanming)', 'CN', 'KWE', 'airport_as_city', '[\"KWE\"]', '[\"貴陽\", \"贵阳\"]'),
(362, 'Gurandani', 'PK', 'GWD', 'airport_as_city', '[\"GWD\"]', '[\"グランダニ\"]'),
(363, 'Guwahati', 'IN', 'GAU', 'airport_as_city', '[\"GAU\"]', '[\"グワーハーティー\"]'),
(364, 'Guyana City', 'VE', 'PZO', 'airport_as_city', '[\"PZO\"]', '[\"ガイアナ市\"]'),
(365, 'Guzara', 'AF', 'HEA', 'airport_as_city', '[\"HEA\"]', '[\"グザラ\"]'),
(366, 'Gyumri', 'AM', 'LWN', 'airport_as_city', '[\"LWN\"]', '[\"ギュムリ\"]'),
(367, 'Haa Dhaalu Atoll', 'MV', 'HAQ', 'airport_as_city', '[\"HAQ\"]', '[\"ハーダール環礁\"]'),
(368, 'Hagåtña', 'GU', 'GUM', 'airport_as_city', '[\"GUM\"]', '[\"ハガニア\"]'),
(369, 'Haidong (Huzhu Tu Autonomous County)', 'CN', 'XNN', 'airport_as_city', '[\"XNN\"]', '[\"海東\", \"海东\", \"西寧\", \"西宁\"]'),
(370, 'Haikou (Meilan)', 'CN', 'HAK', 'airport_as_city', '[\"HAK\"]', '[\"海口\"]'),
(371, 'Hail', 'SA', 'HAS', 'airport_as_city', '[\"HAS\"]', '[\"あられ\"]'),
(372, 'Hailar', 'CN', 'HLD', 'airport_as_city', '[\"HLD\"]', '[\"海拉爾\", \"海拉尔\"]'),
(373, 'Haiphong (Hai An)', 'VN', 'HPH', 'airport_as_city', '[\"HPH\"]', '[\"ハイフォン（ハイアン）\"]'),
(374, 'Hakodate', 'JP', 'HKD', 'airport_as_city', '[\"HKD\"]', '[\"函館\", \"はこだて\"]'),
(375, 'Halifax', 'CA', 'YHZ', 'airport_as_city', '[\"YHZ\"]', '[\"ハリファックス\"]'),
(376, 'Halwara', 'IN', 'HWR', 'airport_as_city', '[\"HWR\"]', '[\"ハルワラ\"]'),
(377, 'Hamburg', 'DE', 'HAM', 'airport_as_city', '[\"HAM\"]', '[\"ハンブルク\"]'),
(378, 'Hamilton', 'BM', 'BDA', 'airport_as_city', '[\"BDA\"]', '[\"ハミルトン\"]'),
(379, 'Hanak', 'SA', 'RSI', 'airport_as_city', '[\"RSI\"]', '[\"ハナク\"]'),
(380, 'Hangzhou', 'CN', 'HGH', 'airport_as_city', '[\"HGH\"]', '[\"杭州\"]'),
(381, 'Hannover', 'DE', 'HAJ', 'airport_as_city', '[\"HAJ\"]', '[\"ハノーファー\"]'),
(382, 'Hanoi (Soc Son)', 'VN', 'HAN', 'airport_as_city', '[\"HAN\"]', '[\"ハノイ (ソクソン)\"]'),
(383, 'Harare', 'ZW', 'HRE', 'airport_as_city', '[\"HRE\"]', '[\"ハラレ\"]'),
(384, 'Harbin', 'CN', 'HRB', 'airport_as_city', '[\"HRB\"]', '[\"哈爾浜\", \"哈爾濱\", \"哈尔滨\"]'),
(385, 'Hargeisa', 'SO', 'HGA', 'airport_as_city', '[\"HGA\"]', '[\"ハルゲイサ\"]'),
(386, 'Hartford', 'US', 'BDL', 'airport_as_city', '[\"BDL\"]', '[\"ハートフォード\"]'),
(387, 'Hat Yai', 'TH', 'HDY', 'airport_as_city', '[\"HDY\"]', '[\"ハジャイ\"]'),
(388, 'Havana', 'CU', 'HAV', 'airport_as_city', '[\"HAV\"]', '[\"ハバナ\"]'),
(389, 'Hawassa', 'ET', 'AWA', 'airport_as_city', '[\"AWA\"]', '[\"ハワッサ\"]'),
(390, 'Hefei', 'CN', 'HFE', 'airport_as_city', '[\"HFE\"]', '[\"合肥\"]'),
(391, 'Helsinki (Vantaa)', 'FI', 'HEL', 'airport_as_city', '[\"HEL\"]', '[\"ヘルシンキ\",\"ヴァンター\"]'),
(392, 'Heraklion', 'GR', 'HER', 'airport_as_city', '[\"HER\"]', '[\"イラクリオン\"]'),
(393, 'Hermosillo', 'MX', 'HMO', 'airport_as_city', '[\"HMO\"]', '[\"エルモシヨ\"]'),
(394, 'Hiroshima', 'JP', 'HIJ', 'airport_as_city', '[\"HIJ\"]', '[\"広島\", \"ひろしま\"]'),
(395, 'Hisar', 'IN', 'HSS', 'airport_as_city', '[\"HSS\"]', '[\"ヒサール\"]'),
(396, 'Ho Chi Minh City', 'VN', 'SGN', 'airport_as_city', '[\"SGN\"]', '[\"ホーチミン\", \"ホーチミン市\"]'),
(397, 'Hobart (Cambridge)', 'AU', 'HBA', 'airport_as_city', '[\"HBA\"]', '[\"ホバート\"]'),
(398, 'Hofuf', 'SA', 'HOF', 'airport_as_city', '[\"HOF\"]', '[\"ホフーフ\"]'),
(399, 'Hohhot', 'CN', 'HET', 'airport_as_city', '[\"HET\"]', '[\"呼和浩特\"]'),
(400, 'Holguin', 'CU', 'HOG', 'airport_as_city', '[\"HOG\"]', '[\"オルギン\"]'),
(401, 'Hong Kong', 'HK', 'HKG', 'airport_as_city', '[\"HKG\"]', '[\"香港\", \"ホンコン\"]'),
(402, 'Honiara', 'SB', 'HIR', 'airport_as_city', '[\"HIR\"]', '[\"ホニアラ\"]'),
(403, 'Honolulu, Oahu', 'US', 'HNL', 'airport_as_city', '[\"HNL\"]', '[\"ホノルル\",\"オアフ島\"]'),
(404, 'Houston', 'US', 'HOU', 'metropolitan', '[\"HOU\", \"IAH\"]', '[\"ヒューストン\"]'),
(405, 'Huai\'an', 'CN', 'HIA', 'airport_as_city', '[\"HIA\"]', '[\"淮安\"]'),
(406, 'Hualien City', 'TW', 'HUN', 'airport_as_city', '[\"HUN\"]', '[\"花蓮\"]'),
(407, 'Huangshan', 'CN', 'TXN', 'airport_as_city', '[\"TXN\"]', '[\"黃山\", \"黄山\"]'),
(408, 'Huatulco', 'MX', 'HUX', 'airport_as_city', '[\"HUX\"]', '[\"ワタルコ\"]'),
(409, 'Hurghada', 'EG', 'HRG', 'airport_as_city', '[\"HRG\"]', '[\"ハルガダ\"]'),
(410, 'Huxi', 'TW', 'MZG', 'airport_as_city', '[\"MZG\"]', '[\"湖西\", \"澎湖\"]'),
(411, 'Hyderabad', 'IN', 'HYD', 'airport_as_city', '[\"HYD\"]', '[\"ハイデラバード\"]'),
(412, 'Iaşi', 'RO', 'IAS', 'airport_as_city', '[\"IAS\"]', '[\"ヤシ\"]'),
(413, 'Ibiza (Eivissa)', 'ES', 'IBZ', 'airport_as_city', '[\"IBZ\"]', '[\"イビサ\"]'),
(414, 'Ilinden', 'MK', 'SKP', 'airport_as_city', '[\"SKP\"]', '[\"スコピエ\",\"イリンデン\"]'),
(415, 'Ilorin/Ogbomosho', 'NG', 'ILR', 'airport_as_city', '[\"ILR\"]', '[\"イロリン/オグボモショ\"]'),
(416, 'Imphal', 'IN', 'IMF', 'airport_as_city', '[\"IMF\"]', '[\"インパール\"]'),
(417, 'Indianapolis', 'US', 'IND', 'airport_as_city', '[\"IND\"]', '[\"インディアナポリス\"]'),
(418, 'Indore', 'IN', 'IDR', 'airport_as_city', '[\"IDR\"]', '[\"インドール\"]'),
(419, 'Ingliston, Edinburgh', 'GB', 'EDI', 'airport_as_city', '[\"EDI\"]', '[\"エディンバラ\",\"イングリストン\"]'),
(420, 'Innsbruck', 'AT', 'INN', 'airport_as_city', '[\"INN\"]', '[\"インスブルック\"]'),
(421, 'Ipoh', 'MY', 'IPH', 'airport_as_city', '[\"IPH\"]', '[\"イポー\"]'),
(422, 'Iquique', 'CL', 'IQQ', 'airport_as_city', '[\"IQQ\"]', '[\"イキケ\"]'),
(423, 'Iquitos', 'PE', 'IQT', 'airport_as_city', '[\"IQT\"]', '[\"イキトス\"]'),
(424, 'Irkutsk', 'RU', 'IKT', 'airport_as_city', '[\"IKT\"]', '[\"イルクーツク\"]'),
(425, 'Isfahan', 'IR', 'IFN', 'airport_as_city', '[\"IFN\"]', '[\"イスファハン\"]'),
(426, 'Isla De Pascua', 'CL', 'IPC', 'airport_as_city', '[\"IPC\"]', '[\"イスラ・デ・パスクア\"]'),
(427, 'Isla Margarita', 'VE', 'PMV', 'airport_as_city', '[\"PMV\"]', '[\"マルガリータ島\"]'),
(428, 'Istanbul', 'TR', 'IST', 'metropolitan', '[\"ISL\", \"IST\", \"SAW\"]', '[\"イスタンブール\"]'),
(429, 'Ivalo', 'FI', 'IVL', 'airport_as_city', '[\"IVL\"]', '[\"イヴァロ\"]'),
(430, 'Ixtapa', 'MX', 'ZIH', 'airport_as_city', '[\"ZIH\"]', '[\"イスタパ\"]'),
(431, 'Jacksonville', 'US', 'JAX', 'airport_as_city', '[\"JAX\"]', '[\"ジャクソンビル\"]'),
(432, 'Jaffna', 'LK', 'JAF', 'airport_as_city', '[\"JAF\"]', '[\"ジャフナ\"]'),
(433, 'Jaipur', 'IN', 'JAI', 'airport_as_city', '[\"JAI\"]', '[\"ジャイプール\"]'),
(434, 'Jakarta', 'ID', 'JKT', 'metropolitan', '[\"CGK\", \"HLP\"]', '[\"ジャカルタ\"]'),
(435, 'Jasionka', 'PL', 'RZE', 'airport_as_city', '[\"RZE\"]', '[\"ジェシュフ\",\"ヤションカ\"]'),
(436, 'Jeddah', 'SA', 'JED', 'airport_as_city', '[\"JED\"]', '[\"ジェッダ\"]'),
(437, 'Jeju City', 'KR', 'CJU', 'airport_as_city', '[\"CJU\"]', '[\"済州\", \"濟州\", \"제주\"]'),
(438, 'Jiayuguan', 'CN', 'JGN', 'airport_as_city', '[\"JGN\"]', '[\"嘉峪関\", \"嘉峪關\", \"嘉峪关\"]'),
(439, 'Jieyang (Rongcheng)', 'CN', 'SWA', 'airport_as_city', '[\"SWA\"]', '[\"揭陽\", \"揭阳\"]'),
(440, 'Jijiga', 'ET', 'JIJ', 'airport_as_city', '[\"JIJ\"]', '[\"ジジガ\"]'),
(441, 'Jinan (Licheng)', 'CN', 'TNA', 'airport_as_city', '[\"TNA\"]', '[\"済南\", \"濟南\", \"济南\"]'),
(442, 'Jinghong (Gasa)', 'CN', 'JHG', 'airport_as_city', '[\"JHG\"]', '[\"景洪\"]'),
(443, 'João Pessoa', 'BR', 'JPA', 'airport_as_city', '[\"JPA\"]', '[\"ジョアン ペソア\"]'),
(444, 'Johannesburg', 'ZA', 'JNB', 'metropolitan', '[\"HLA\"]', '[\"ヨハネスブルグ\"]'),
(445, 'Johor Bahru', 'MY', 'JHB', 'airport_as_city', '[\"JHB\"]', '[\"ジョホールバル\"]'),
(446, 'Juba', 'SS', 'JUB', 'airport_as_city', '[\"JUB\"]', '[\"ジュバ\"]'),
(447, 'Juliaca', 'PE', 'JUL', 'airport_as_city', '[\"JUL\"]', '[\"フリアカ\"]'),
(448, 'Kabul', 'AF', 'KBL', 'airport_as_city', '[\"KBL\"]', '[\"カブール\"]'),
(449, 'Kaduna', 'NG', 'KAD', 'airport_as_city', '[\"KAD\"]', '[\"カドゥナ\"]'),
(450, 'Kagoshima', 'JP', 'KOJ', 'airport_as_city', '[\"KOJ\"]', '[\"鹿児島\", \"かごしま\"]'),
(451, 'Kahului', 'US', 'OGG', 'airport_as_city', '[\"OGG\"]', '[\"カフルイ\"]'),
(452, 'Kailua-Kona', 'US', 'KOA', 'airport_as_city', '[\"KOA\"]', '[\"カイルア・コナ\",\"コナ\"]'),
(453, 'Kakadi', 'IN', 'SAG', 'airport_as_city', '[\"SAG\"]', '[\"カカディ\"]'),
(454, 'Kalibo', 'PH', 'KLO', 'airport_as_city', '[\"KLO\"]', '[\"カリボ\"]'),
(455, 'Kaliningrad', 'RU', 'KGD', 'airport_as_city', '[\"KGD\"]', '[\"カリーニングラード\"]'),
(456, 'Kanazawa', 'JP', 'KMQ', 'airport_as_city', '[\"KMQ\"]', '[\"金沢\"]'),
(457, 'Kandahar', 'AF', 'KDH', 'airport_as_city', '[\"KDH\"]', '[\"カンダハル\"]'),
(458, 'Kannur', 'IN', 'CNN', 'airport_as_city', '[\"CNN\"]', '[\"カンヌール\"]'),
(459, 'Kano', 'NG', 'KAN', 'airport_as_city', '[\"KAN\"]', '[\"カノ\"]'),
(460, 'Kansas City', 'US', 'MCI', 'airport_as_city', '[\"MCI\"]', '[\"カンザスシティ\"]'),
(461, 'Kaohsiung (Xiaogang)', 'TW', 'KHH', 'airport_as_city', '[\"KHH\"]', '[\"高雄\"]'),
(462, 'Karachi', 'PK', 'KHI', 'airport_as_city', '[\"KHI\"]', '[\"カラチ\"]'),
(463, 'Karaganda', 'KZ', 'KGF', 'airport_as_city', '[\"KGF\"]', '[\"カラガンダ\"]'),
(464, 'Karaj', 'IR', 'PYK', 'airport_as_city', '[\"PYK\"]', '[\"カラジ\"]'),
(465, 'Karlovy Vary', 'CZ', 'KLV', 'airport_as_city', '[\"KLV\"]', '[\"カルロヴィ・ヴァリ\"]'),
(466, 'Kasane', 'BW', 'BBK', 'airport_as_city', '[\"BBK\"]', '[\"かさね\"]'),
(467, 'Kashgar', 'CN', 'KHG', 'airport_as_city', '[\"KHG\"]', '[\"喀什\"]'),
(468, 'Kathmandu', 'NP', 'KTM', 'airport_as_city', '[\"KTM\"]', '[\"カトマンズ\"]'),
(469, 'Katowice', 'PL', 'KTW', 'airport_as_city', '[\"KTW\"]', '[\"カトヴィツェ\"]'),
(470, 'Kaunas', 'LT', 'KUN', 'airport_as_city', '[\"KUN\"]', '[\"カウナス\"]'),
(471, 'Kavala', 'GR', 'KVA', 'airport_as_city', '[\"KVA\"]', '[\"カヴァラ\"]'),
(472, 'Kayseri', 'TR', 'ASR', 'airport_as_city', '[\"ASR\"]', '[\"カイセリ\"]'),
(473, 'Kazan', 'RU', 'KZN', 'airport_as_city', '[\"KZN\"]', '[\"カザン\"]'),
(474, 'Kelowna', 'CA', 'YLW', 'airport_as_city', '[\"YLW\"]', '[\"ケロウナ\"]'),
(475, 'Kemerovo', 'RU', 'KEJ', 'airport_as_city', '[\"KEJ\"]', '[\"ケメロヴォ\"]'),
(476, 'Kerkyra (Corfu)', 'GR', 'CFU', 'airport_as_city', '[\"CFU\"]', '[\"コルフ島\",\"ケルキラ\"]'),
(477, 'Kerman', 'IR', 'KER', 'airport_as_city', '[\"KER\"]', '[\"ケルマン\"]'),
(478, 'Khartoum', 'SD', 'KRT', 'airport_as_city', '[\"KRT\"]', '[\"ハルツーム\"]'),
(479, 'Khujand', 'TJ', 'LBD', 'airport_as_city', '[\"LBD\"]', '[\"ホジェンド\"]'),
(480, 'Kigali', 'RW', 'KGL', 'airport_as_city', '[\"KGL\"]', '[\"キガリ\"]'),
(481, 'Kimberley', 'ZA', 'KIM', 'airport_as_city', '[\"KIM\"]', '[\"キンバリー\"]'),
(482, 'Kingston', 'JM', 'KIN', 'airport_as_city', '[\"KIN\"]', '[\"キングストン\"]'),
(483, 'Kingstown', 'VC', 'SVD', 'airport_as_city', '[\"SVD\"]', '[\"キングスタウン\"]'),
(484, 'Kinshasa', 'CD', 'FIH', 'airport_as_city', '[\"FIH\"]', '[\"キンシャサ\"]'),
(485, 'Kiritimati', 'KI', 'CXI', 'airport_as_city', '[\"CXI\"]', '[\"キリティマティ\"]'),
(486, 'Kirkuk', 'IQ', 'KIK', 'airport_as_city', '[\"KIK\"]', '[\"キルクーク\"]'),
(487, 'Kiruna', 'SE', 'KRN', 'airport_as_city', '[\"KRN\"]', '[\"キルナ\"]'),
(488, 'Kisangani', 'CD', 'FKI', 'airport_as_city', '[\"FKI\"]', '[\"キサンガニ\"]'),
(489, 'Kish Island', 'IR', 'KIH', 'airport_as_city', '[\"KIH\"]', '[\"キシュ島\"]'),
(490, 'Kisumu', 'KE', 'KIS', 'airport_as_city', '[\"KIS\"]', '[\"キスム\"]'),
(491, 'Kitakyushu', 'JP', 'KKJ', 'airport_as_city', '[\"KKJ\"]', '[\"北九州\", \"きたきゅうしゅう\"]'),
(492, 'Kittilä', 'FI', 'KTT', 'airport_as_city', '[\"KTT\"]', '[\"キッティラ\"]'),
(493, 'Klagenfurt am Wörthersee', 'AT', 'KLU', 'airport_as_city', '[\"KLU\"]', '[\"クラーゲンフルト\"]'),
(494, 'Knoxville/Maryville', 'US', 'TYS', 'airport_as_city', '[\"TYS\"]', '[\"ノックスビル\",\"メアリービル\"]'),
(495, 'Kobe', 'JP', 'UKB', 'airport_as_city', '[\"UKB\"]', '[\"神戸\", \"こうべ\"]'),
(496, 'Kochi', 'IN', 'COK', 'airport_as_city', '[\"COK\"]', '[\"高知\", \"こうち\"]'),
(497, 'Kokshetau', 'KZ', 'KOV', 'airport_as_city', '[\"KOV\"]', '[\"コクシェタウ\"]'),
(498, 'Kolkata', 'IN', 'CCU', 'airport_as_city', '[\"CCU\"]', '[\"コルカタ\"]'),
(499, 'Köln (Cologne)', 'DE', 'CGN', 'airport_as_city', '[\"CGN\"]', '[\"ケルン\",\"コロン\"]'),
(500, 'Konya', 'TR', 'KYA', 'airport_as_city', '[\"KYA\"]', '[\"コンヤ\"]'),
(501, 'Kopitnari', 'GE', 'KUT', 'airport_as_city', '[\"KUT\"]', '[\"コピトナリ\"]'),
(502, 'Kos Island', 'GR', 'KGS', 'airport_as_city', '[\"KGS\"]', '[\"コス島\"]'),
(503, 'Kostanay', 'KZ', 'KSN', 'airport_as_city', '[\"KSN\"]', '[\"コスタナイ\"]'),
(504, 'Kota Kinabalu', 'MY', 'BKI', 'airport_as_city', '[\"BKI\"]', '[\"コタキナバル\"]'),
(505, 'Krabi', 'TH', 'KBV', 'airport_as_city', '[\"KBV\"]', '[\"クラビ\"]'),
(506, 'Kralendijk', 'BQ', 'BON', 'airport_as_city', '[\"BON\"]', '[\"クラレンダイク\"]'),
(507, 'Krasnodar', 'RU', 'KRR', 'airport_as_city', '[\"KRR\"]', '[\"クラスノダール\"]'),
(508, 'Krasnoyarsk', 'RU', 'KJA', 'airport_as_city', '[\"KJA\"]', '[\"クラスノヤルスク\"]'),
(509, 'Kristiansand(Kjevik)', 'NO', 'KRS', 'airport_as_city', '[\"KRS\"]', '[\"クリスチャンサン\"]'),
(510, 'Kuching', 'MY', 'KCH', 'airport_as_city', '[\"KCH\"]', '[\"クチン\"]'),
(511, 'Kulob', 'TJ', 'TJU', 'airport_as_city', '[\"TJU\"]', '[\"クリャーブ\"]'),
(512, 'Kumamoto', 'JP', 'KMJ', 'airport_as_city', '[\"KMJ\"]', '[\"熊本\", \"くまもと\"]'),
(513, 'Kumasi', 'GH', 'KMS', 'airport_as_city', '[\"KMS\"]', '[\"クマシ\"]'),
(514, 'Kunming', 'CN', 'KMG', 'airport_as_city', '[\"KMG\"]', '[\"昆明\"]'),
(515, 'Kuopio / Siilinjärvi', 'FI', 'KUO', 'airport_as_city', '[\"KUO\"]', '[\"クオピオ\",\"シーリンヤルヴィ\"]'),
(516, 'Kuta, Badung', 'ID', 'DPS', 'airport_as_city', '[\"DPS\"]', '[\"クタ、バドゥン\"]'),
(517, 'Kuwait City', 'KW', 'KWI', 'airport_as_city', '[\"KWI\"]', '[\"クウェートシティ\"]'),
(518, 'Kyiv', 'UA', 'IEV', 'metropolitan', '[\"IEV\", \"KBP\"]', '[\"キーウ\",\"キエフ\"]'),
(519, 'Kyzylorda', 'KZ', 'KZO', 'airport_as_city', '[\"KZO\"]', '[\"クズロルダ\"]'),
(520, 'La Paz / El Alto', 'BO', 'LPB', 'airport_as_city', '[\"LPB\"]', '[\"ラパス/エルアルト\"]'),
(521, 'La Romana', 'DO', 'LRM', 'airport_as_city', '[\"LRM\"]', '[\"ラ・ロマーナ\"]'),
(522, 'Lae', 'PG', 'LAE', 'airport_as_city', '[\"LAE\"]', '[\"ラエ\"]'),
(523, 'Lagos', 'NG', 'LOS', 'airport_as_city', '[\"LOS\"]', '[\"ラゴス\"]'),
(524, 'Laguindingan', 'PH', 'CGY', 'airport_as_city', '[\"CGY\"]', '[\"ラギンディンガン\"]'),
(525, 'Lahore', 'PK', 'LHE', 'airport_as_city', '[\"LHE\"]', '[\"ラホール\"]'),
(526, 'Lamezia Terme (CZ)', 'IT', 'SUF', 'airport_as_city', '[\"SUF\"]', '[\"ラメーツィア・テルメ\"]'),
(527, 'Langkawi', 'MY', 'LGK', 'airport_as_city', '[\"LGK\"]', '[\"ランカウイ\"]'),
(528, 'Lanzhou (Yongdeng)', 'CN', 'LHW', 'airport_as_city', '[\"LHW\"]', '[\"蘭州\", \"兰州\"]'),
(529, 'Laoag City', 'PH', 'LAO', 'airport_as_city', '[\"LAO\"]', '[\"ラオアグ市\"]'),
(530, 'Lappeenranta', 'FI', 'LPP', 'airport_as_city', '[\"LPP\"]', '[\"ラッペーンランタ\"]'),
(531, 'Larnaca', 'CY', 'LCA', 'airport_as_city', '[\"LCA\"]', '[\"ラルナカ\"]'),
(532, 'Las Vegas', 'US', 'LAS', 'airport_as_city', '[\"LAS\"]', '[\"ラスベガス\"]'),
(533, 'Leeds, West Yorkshire', 'GB', 'LBA', 'airport_as_city', '[\"LBA\"]', '[\"リーズ\"]'),
(534, 'Legazpi', 'PH', 'DRP', 'airport_as_city', '[\"DRP\"]', '[\"レガスピ\"]'),
(535, 'Lesquin', 'FR', 'LIL', 'airport_as_city', '[\"LIL\"]', '[\"リール\",\"レスカン\"]'),
(536, 'Lianyungang', 'CN', 'LYG', 'airport_as_city', '[\"LYG\"]', '[\"連雲港\", \"连云港\"]'),
(537, 'Liberia', 'CR', 'LIR', 'airport_as_city', '[\"LIR\"]', '[\"リベリア\"]'),
(538, 'Libreville', 'GA', 'LBV', 'airport_as_city', '[\"LBV\"]', '[\"リーブルヴィル\"]'),
(539, 'Lihue, Kauai', 'US', 'LIH', 'airport_as_city', '[\"LIH\"]', '[\"リフエ\",\"カウアイ島\"]'),
(540, 'Lijiang', 'CN', 'LJG', 'airport_as_city', '[\"LJG\"]', '[\"麗江\", \"丽江\"]'),
(541, 'Lima', 'PE', 'LIM', 'airport_as_city', '[\"LIM\"]', '[\"リマ\"]'),
(542, 'Linköping', 'SE', 'LPI', 'airport_as_city', '[\"LPI\"]', '[\"リンシェーピング\"]'),
(543, 'Linz', 'AT', 'LNZ', 'airport_as_city', '[\"LNZ\"]', '[\"リンツ\"]'),
(544, 'Lisbon', 'PT', 'LIS', 'airport_as_city', '[\"LIS\"]', '[\"リスボン\"]'),
(545, 'Liverpool', 'GB', 'LPL', 'airport_as_city', '[\"LPL\"]', '[\"リバプール\"]'),
(546, 'Livingstone', 'ZM', 'LVI', 'airport_as_city', '[\"LVI\"]', '[\"リヴィングストン\"]'),
(547, 'Lomé', 'TG', 'LFW', 'airport_as_city', '[\"LFW\"]', '[\"ロメ\"]'),
(548, 'London', 'GB', 'LON', 'metropolitan', '[\"LCY\", \"LGW\", \"LHR\", \"LTN\", \"STN\"]', '[\"ロンドン\"]'),
(549, 'London, Essex', 'GB', 'STN', 'airport_as_city', '[\"STN\"]', '[\"ロンドン\",\"スタンステッド\",\"エセックス\"]'),
(550, 'Long Beach', 'US', 'LGB', 'airport_as_city', '[\"LGB\"]', '[\"ロングビーチ\"]'),
(551, 'Loreto', 'MX', 'LTO', 'airport_as_city', '[\"LTO\"]', '[\"ロレト\"]'),
(552, 'Los Angeles', 'US', 'LAX', 'airport_as_city', '[\"LAX\"]', '[\"ロサンゼルス\"]'),
(553, 'Louisville', 'US', 'SDF', 'airport_as_city', '[\"SDF\"]', '[\"ルイビル\"]'),
(554, 'Luanda', 'AO', 'LAD', 'airport_as_city', '[\"LAD\"]', '[\"ルアンダ\"]'),
(555, 'Luanda (Ícolo e Bengo)', 'AO', 'NBJ', 'airport_as_city', '[\"NBJ\"]', '[\"ルアンダ (イコロ エ ベンゴ)\"]'),
(556, 'Luang Phabang', 'LA', 'LPQ', 'airport_as_city', '[\"LPQ\"]', '[\"ルアンパバーン\"]'),
(557, 'Lublin', 'PL', 'LUZ', 'airport_as_city', '[\"LUZ\"]', '[\"ルブリン\"]'),
(558, 'Lubumbashi', 'CD', 'FBM', 'airport_as_city', '[\"FBM\"]', '[\"ルブンバシ\"]'),
(559, 'Lucknow', 'IN', 'LKO', 'airport_as_city', '[\"LKO\"]', '[\"ラクナウ\"]'),
(560, 'Luleå', 'SE', 'LLA', 'airport_as_city', '[\"LLA\"]', '[\"ルレオ\"]'),
(561, 'Lumbadzi', 'MW', 'LLW', 'airport_as_city', '[\"LLW\"]', '[\"ルンバジ\"]'),
(562, 'Luoyang (Laocheng)', 'CN', 'LYA', 'airport_as_city', '[\"LYA\"]', '[\"洛陽\", \"洛阳\"]'),
(563, 'Lusaka', 'ZM', 'LUN', 'airport_as_city', '[\"LUN\"]', '[\"ルサカ\"]'),
(564, 'Luton, Luton', 'GB', 'LTN', 'airport_as_city', '[\"LTN\"]', '[\"ロンドン\",\"ルートン\"]'),
(565, 'Luxembourg', 'LU', 'LUX', 'airport_as_city', '[\"LUX\"]', '[\"ルクセンブルク\"]'),
(566, 'Luxor', 'EG', 'LXR', 'airport_as_city', '[\"LXR\"]', '[\"ルクソール\"]'),
(567, 'Lviv', 'UA', 'LWO', 'airport_as_city', '[\"LWO\"]', '[\"リヴィウ\",\"リビウ\"]'),
(568, 'Maastricht', 'NL', 'MST', 'airport_as_city', '[\"MST\"]', '[\"マーストリヒト\"]'),
(569, 'Mabalacat', 'PH', 'CRK', 'airport_as_city', '[\"CRK\"]', '[\"マバラカット\"]'),
(570, 'Maceió', 'BR', 'MCZ', 'airport_as_city', '[\"MCZ\"]', '[\"マセイオ\"]'),
(571, 'Madrid', 'ES', 'MAD', 'airport_as_city', '[\"MAD\"]', '[\"マドリード\"]'),
(572, 'Magnitogorsk', 'RU', 'MQF', 'airport_as_city', '[\"MQF\"]', '[\"マグニトゴルスク\"]'),
(573, 'Mahajanga', 'MG', 'MJN', 'airport_as_city', '[\"MJN\"]', '[\"マハジャンガ\"]'),
(574, 'Mahón (Maó)', 'ES', 'MAH', 'airport_as_city', '[\"MAH\"]', '[\"メノルカ島\",\"マオー\"]'),
(575, 'Mahovljani', 'BA', 'BNX', 'airport_as_city', '[\"BNX\"]', '[\"バニャ・ルカ\",\"マホヴリャニ\"]'),
(576, 'Maiduguri', 'NG', 'MIU', 'airport_as_city', '[\"MIU\"]', '[\"マイドゥグリ\"]'),
(577, 'Maiquetía', 'VE', 'CCS', 'airport_as_city', '[\"CCS\"]', '[\"マイケティア\"]'),
(578, 'Majuro Atoll', 'MH', 'MAJ', 'airport_as_city', '[\"MAJ\"]', '[\"マジュロ環礁\"]'),
(579, 'Makassar', 'ID', 'UPG', 'airport_as_city', '[\"UPG\"]', '[\"マカッサル\"]'),
(580, 'Makhachkala', 'RU', 'MCX', 'airport_as_city', '[\"MCX\"]', '[\"マハチカラ\"]'),
(581, 'Makinohara / Shimada', 'JP', 'FSZ', 'airport_as_city', '[\"FSZ\"]', '[\"牧之原・島田\"]'),
(582, 'Malabo', 'GQ', 'SSG', 'airport_as_city', '[\"SSG\"]', '[\"マラボ\"]'),
(583, 'Málaga', 'ES', 'AGP', 'airport_as_city', '[\"AGP\"]', '[\"マラガ\"]'),
(584, 'Malé', 'MV', 'MLE', 'airport_as_city', '[\"MLE\"]', '[\"マレ\"]'),
(585, 'Malmö', 'SE', 'MMX', 'airport_as_city', '[\"MMX\"]', '[\"マルメ\"]'),
(586, 'Malung-Sälen', 'SE', 'SCR', 'airport_as_city', '[\"SCR\"]', '[\"セーレン\",\"マルング\"]'),
(587, 'Manado', 'ID', 'MDC', 'airport_as_city', '[\"MDC\"]', '[\"マナド\"]'),
(588, 'Managua', 'NI', 'MGA', 'airport_as_city', '[\"MGA\"]', '[\"マナグア\"]'),
(589, 'Manama', 'BH', 'BAH', 'airport_as_city', '[\"BAH\"]', '[\"マナマ\"]'),
(590, 'Manaus', 'BR', 'MAO', 'airport_as_city', '[\"MAO\"]', '[\"マナウス\"]'),
(591, 'Manchester, Greater Manchester', 'GB', 'MAN', 'airport_as_city', '[\"MAN\"]', '[\"マンチェスター\"]'),
(592, 'Mandalay', 'MM', 'MDL', 'airport_as_city', '[\"MDL\"]', '[\"マンダレー\"]'),
(593, 'Mangaluru', 'IN', 'IXE', 'airport_as_city', '[\"IXE\"]', '[\"マンガルル\"]'),
(594, 'Manila (Pasay)', 'PH', 'MNL', 'airport_as_city', '[\"MNL\"]', '[\"マニラ（パサイ）\"]'),
(595, 'Maputo', 'MZ', 'MPM', 'airport_as_city', '[\"MPM\"]', '[\"マプト\"]'),
(596, 'Maracaibo', 'VE', 'MAR', 'airport_as_city', '[\"MAR\"]', '[\"マラカイボ\"]'),
(597, 'Marignane, Bouches-du-Rhône', 'FR', 'MRS', 'airport_as_city', '[\"MRS\"]', '[\"マルセイユ\",\"マリニャーヌ\"]'),
(598, 'Maroochydore', 'AU', 'MCY', 'airport_as_city', '[\"MCY\"]', '[\"サンシャインコースト\",\"マルーチードール\"]'),
(599, 'Marrakesh', 'MA', 'RAK', 'airport_as_city', '[\"RAK\"]', '[\"マラケシュ\"]'),
(600, 'Marsa Alam', 'EG', 'RMF', 'airport_as_city', '[\"RMF\"]', '[\"マルサ アラム\"]'),
(601, 'Marsa Matruh', 'EG', 'MUH', 'airport_as_city', '[\"MUH\"]', '[\"マルサ・マトルー\"]'),
(602, 'Maseru(Mazenod)', 'LS', 'MSU', 'airport_as_city', '[\"MSU\"]', '[\"マセル(マゼノド)\"]'),
(603, 'Mashhad', 'IR', 'MHD', 'airport_as_city', '[\"MHD\"]', '[\"マシュハド\"]'),
(604, 'Matanzas', 'CU', 'VRA', 'airport_as_city', '[\"VRA\"]', '[\"マタンサス\"]'),
(605, 'Mataram (Pujut, Lombok Tengah)', 'ID', 'LOP', 'airport_as_city', '[\"LOP\"]', '[\"マタラム (ロンボク島テンガ州プジュット)\"]'),
(606, 'Matoury', 'GF', 'CAY', 'airport_as_city', '[\"CAY\"]', '[\"マトゥーリー\"]'),
(607, 'Matsuyama', 'JP', 'MYJ', 'airport_as_city', '[\"MYJ\"]', '[\"松山\", \"まつやま\"]'),
(608, 'Maun', 'BW', 'MUB', 'airport_as_city', '[\"MUB\"]', '[\"マウン\"]'),
(609, 'Mazar-i-Sharif', 'AF', 'MZR', 'airport_as_city', '[\"MZR\"]', '[\"マザーリシャリフ\"]'),
(610, 'Mazatlàn', 'MX', 'MZT', 'airport_as_city', '[\"MZT\"]', '[\"マサトラン\"]'),
(611, 'Mbombela', 'ZA', 'MQP', 'airport_as_city', '[\"MQP\"]', '[\"ムボンベラ\"]'),
(612, 'Medellín', 'CO', 'MDE', 'airport_as_city', '[\"MDE\"]', '[\"メデジン\"]'),
(613, 'Medina', 'SA', 'MED', 'airport_as_city', '[\"MED\"]', '[\"メディナ\"]'),
(614, 'Melbourne', 'AU', 'MEL', 'metropolitan', '[\"AVV\", \"MEL\"]', '[\"メルボルン\"]'),
(615, 'Mellita', 'TN', 'DJE', 'airport_as_city', '[\"DJE\"]', '[\"メリタ\"]'),
(616, 'Memmingen', 'DE', 'FMM', 'airport_as_city', '[\"FMM\"]', '[\"メミンゲン\"]'),
(617, 'Memphis', 'US', 'MEM', 'airport_as_city', '[\"MEM\"]', '[\"メンフィス\"]'),
(618, 'Mendoza', 'AR', 'MDZ', 'airport_as_city', '[\"MDZ\"]', '[\"メンドーサ\"]'),
(619, 'Mérida', 'MX', 'MID', 'airport_as_city', '[\"MID\"]', '[\"メリダ\"]'),
(620, 'Mexico City', 'MX', 'MEX', 'airport_as_city', '[\"MEX\"]', '[\"メキシコシティ\"]'),
(621, 'Mfuwe', 'ZM', 'MFU', 'airport_as_city', '[\"MFU\"]', '[\"ムフウェ\"]'),
(622, 'Miami', 'US', 'MIA', 'airport_as_city', '[\"MIA\"]', '[\"マイアミ\"]'),
(623, 'Milan', 'IT', 'MIL', 'metropolitan', '[\"BGY\", \"LIN\", \"MXP\"]', '[\"ミラノ\"]'),
(624, 'Milwaukee', 'US', 'MKE', 'airport_as_city', '[\"MKE\"]', '[\"ミルウォーキー\"]'),
(625, 'Mineralnyye Vody', 'RU', 'MRV', 'airport_as_city', '[\"MRV\"]', '[\"ミネラーリヌィエ・ヴォードィ\"]'),
(626, 'Minneapolis', 'US', 'MSP', 'airport_as_city', '[\"MSP\"]', '[\"ミネアポリス\"]'),
(627, 'Minsk', 'BY', 'MSQ', 'airport_as_city', '[\"MSQ\"]', '[\"ミンスク\"]'),
(628, 'Miyazaki', 'JP', 'KMI', 'airport_as_city', '[\"KMI\"]', '[\"宮崎\", \"みやざき\"]'),
(629, 'Mogadishu', 'SO', 'MGQ', 'airport_as_city', '[\"MGQ\"]', '[\"モガディシュ\"]'),
(630, 'Mombasa', 'KE', 'MBA', 'airport_as_city', '[\"MBA\"]', '[\"モンバサ\"]'),
(631, 'Monrovia', 'LR', 'ROB', 'airport_as_city', '[\"ROB\"]', '[\"モンロビア\"]'),
(632, 'Montego Bay', 'JM', 'MBJ', 'airport_as_city', '[\"MBJ\"]', '[\"モンテゴベイ\"]'),
(633, 'Monterrey', 'MX', 'MTY', 'airport_as_city', '[\"MTY\"]', '[\"モンテレー\"]'),
(634, 'Montpellier/Méditerranée', 'FR', 'MPL', 'airport_as_city', '[\"MPL\"]', '[\"モンペリエ\"]'),
(635, 'Montréal', 'CA', 'YUL', 'airport_as_city', '[\"YUL\"]', '[\"モントリオール\"]'),
(636, 'Mopa', 'IN', 'GOX', 'airport_as_city', '[\"GOX\"]', '[\"モパ\"]'),
(637, 'Morelia', 'MX', 'MLM', 'airport_as_city', '[\"MLM\"]', '[\"モレリア\"]'),
(638, 'Moroni', 'KM', 'HAH', 'airport_as_city', '[\"HAH\"]', '[\"モロナイ\"]'),
(639, 'Moscow', 'RU', 'MOW', 'metropolitan', '[\"DME\", \"SVO\", \"VKO\"]', '[\"モスクワ\"]'),
(640, 'Mošnov', 'CZ', 'OSR', 'airport_as_city', '[\"OSR\"]', '[\"オストラヴァ\",\"モシュノフ\"]'),
(641, 'Mostar', 'BA', 'OMO', 'airport_as_city', '[\"OMO\"]', '[\"モスタル\"]'),
(642, 'Mount Pleasant', 'FK', 'MPN', 'airport_as_city', '[\"MPN\"]', '[\"マウント・プレザント\"]'),
(643, 'Mpaka', 'SZ', 'SHO', 'airport_as_city', '[\"SHO\"]', '[\"ムパカ\"]'),
(644, 'Muan (Piseo-ri)', 'KR', 'MWX', 'airport_as_city', '[\"MWX\"]', '[\"務安\", \"무안\"]'),
(645, 'Mukalla(Riyan)', 'YE', 'RIY', 'airport_as_city', '[\"RIY\"]', '[\"ムカラ(リヤン)\"]'),
(646, 'Multan', 'PK', 'MUX', 'airport_as_city', '[\"MUX\"]', '[\"ムルタン\"]'),
(647, 'Mumbai', 'IN', 'BOM', 'airport_as_city', '[\"BOM\"]', '[\"ムンバイ\"]'),
(648, 'Munich', 'DE', 'MUC', 'airport_as_city', '[\"MUC\"]', '[\"ミュンヘン\"]'),
(649, 'Murmansk', 'RU', 'MMK', 'airport_as_city', '[\"MMK\"]', '[\"ムルマンスク\"]'),
(650, 'Muscat/Seeb', 'OM', 'MCT', 'airport_as_city', '[\"MCT\"]', '[\"マスカット/シーブ\"]'),
(651, 'Mwanza', 'TZ', 'MWZ', 'airport_as_city', '[\"MWZ\"]', '[\"ムワンザ\"]'),
(652, 'Myrtle Beach', 'US', 'MYR', 'airport_as_city', '[\"MYR\"]', '[\"マートルビーチ\"]'),
(653, 'N\'Djamena', 'TD', 'NDJ', 'airport_as_city', '[\"NDJ\"]', '[\"ンジャメナ\"]'),
(654, 'Na Thon (Ko Samui Island)', 'TH', 'USM', 'airport_as_city', '[\"USM\"]', '[\"ナトン（サムイ島）\"]'),
(655, 'Nadi', 'FJ', 'NAN', 'airport_as_city', '[\"NAN\"]', '[\"ナンディ\"]'),
(656, 'Nagasaki', 'JP', 'NGS', 'airport_as_city', '[\"NGS\"]', '[\"長崎\", \"ながさき\"]'),
(657, 'Nagoya', 'JP', 'NGO', 'metropolitan', '[\"NGO\", \"NKM\"]', '[\"名古屋\", \"なごや\"]'),
(658, 'Nagpur', 'IN', 'NAG', 'airport_as_city', '[\"NAG\"]', '[\"ナグプール\"]'),
(659, 'Naha', 'JP', 'OKA', 'airport_as_city', '[\"OKA\"]', '[\"那覇\", \"沖縄\", \"なは\"]'),
(660, 'Nairobi', 'KE', 'NBO', 'airport_as_city', '[\"NBO\"]', '[\"ナイロビ\"]'),
(661, 'Najaf', 'IQ', 'NJF', 'airport_as_city', '[\"NJF\"]', '[\"ナジャフ\"]'),
(662, 'Nakhchivan', 'AZ', 'NAJ', 'airport_as_city', '[\"NAJ\"]', '[\"ナヒチェヴァン\"]'),
(663, 'Namangan', 'UZ', 'NMA', 'airport_as_city', '[\"NMA\"]', '[\"ナマンガン\"]'),
(664, 'Nampula', 'MZ', 'APL', 'airport_as_city', '[\"APL\"]', '[\"ナンプラ\"]'),
(665, 'Nanchang', 'CN', 'KHN', 'airport_as_city', '[\"KHN\"]', '[\"南昌\"]'),
(666, 'Nanjing', 'CN', 'NKG', 'airport_as_city', '[\"NKG\"]', '[\"南京\"]'),
(667, 'Nankoku', 'JP', 'KCZ', 'airport_as_city', '[\"KCZ\"]', '[\"南国市\"]'),
(668, 'Nanning (Jiangnan)', 'CN', 'NNG', 'airport_as_city', '[\"NNG\"]', '[\"南寧\", \"南宁\"]'),
(669, 'Nantes', 'FR', 'NTE', 'airport_as_city', '[\"NTE\"]', '[\"ナント\"]'),
(670, 'Napoli', 'IT', 'NAP', 'airport_as_city', '[\"NAP\"]', '[\"ナポリ\"]'),
(671, 'Narita', 'JP', 'NRT', 'airport_as_city', '[\"NRT\"]', '[\"成田\"]'),
(672, 'Nashik', 'IN', 'ISK', 'airport_as_city', '[\"ISK\"]', '[\"ナシック\"]'),
(673, 'Nashville', 'US', 'BNA', 'airport_as_city', '[\"BNA\"]', '[\"ナッシュビル\"]'),
(674, 'Nassau', 'BS', 'NAS', 'airport_as_city', '[\"NAS\"]', '[\"ナッソー\"]'),
(675, 'Natal', 'BR', 'NAT', 'airport_as_city', '[\"NAT\"]', '[\"ナタール\"]'),
(676, 'Natori', 'JP', 'SDJ', 'airport_as_city', '[\"SDJ\"]', '[\"名取\"]'),
(677, 'Nausori', 'FJ', 'SUV', 'airport_as_city', '[\"SUV\"]', '[\"なうそり\"]'),
(678, 'Navegantes', 'BR', 'NVT', 'airport_as_city', '[\"NVT\"]', '[\"ナベガンテス\"]'),
(679, 'Navi Mumbai', 'IN', 'NMI', 'airport_as_city', '[\"NMI\"]', '[\"ナビ・ムンバイ\"]'),
(680, 'Naypyitaw', 'MM', 'NYT', 'airport_as_city', '[\"NYT\"]', '[\"ネピドー\"]'),
(681, 'Ndola', 'ZM', 'NLA', 'airport_as_city', '[\"NLA\"]', '[\"ンドラ\"]'),
(682, 'Neuquén', 'AR', 'NQN', 'airport_as_city', '[\"NQN\"]', '[\"ネウケン\"]'),
(683, 'Nevşehir', 'TR', 'NAV', 'airport_as_city', '[\"NAV\"]', '[\"カッパドキア\",\"ネヴシェヒル\"]'),
(684, 'New Delhi', 'IN', 'DEL', 'airport_as_city', '[\"DEL\"]', '[\"ニューデリー\"]'),
(685, 'New Orleans', 'US', 'MSY', 'airport_as_city', '[\"MSY\"]', '[\"ニューオーリンズ\"]'),
(686, 'New York', 'US', 'NYC', 'metropolitan', '[\"JFK\", \"LGA\"]', '[\"ニューヨーク\",\"ニューヨーク市\"]'),
(687, 'Newark', 'US', 'EWR', 'airport_as_city', '[\"EWR\"]', '[\"ニューアーク\"]'),
(688, 'Newcastle upon Tyne, Tyne and Wear', 'GB', 'NCL', 'airport_as_city', '[\"NCL\"]', '[\"ニューカッスル・アポン・タイン\",\"ニューカッスル\"]'),
(689, 'Nha Trang/nha Trang aiurportCam Ranh', 'VN', 'CXR', 'airport_as_city', '[\"CXR\"]', '[\"ニャチャン/ニャチャン空港カムラン\"]'),
(690, 'Niamey', 'NE', 'NIM', 'airport_as_city', '[\"NIM\"]', '[\"ニアメ\"]'),
(691, 'Nice, Alpes-Maritimes', 'FR', 'NCE', 'airport_as_city', '[\"NCE\"]', '[\"ニース\"]'),
(692, 'Niigata', 'JP', 'KIJ', 'airport_as_city', '[\"KIJ\"]', '[\"新潟\", \"にいがた\"]'),
(693, 'Ningbo', 'CN', 'NGB', 'airport_as_city', '[\"NGB\"]', '[\"寧波\", \"宁波\"]'),
(694, 'Niš', 'RS', 'INI', 'airport_as_city', '[\"INI\"]', '[\"ニシュ\"]'),
(695, 'Nizhnevartovsk', 'RU', 'NJC', 'airport_as_city', '[\"NJC\"]', '[\"ニジネヴァルトフスク\"]'),
(696, 'Nizhny Novgorod', 'RU', 'GOJ', 'airport_as_city', '[\"GOJ\"]', '[\"ニジニ・ノヴゴロド\"]'),
(697, 'Norfolk', 'US', 'ORF', 'airport_as_city', '[\"ORF\"]', '[\"ノーフォーク\"]'),
(698, 'Norilsk', 'RU', 'NSK', 'airport_as_city', '[\"NSK\"]', '[\"ノリリスク\"]'),
(699, 'Nossa Senhora do Carmo', 'MO', 'MFM', 'airport_as_city', '[\"MFM\"]', '[\"ノッサ セニョーラ ド カルモ\"]'),
(700, 'Nosy Be', 'MG', 'NOS', 'airport_as_city', '[\"NOS\"]', '[\"ノシベ\"]'),
(701, 'Nottingham, Leicestershire', 'GB', 'EMA', 'airport_as_city', '[\"EMA\"]', '[\"イースト・ミッドランズ\",\"ノッティンガム\"]'),
(702, 'Nouadhibou', 'MR', 'NDB', 'airport_as_city', '[\"NDB\"]', '[\"ヌアジブ\"]'),
(703, 'Nouakchott', 'MR', 'NKC', 'airport_as_city', '[\"NKC\"]', '[\"ヌアクショット\"]');
INSERT INTO `iata_cities` (`id`, `city`, `country`, `iata`, `code_type`, `airports`, `aliases`) VALUES
(704, 'Nouméa (La Tontouta)', 'NC', 'NOU', 'airport_as_city', '[\"NOU\"]', '[\"ヌメア (ラ トントゥータ)\"]'),
(705, 'Novosibirsk', 'RU', 'OVB', 'airport_as_city', '[\"OVB\"]', '[\"ノヴォシビルスク\"]'),
(706, 'Nowy Dwór Mazowiecki', 'PL', 'WMI', 'airport_as_city', '[\"WMI\"]', '[\"ワルシャワ\",\"モドリン\",\"ノヴィ・ドヴル・マゾヴィエツキ\"]'),
(707, 'Nuku\'alofa', 'TO', 'TBU', 'airport_as_city', '[\"TBU\"]', '[\"ヌクアロファ\"]'),
(708, 'Nukus', 'UZ', 'NCU', 'airport_as_city', '[\"NCU\"]', '[\"ヌクス\"]'),
(709, 'Nuremberg', 'DE', 'NUE', 'airport_as_city', '[\"NUE\"]', '[\"ニュルンベルク\"]'),
(710, 'Nuuk', 'GL', 'GOH', 'airport_as_city', '[\"GOH\"]', '[\"ヌーク\"]'),
(711, 'Nyköping', 'SE', 'NYO', 'airport_as_city', '[\"NYO\"]', '[\"ストックホルム\",\"スカブスタ\",\"ニュヒェーピング\"]'),
(712, 'Oakland', 'US', 'OAK', 'airport_as_city', '[\"OAK\"]', '[\"オークランド\"]'),
(713, 'Oaxaca', 'MX', 'OAX', 'airport_as_city', '[\"OAX\"]', '[\"オアハカ\"]'),
(714, 'Odense', 'DK', 'ODE', 'airport_as_city', '[\"ODE\"]', '[\"オーデンセ\"]'),
(715, 'Łódź', 'PL', 'LCJ', 'airport_as_city', '[\"LCJ\"]', '[\"ウッチ\"]'),
(716, 'Oecussi-Ambeno', 'TL', 'OEC', 'airport_as_city', '[\"OEC\"]', '[\"オエクッシ・アンベノ\"]'),
(717, 'Ohrid', 'MK', 'OHD', 'airport_as_city', '[\"OHD\"]', '[\"オフリド\"]'),
(718, 'Okat', 'FM', 'KSA', 'airport_as_city', '[\"KSA\"]', '[\"オカット\"]'),
(719, 'Okayama', 'JP', 'OKJ', 'airport_as_city', '[\"OKJ\"]', '[\"岡山\", \"おかやま\"]'),
(720, 'Oklahoma City', 'US', 'OKC', 'airport_as_city', '[\"OKC\"]', '[\"オクラホマシティ\"]'),
(721, 'Olbia (SS)', 'IT', 'OLB', 'airport_as_city', '[\"OLB\"]', '[\"オルビア\"]'),
(722, 'Olongapo', 'PH', 'SFS', 'airport_as_city', '[\"SFS\"]', '[\"オロンガポ\"]'),
(723, 'Omaha', 'US', 'OMA', 'airport_as_city', '[\"OMA\"]', '[\"オマハ\"]'),
(724, 'Omitama', 'JP', 'IBR', 'airport_as_city', '[\"IBR\"]', '[\"小美玉市\"]'),
(725, 'Omsk', 'RU', 'OMS', 'airport_as_city', '[\"OMS\"]', '[\"オムスク\"]'),
(726, 'Ontario', 'US', 'ONT', 'airport_as_city', '[\"ONT\"]', '[\"オンタリオ\"]'),
(727, 'Oostende', 'BE', 'OST', 'airport_as_city', '[\"OST\"]', '[\"オーステンデ\"]'),
(728, 'Oradea', 'RO', 'OMR', 'airport_as_city', '[\"OMR\"]', '[\"オラデア\"]'),
(729, 'Oranjestad', 'AW', 'AUA', 'airport_as_city', '[\"AUA\"]', '[\"オラニエスタッド\"]'),
(730, 'Ordos', 'CN', 'DSN', 'airport_as_city', '[\"DSN\"]', '[\"鄂爾多斯\", \"鄂尔多斯\"]'),
(731, 'Orio al Serio (BG)', 'IT', 'BGY', 'airport_as_city', '[\"BGY\"]', '[\"ミラノ\",\"ベルガモ\",\"オーリオ・アル・セーリオ\"]'),
(732, 'Orlando', 'US', 'MCO', 'airport_as_city', '[\"MCO\"]', '[\"オーランド\"]'),
(733, 'Oruro', 'BO', 'ORU', 'airport_as_city', '[\"ORU\"]', '[\"オルロ\"]'),
(734, 'Osaka', 'JP', 'OSA', 'metropolitan', '[\"ITM\", \"KIX\", \"UKB\"]', '[\"大阪\", \"おおさか\"]'),
(735, 'Osbourn', 'AG', 'ANU', 'airport_as_city', '[\"ANU\"]', '[\"オズボーン\"]'),
(736, 'Osh', 'KG', 'OSS', 'airport_as_city', '[\"OSS\"]', '[\"オシ\"]'),
(737, 'Oslo', 'NO', 'OSL', 'metropolitan', '[\"OSL\", \"TRF\"]', '[\"オスロ\"]'),
(738, 'Oslo (Gardermoen)', 'NO', 'OSL', 'airport_as_city', '[\"OSL\"]', '[\"オスロ\",\"ガーデモエン\"]'),
(739, 'Otopeni', 'RO', 'OTP', 'airport_as_city', '[\"OTP\"]', '[\"ブカレスト\",\"オトペニ\"]'),
(740, 'Ottawa', 'CA', 'YOW', 'airport_as_city', '[\"YOW\"]', '[\"オタワ\"]'),
(741, 'Ouagadougou', 'BF', 'OUA', 'airport_as_city', '[\"OUA\"]', '[\"ワガドゥグー\"]'),
(742, 'Ouarzazate', 'MA', 'OZZ', 'airport_as_city', '[\"OZZ\"]', '[\"ワルザザート\"]'),
(743, 'Oulad Yaich', 'MA', 'BEM', 'airport_as_city', '[\"BEM\"]', '[\"ウーラド・ヤイチ\"]'),
(744, 'Oulu / Oulunsalo', 'FI', 'OUL', 'airport_as_city', '[\"OUL\"]', '[\"オウル\"]'),
(745, 'Padang (Katapiang)', 'ID', 'PDG', 'airport_as_city', '[\"PDG\"]', '[\"パダン（カタピアン）\"]'),
(746, 'Pago Pago', 'AS', 'PPG', 'airport_as_city', '[\"PPG\"]', '[\"パゴパゴ\"]'),
(747, 'Pakse', 'LA', 'PKZ', 'airport_as_city', '[\"PKZ\"]', '[\"パクセー\"]'),
(748, 'Palanga', 'LT', 'PLQ', 'airport_as_city', '[\"PLQ\"]', '[\"パランガ\"]'),
(749, 'Palermo', 'IT', 'PMO', 'airport_as_city', '[\"PMO\"]', '[\"パレルモ\"]'),
(750, 'Palm Springs', 'US', 'PSP', 'airport_as_city', '[\"PSP\"]', '[\"パームスプリングス\"]'),
(751, 'Palma de Mallorca', 'ES', 'PMI', 'airport_as_city', '[\"PMI\"]', '[\"パルマ・デ・マヨルカ\",\"マヨルカ島\"]'),
(752, 'Palmerola', 'HN', 'XPL', 'airport_as_city', '[\"XPL\"]', '[\"パルメローラ\"]'),
(753, 'Panglao', 'PH', 'TAG', 'airport_as_city', '[\"TAG\"]', '[\"パングラオ\"]'),
(754, 'Papeete', 'PF', 'PPT', 'airport_as_city', '[\"PPT\"]', '[\"パペーテ\"]'),
(755, 'Paphos', 'CY', 'PFO', 'airport_as_city', '[\"PFO\"]', '[\"パフォス\"]'),
(756, 'Paramaribo', 'SR', 'PBM', 'airport_as_city', '[\"PBM\"]', '[\"パラマリボ\"]'),
(757, 'Pardubice', 'CZ', 'PED', 'airport_as_city', '[\"PED\"]', '[\"パルドゥビツェ\"]'),
(758, 'Paris', 'FR', 'PAR', 'metropolitan', '[\"CDG\", \"ORY\"]', '[\"パリ\"]'),
(759, 'Paris (Orly, Val-de-Marne)', 'FR', 'ORY', 'airport_as_city', '[\"ORY\"]', '[\"パリ\",\"オルリー\"]'),
(760, 'Paris (Roissy-en-France, Val-d\'Oise)', 'FR', 'CDG', 'airport_as_city', '[\"CDG\"]', '[\"パリ\",\"シャルル・ド・ゴール\",\"ロワシー\"]'),
(761, 'Paro', 'BT', 'PBH', 'airport_as_city', '[\"PBH\"]', '[\"パロ\"]'),
(762, 'Pavlodar', 'KZ', 'PWQ', 'airport_as_city', '[\"PWQ\"]', '[\"パヴロダル\"]'),
(763, 'Pécs', 'HU', 'PEV', 'airport_as_city', '[\"PEV\"]', '[\"ペーチ\"]'),
(764, 'Penang', 'MY', 'PEN', 'airport_as_city', '[\"PEN\"]', '[\"ペナン\"]'),
(765, 'Pendik, Istanbul', 'TR', 'SAW', 'airport_as_city', '[\"SAW\"]', '[\"イスタンブール\",\"サビハ・ギョクチェン\",\"ペンディク\"]'),
(766, 'Pensacola', 'US', 'PNS', 'airport_as_city', '[\"PNS\"]', '[\"ペンサコーラ\"]'),
(767, 'Perm', 'RU', 'PEE', 'airport_as_city', '[\"PEE\"]', '[\"ペルミ\"]'),
(768, 'Perth', 'AU', 'PER', 'airport_as_city', '[\"PER\"]', '[\"パース\"]'),
(769, 'Perugia (PG)', 'IT', 'PEG', 'airport_as_city', '[\"PEG\"]', '[\"ペルージャ\"]'),
(770, 'Pescara', 'IT', 'PSR', 'airport_as_city', '[\"PSR\"]', '[\"ペスカーラ\"]'),
(771, 'Peshawar', 'PK', 'PEW', 'airport_as_city', '[\"PEW\"]', '[\"ペシャワール\"]'),
(772, 'Petropavl', 'KZ', 'PPK', 'airport_as_city', '[\"PPK\"]', '[\"ペトロパブル\"]'),
(773, 'Petropavlovsk-Kamchatsky', 'RU', 'PKC', 'airport_as_city', '[\"PKC\"]', '[\"ペトロパブロフスク・カムチャツキー\"]'),
(774, 'Philadelphia', 'US', 'PHL', 'airport_as_city', '[\"PHL\"]', '[\"フィラデルフィア\"]'),
(775, 'Phnom Penh (Boeng Khyang)', 'KH', 'KTI', 'airport_as_city', '[\"KTI\"]', '[\"プノンペン（ボンキヤン）\"]'),
(776, 'Phoenix', 'US', 'PHX', 'airport_as_city', '[\"PHX\"]', '[\"フェニックス\"]'),
(777, 'Phu Quoc Island', 'VN', 'PQC', 'airport_as_city', '[\"PQC\"]', '[\"フーコック島\"]'),
(778, 'Phuket', 'TH', 'HKT', 'airport_as_city', '[\"HKT\"]', '[\"プーケット\"]'),
(779, 'Pinellas Park', 'US', 'PIE', 'airport_as_city', '[\"PIE\"]', '[\"ピネラスパーク\"]'),
(780, 'Pisa (PI)', 'IT', 'PSA', 'airport_as_city', '[\"PSA\"]', '[\"ピサ\"]'),
(781, 'Pittsburgh', 'US', 'PIT', 'airport_as_city', '[\"PIT\"]', '[\"ピッツバーグ\"]'),
(782, 'Plaine Magnien', 'MU', 'MRU', 'airport_as_city', '[\"MRU\"]', '[\"プレーン・マニアン\"]'),
(783, 'Plovdiv', 'BG', 'PDV', 'airport_as_city', '[\"PDV\"]', '[\"プロヴディフ\"]'),
(784, 'Podgorica', 'ME', 'TGD', 'airport_as_city', '[\"TGD\"]', '[\"ポドゴリツァ\"]'),
(785, 'Pointe-à-Pitre', 'GP', 'PTP', 'airport_as_city', '[\"PTP\"]', '[\"ポワンタピートル\"]'),
(786, 'Pointe Noire', 'CG', 'PNR', 'airport_as_city', '[\"PNR\"]', '[\"ポワント ノワール\"]'),
(787, 'Pokhara', 'NP', 'PHH', 'airport_as_city', '[\"PHH\"]', '[\"ポカラ\"]'),
(788, 'Polokwane', 'ZA', 'PTG', 'airport_as_city', '[\"PTG\"]', '[\"ポロクワネ\"]'),
(789, 'Ponta Delgada', 'PT', 'PDL', 'airport_as_city', '[\"PDL\"]', '[\"ポンタ・デルガダ\"]'),
(790, 'Pontianak', 'ID', 'PNK', 'airport_as_city', '[\"PNK\"]', '[\"ポンティアナック\"]'),
(791, 'Port-au-Prince', 'HT', 'PAP', 'airport_as_city', '[\"PAP\"]', '[\"ポルトープランス\"]'),
(792, 'Port Blair', 'IN', 'IXZ', 'airport_as_city', '[\"IXZ\"]', '[\"ポート ブレア\"]'),
(793, 'Port Gentil', 'GA', 'POG', 'airport_as_city', '[\"POG\"]', '[\"ポール・ジャンティ\"]'),
(794, 'Port Harcourt', 'NG', 'PHC', 'airport_as_city', '[\"PHC\"]', '[\"ポートハーコート\"]'),
(795, 'Port Hedland', 'AU', 'PHE', 'airport_as_city', '[\"PHE\"]', '[\"ポートヘッドランド\"]'),
(796, 'Port Moresby', 'PG', 'POM', 'airport_as_city', '[\"POM\"]', '[\"ポートモレスビー\"]'),
(797, 'Port of Spain', 'TT', 'POS', 'airport_as_city', '[\"POS\"]', '[\"ポート オブ スペイン\"]'),
(798, 'Port Said', 'EG', 'PSD', 'airport_as_city', '[\"PSD\"]', '[\"ポートサイド\"]'),
(799, 'Port Sudan', 'SD', 'PZU', 'airport_as_city', '[\"PZU\"]', '[\"ポートスーダン\"]'),
(800, 'Port Vila', 'VU', 'VLI', 'airport_as_city', '[\"VLI\"]', '[\"ポートビラ\"]'),
(801, 'Portland', 'US', 'PDX', 'airport_as_city', '[\"PDX\"]', '[\"ポートランド\"]'),
(802, 'Porto', 'PT', 'OPO', 'airport_as_city', '[\"OPO\"]', '[\"ポルト\"]'),
(803, 'Porto Alegre', 'BR', 'POA', 'airport_as_city', '[\"POA\"]', '[\"ポルトアレグレ\"]'),
(804, 'Porto Seguro', 'BR', 'BPS', 'airport_as_city', '[\"BPS\"]', '[\"ポルト・セグーロ\"]'),
(805, 'Porto Velho', 'BR', 'PVH', 'airport_as_city', '[\"PVH\"]', '[\"ポルト ヴェーリョ\"]'),
(806, 'Poznań', 'PL', 'POZ', 'airport_as_city', '[\"POZ\"]', '[\"ポズナン\"]'),
(807, 'Prague', 'CZ', 'PRG', 'airport_as_city', '[\"PRG\"]', '[\"プラハ\"]'),
(808, 'Praia', 'CV', 'RAI', 'airport_as_city', '[\"RAI\"]', '[\"プライア\"]'),
(809, 'Preah Sihanouk', 'KH', 'KOS', 'airport_as_city', '[\"KOS\"]', '[\"プレア・シアヌーク\"]'),
(810, 'Prestwick, South Ayrshire', 'GB', 'PIK', 'airport_as_city', '[\"PIK\"]', '[\"グラスゴー\",\"プレストウィック\"]'),
(811, 'Prishtina', 'XK', 'PRN', 'airport_as_city', '[\"PRN\"]', '[\"プリシュティナ\"]'),
(812, 'Providence/Warwick', 'US', 'PVD', 'airport_as_city', '[\"PVD\"]', '[\"プロビデンス\",\"ウォリック\"]'),
(813, 'Providenciales', 'TC', 'PLS', 'airport_as_city', '[\"PLS\"]', '[\"プロビデンシアレス\"]'),
(814, 'Pucallpa', 'PE', 'PCL', 'airport_as_city', '[\"PCL\"]', '[\"プカルパ\"]'),
(815, 'Puebla', 'MX', 'PBC', 'airport_as_city', '[\"PBC\"]', '[\"プエブラ\"]'),
(816, 'Puerto Montt', 'CL', 'PMC', 'airport_as_city', '[\"PMC\"]', '[\"プエルトモント\"]'),
(817, 'Puerto Princesa', 'PH', 'PPS', 'airport_as_city', '[\"PPS\"]', '[\"プエルト プリンセサ\"]'),
(818, 'Puerto Vallarta', 'MX', 'PVR', 'airport_as_city', '[\"PVR\"]', '[\"プエルトバリャルタ\"]'),
(819, 'Pula', 'HR', 'PUY', 'airport_as_city', '[\"PUY\"]', '[\"プーラ\"]'),
(820, 'Pune', 'IN', 'PNQ', 'airport_as_city', '[\"PNQ\"]', '[\"プネ\"]'),
(821, 'Punta Arenas', 'CL', 'PUQ', 'airport_as_city', '[\"PUQ\"]', '[\"プンタ アレナス\"]'),
(822, 'Punta Cana', 'DO', 'PUJ', 'airport_as_city', '[\"PUJ\"]', '[\"プンタ カナ\"]'),
(823, 'Pyongyang', 'KP', 'FNJ', 'airport_as_city', '[\"FNJ\"]', '[\"平壌\"]'),
(824, 'Qaisumah', 'SA', 'AQI', 'airport_as_city', '[\"AQI\"]', '[\"カイスマ\"]'),
(825, 'Qassim', 'SA', 'ELQ', 'airport_as_city', '[\"ELQ\"]', '[\"カシム\"]'),
(826, 'Qeshm(Dayrestan)', 'IR', 'GSM', 'airport_as_city', '[\"GSM\"]', '[\"ケシュム(デイレスターン州)\"]'),
(827, 'Qingdao (Jiaozhou)', 'CN', 'TAO', 'airport_as_city', '[\"TAO\"]', '[\"青島\", \"青岛\"]'),
(828, 'Qiqihar', 'CN', 'NDG', 'airport_as_city', '[\"NDG\"]', '[\"齊齊哈爾\", \"齐齐哈尔\"]'),
(829, 'Quanzhou', 'CN', 'JJN', 'airport_as_city', '[\"JJN\"]', '[\"泉州\"]'),
(830, 'Quebec', 'CA', 'YQB', 'airport_as_city', '[\"YQB\"]', '[\"ケベック州\"]'),
(831, 'Queenstown', 'NZ', 'ZQN', 'airport_as_city', '[\"ZQN\"]', '[\"クイーンズタウン\"]'),
(832, 'Querétaro', 'MX', 'QRO', 'airport_as_city', '[\"QRO\"]', '[\"ケレタロ\"]'),
(833, 'Quetta', 'PK', 'UET', 'airport_as_city', '[\"UET\"]', '[\"クエッタ\"]'),
(834, 'Quijarro', 'BO', 'UYU', 'airport_as_city', '[\"UYU\"]', '[\"キハロ\"]'),
(835, 'Quito', 'EC', 'UIO', 'airport_as_city', '[\"UIO\"]', '[\"キト\"]'),
(836, 'Rabat', 'MA', 'RBA', 'airport_as_city', '[\"RBA\"]', '[\"ラバト\"]'),
(837, 'Rabil', 'CV', 'BVC', 'airport_as_city', '[\"BVC\"]', '[\"ラビル\"]'),
(838, 'Rajkot', 'IN', 'HSR', 'airport_as_city', '[\"HSR\"]', '[\"ラージコット\"]'),
(839, 'Raleigh/Durham', 'US', 'RDU', 'airport_as_city', '[\"RDU\"]', '[\"ローリー\",\"ダーラム\"]'),
(840, 'Ranón', 'ES', 'OVD', 'airport_as_city', '[\"OVD\"]', '[\"アストゥリアス\",\"ラノン\"]'),
(841, 'Ras Al Khaimah', 'AE', 'RKT', 'airport_as_city', '[\"RKT\"]', '[\"ラス アル ハイマ\"]'),
(842, 'Rayong', 'TH', 'UTP', 'airport_as_city', '[\"UTP\"]', '[\"ラヨーン\"]'),
(843, 'Recife', 'BR', 'REC', 'airport_as_city', '[\"REC\"]', '[\"レシフェ\"]'),
(844, 'Reno', 'US', 'RNO', 'airport_as_city', '[\"RNO\"]', '[\"リノ\"]'),
(845, 'Resistencia', 'AR', 'RES', 'airport_as_city', '[\"RES\"]', '[\"レシステンシア\"]'),
(846, 'Reus', 'ES', 'REU', 'airport_as_city', '[\"REU\"]', '[\"レウス\"]'),
(847, 'Reykjavik', 'IS', 'REK', 'metropolitan', '[\"KEF\", \"RKV\"]', '[\"Reykjavík\",\"レイキャヴィーク\",\"レイキャビク\"]'),
(848, 'Rheinmünster', 'DE', 'FKB', 'airport_as_city', '[\"FKB\"]', '[\"カールスルーエ\",\"バーデン＝バーデン\",\"ラインミュンスター\"]'),
(849, 'Rhodes', 'GR', 'RHO', 'airport_as_city', '[\"RHO\"]', '[\"ロードス島\"]'),
(850, 'Richmond', 'US', 'RIC', 'airport_as_city', '[\"RIC\"]', '[\"リッチモンド\"]'),
(851, 'Riga', 'LV', 'RIX', 'airport_as_city', '[\"RIX\"]', '[\"リガ\"]'),
(852, 'Rijeka(Omišalj)', 'HR', 'RJK', 'airport_as_city', '[\"RJK\"]', '[\"リエカ\",\"オミシャリ\"]'),
(853, 'Rimini (RN)', 'IT', 'RMI', 'airport_as_city', '[\"RMI\"]', '[\"リミニ\"]'),
(854, 'Rinas', 'AL', 'TIA', 'airport_as_city', '[\"TIA\"]', '[\"ティラナ\",\"リナス\"]'),
(855, 'Rio Branco', 'BR', 'RBR', 'airport_as_city', '[\"RBR\"]', '[\"リオ ブランコ\"]'),
(856, 'Rio de Janeiro', 'BR', 'RIO', 'metropolitan', '[\"GIG\", \"SDU\"]', '[\"Rio De Janeiro\",\"リオデジャネイロ\"]'),
(857, 'Rio Gallegos', 'AR', 'RGL', 'airport_as_city', '[\"RGL\"]', '[\"リオ・ガジェゴス\"]'),
(858, 'Riyadh', 'SA', 'RUH', 'airport_as_city', '[\"RUH\"]', '[\"リヤド\"]'),
(859, 'Rize', 'TR', 'RZV', 'airport_as_city', '[\"RZV\"]', '[\"リゼ\"]'),
(860, 'Rochester', 'US', 'ROC', 'airport_as_city', '[\"ROC\"]', '[\"ロチェスター\"]'),
(861, 'Rome', 'IT', 'ROM', 'metropolitan', '[\"CIA\", \"FCO\"]', '[\"ローマ\"]'),
(862, 'Ronchi dei Legionari/Trieste', 'IT', 'TRS', 'airport_as_city', '[\"TRS\"]', '[\"トリエステ\",\"ロンキ・デイ・レジョナーリ\"]'),
(863, 'Rosario', 'AR', 'ROS', 'airport_as_city', '[\"ROS\"]', '[\"ロザリオ\"]'),
(864, 'Rostov-on-Don', 'RU', 'ROV', 'airport_as_city', '[\"ROV\"]', '[\"ロストフ・ナ・ドヌ\"]'),
(865, 'Rota Island', 'MP', 'ROP', 'airport_as_city', '[\"ROP\"]', '[\"ロタ島\"]'),
(866, 'Rotterdam', 'NL', 'RTM', 'airport_as_city', '[\"RTM\"]', '[\"ロッテルダム\"]'),
(867, 'Rovaniemi', 'FI', 'RVN', 'airport_as_city', '[\"RVN\"]', '[\"ロヴァニエミ\"]'),
(868, 'Sacramento', 'US', 'SMF', 'airport_as_city', '[\"SMF\"]', '[\"サクラメント\"]'),
(869, 'Saga', 'JP', 'HSG', 'airport_as_city', '[\"HSG\"]', '[\"佐賀\", \"さが\"]'),
(870, 'Saint George\'s', 'GD', 'GND', 'airport_as_city', '[\"GND\"]', '[\"セントジョージズ\"]'),
(871, 'Saint-Pierre', 'RE', 'ZSE', 'airport_as_city', '[\"ZSE\"]', '[\"サンピエール\"]'),
(872, 'Sainte-Marie', 'RE', 'RUN', 'airport_as_city', '[\"RUN\"]', '[\"サントマリー\"]'),
(873, 'Saïss', 'MA', 'FEZ', 'airport_as_city', '[\"FEZ\"]', '[\"サイス\"]'),
(874, 'Salalah', 'OM', 'SLL', 'airport_as_city', '[\"SLL\"]', '[\"サラーラ\"]'),
(875, 'Salinas/La Libertad', 'EC', 'SNC', 'airport_as_city', '[\"SNC\"]', '[\"サリナス/ラ・リベルタード\"]'),
(876, 'Salt Lake City', 'US', 'SLC', 'airport_as_city', '[\"SLC\"]', '[\"ソルトレイクシティ\",\"ソルトレイク\"]'),
(877, 'Salta', 'AR', 'SLA', 'airport_as_city', '[\"SLA\"]', '[\"サルタ\"]'),
(878, 'Salvador', 'BR', 'SSA', 'airport_as_city', '[\"SSA\"]', '[\"サルバドール\"]'),
(879, 'Salzburg', 'AT', 'SZG', 'airport_as_city', '[\"SZG\"]', '[\"ザルツブルク\"]'),
(880, 'Samara', 'RU', 'KUF', 'airport_as_city', '[\"KUF\"]', '[\"サマーラ\"]'),
(881, 'Samarkand', 'UZ', 'SKD', 'airport_as_city', '[\"SKD\"]', '[\"サマルカンド\"]'),
(882, 'San Andrés', 'CO', 'ADZ', 'airport_as_city', '[\"ADZ\"]', '[\"サンアンドレス\"]'),
(883, 'San Antonio', 'US', 'SAT', 'airport_as_city', '[\"SAT\"]', '[\"サンアントニオ\"]'),
(884, 'San Bartolomé', 'ES', 'ACE', 'airport_as_city', '[\"ACE\"]', '[\"ランサローテ島\",\"サン・バルトロメ\"]'),
(885, 'San Bernardino', 'US', 'SBD', 'airport_as_city', '[\"SBD\"]', '[\"サンバーナーディーノ\"]'),
(886, 'San Carlos de Bariloche', 'AR', 'BRC', 'airport_as_city', '[\"BRC\"]', '[\"サン カルロス デ バリローチェ\"]'),
(887, 'San Diego', 'US', 'SAN', 'airport_as_city', '[\"SAN\"]', '[\"サンディエゴ\"]'),
(888, 'San Francisco', 'US', 'SFO', 'airport_as_city', '[\"SFO\"]', '[\"サンフランシスコ\"]'),
(889, 'San Jose', 'US', 'SJC', 'airport_as_city', '[\"SJC\"]', '[\"サンノゼ\"]'),
(890, 'San José (Alajuela)', 'CR', 'SJO', 'airport_as_city', '[\"SJO\"]', '[\"サンホセ (アラフエラ)\"]'),
(891, 'San José del Cabo', 'MX', 'SJD', 'airport_as_city', '[\"SJD\"]', '[\"サン ホセ デル カボ\"]'),
(892, 'San Juan', 'PR', 'SJU', 'airport_as_city', '[\"SJU\"]', '[\"サンフアン\"]'),
(893, 'San Miguel de Tucumán', 'AR', 'TUC', 'airport_as_city', '[\"TUC\"]', '[\"サン ミゲル デ トゥクマン\"]'),
(894, 'San Pedro Sula', 'HN', 'SAP', 'airport_as_city', '[\"SAP\"]', '[\"サン ペドロ スーラ\"]'),
(895, 'San Salvador', 'BS', 'ZSA', 'airport_as_city', '[\"ZSA\"]', '[\"サンサルバドル\"]'),
(896, 'San Salvador de Jujuy', 'AR', 'JUJ', 'airport_as_city', '[\"JUJ\"]', '[\"サン サルバドル デ フフイ\"]'),
(897, 'San Salvador (San Luis Talpa)', 'SV', 'SAL', 'airport_as_city', '[\"SAL\"]', '[\"サン サルバドル (サン ルイス タルパ)\"]'),
(898, 'Sanaa', 'YE', 'SAH', 'airport_as_city', '[\"SAH\"]', '[\"サナア\"]'),
(899, 'Sandefjord(Torp)', 'NO', 'TRF', 'airport_as_city', '[\"TRF\"]', '[\"オスロ\",\"サンデフィヨルド\",\"トルプ\"]'),
(900, 'Şanlıurfa', 'TR', 'GNY', 'airport_as_city', '[\"GNY\"]', '[\"シャンルウルファ\"]'),
(901, 'Santa Ana', 'US', 'SNA', 'airport_as_city', '[\"SNA\"]', '[\"サンタアナ\"]'),
(902, 'Santa Clara', 'CU', 'SNU', 'airport_as_city', '[\"SNU\"]', '[\"サンタクララ\"]'),
(903, 'Santa Cruz', 'BO', 'VVI', 'airport_as_city', '[\"VVI\"]', '[\"サンタクルーズ\"]'),
(904, 'Santiago', 'CL', 'SCL', 'airport_as_city', '[\"SCL\"]', '[\"サンティアゴ\"]'),
(905, 'Santiago', 'CU', 'SCU', 'airport_as_city', '[\"SCU\"]', '[\"サンティアゴ\"]'),
(906, 'Santiago', 'DO', 'STI', 'airport_as_city', '[\"STI\"]', '[\"サンティアゴ\"]'),
(907, 'Santiago de Compostela', 'ES', 'SCQ', 'airport_as_city', '[\"SCQ\"]', '[\"サンティアゴ・デ・コンポステーラ\"]'),
(908, 'Santo Domingo', 'DO', 'SDQ', 'airport_as_city', '[\"SDQ\"]', '[\"サントドミンゴ\"]'),
(909, 'Santorini Island', 'GR', 'JTR', 'airport_as_city', '[\"JTR\"]', '[\"サントリーニ島\"]'),
(910, 'Sanya (Tianya)', 'CN', 'SYX', 'airport_as_city', '[\"SYX\"]', '[\"三亜\", \"三亞\", \"三亚\"]'),
(911, 'São Luís', 'BR', 'SLZ', 'airport_as_city', '[\"SLZ\"]', '[\"サンルイス\"]'),
(912, 'Sao Paulo', 'BR', 'SAO', 'metropolitan', '[\"CGH\", \"GRU\", \"VCP\"]', '[\"São Paulo\",\"サンパウロ\"]'),
(913, 'São Pedro', 'CV', 'VXE', 'airport_as_city', '[\"VXE\"]', '[\"サン ペドロ\"]'),
(914, 'São Tomé', 'ST', 'TMS', 'airport_as_city', '[\"TMS\"]', '[\"サントメ\"]'),
(915, 'Sapporo', 'JP', 'SPK', 'metropolitan', '[\"CTS\", \"OKD\"]', '[\"札幌\", \"さっぽろ\"]'),
(916, 'Sarajevo', 'BA', 'SJJ', 'airport_as_city', '[\"SJJ\"]', '[\"サラエヴォ\"]'),
(917, 'Saransk', 'RU', 'SKX', 'airport_as_city', '[\"SKX\"]', '[\"サランスク\"]'),
(918, 'Sarasota/Bradenton', 'US', 'SRQ', 'airport_as_city', '[\"SRQ\"]', '[\"サラソータ\",\"ブレーデントン\"]'),
(919, 'Saratov', 'RU', 'GSV', 'airport_as_city', '[\"GSV\"]', '[\"サラトフ\"]'),
(920, 'Saskatoon', 'CA', 'YXE', 'airport_as_city', '[\"YXE\"]', '[\"サスカトゥーン\"]'),
(921, 'Savannah', 'US', 'SAV', 'airport_as_city', '[\"SAV\"]', '[\"サバンナ\"]'),
(922, 'Scarborough', 'TT', 'TAB', 'airport_as_city', '[\"TAB\"]', '[\"スカボロー\"]'),
(923, 'Schkeuditz', 'DE', 'LEJ', 'airport_as_city', '[\"LEJ\"]', '[\"ライプツィヒ\",\"シュクロイディッツ\"]'),
(924, 'Seattle', 'US', 'SEA', 'airport_as_city', '[\"SEA\"]', '[\"シアトル\"]'),
(925, 'Segrate (MI)', 'IT', 'LIN', 'airport_as_city', '[\"LIN\"]', '[\"ミラノ\",\"リナーテ\",\"セグラーテ\"]'),
(926, 'Seiyun', 'YE', 'GXF', 'airport_as_city', '[\"GXF\"]', '[\"セイユン\"]'),
(927, 'Semarang', 'ID', 'SRG', 'airport_as_city', '[\"SRG\"]', '[\"スマラン\"]'),
(928, 'Semey', 'KZ', 'PLX', 'airport_as_city', '[\"PLX\"]', '[\"セメイ\"]'),
(929, 'Sentani', 'ID', 'DJJ', 'airport_as_city', '[\"DJJ\"]', '[\"センタニ\"]'),
(930, 'Seoul', 'KR', 'SEL', 'metropolitan', '[\"GMP\", \"ICN\"]', '[\"ソウル\", \"서울\", \"首爾\", \"首尔\"]'),
(931, 'Sepang', 'MY', 'KUL', 'airport_as_city', '[\"KUL\"]', '[\"セパン\"]'),
(932, 'Seville', 'ES', 'SVQ', 'airport_as_city', '[\"SVQ\"]', '[\"セビリア\"]'),
(933, 'Shanghai', 'CN', 'SHA', 'metropolitan', '[\"PVG\", \"SHA\"]', '[\"上海\", \"シャンハイ\"]'),
(934, 'Shanghai (Minhang)', 'CN', 'SHA', 'airport_as_city', '[\"SHA\"]', '[\"上海\", \"虹橋\", \"虹桥\"]'),
(935, 'Shanghai (Pudong)', 'CN', 'PVG', 'airport_as_city', '[\"PVG\"]', '[\"上海\", \"浦東\", \"浦东\"]'),
(936, 'Shannan (Gonggar)', 'CN', 'LXA', 'airport_as_city', '[\"LXA\"]', '[\"山南\", \"拉薩\", \"拉萨\"]'),
(937, 'Shannon', 'IE', 'SNN', 'airport_as_city', '[\"SNN\"]', '[\"シャノン\"]'),
(938, 'Sharjah', 'AE', 'SHJ', 'airport_as_city', '[\"SHJ\"]', '[\"シャルジャ\"]'),
(939, 'Sharm El Sheikh', 'EG', 'SSH', 'airport_as_city', '[\"SSH\"]', '[\"シャルム エル シェイク\"]'),
(940, 'Sharma', 'SA', 'NUM', 'airport_as_city', '[\"NUM\"]', '[\"シャルマ\"]'),
(941, 'Shenyang', 'CN', 'SHE', 'airport_as_city', '[\"SHE\"]', '[\"瀋陽\", \"沈阳\"]'),
(942, 'Shenzhen', 'CN', 'SZX', 'airport_as_city', '[\"SZX\"]', '[\"深圳\"]'),
(943, 'Shijiazhuang', 'CN', 'SJW', 'airport_as_city', '[\"SJW\"]', '[\"石家荘\", \"石家莊\", \"石家庄\"]'),
(944, 'Shiraz', 'IR', 'SYZ', 'airport_as_city', '[\"SYZ\"]', '[\"シラーズ\"]'),
(945, 'Shymkent', 'KZ', 'CIT', 'airport_as_city', '[\"CIT\"]', '[\"シムケント\"]'),
(946, 'Sialkot', 'PK', 'SKT', 'airport_as_city', '[\"SKT\"]', '[\"シアールコート\"]'),
(947, 'Sibiu', 'RO', 'SBZ', 'airport_as_city', '[\"SBZ\"]', '[\"シビウ\"]'),
(948, 'Siddharthanagar (Bhairahawa)', 'NP', 'BWA', 'airport_as_city', '[\"BWA\"]', '[\"シッダルタナガル（バイラハワ）\"]'),
(949, 'Siem Reap', 'KH', 'SAI', 'airport_as_city', '[\"SAI\"]', '[\"シェムリアップ\"]'),
(950, 'Silao', 'MX', 'BJX', 'airport_as_city', '[\"BJX\"]', '[\"シラオ\"]'),
(951, 'Siliguri', 'IN', 'IXB', 'airport_as_city', '[\"IXB\"]', '[\"シリグリ\"]'),
(952, 'Simferopol', 'UA', 'SIP', 'airport_as_city', '[\"SIP\"]', '[\"シンフェロポリ\"]'),
(953, 'Singapore', 'SG', 'SIN', 'airport_as_city', '[\"SIN\"]', '[\"シンガポール\"]'),
(954, 'Sint Maarten', 'SX', 'SXM', 'airport_as_city', '[\"SXM\"]', '[\"シント・マールテン島\"]'),
(955, 'Skardu', 'PK', 'KDU', 'airport_as_city', '[\"KDU\"]', '[\"スカルドゥ\"]'),
(956, 'Sochi', 'RU', 'AER', 'airport_as_city', '[\"AER\"]', '[\"ソチ\"]'),
(957, 'Sofia', 'BG', 'SOF', 'airport_as_city', '[\"SOF\"]', '[\"ソフィア\"]'),
(958, 'Sokoto', 'NG', 'SKO', 'airport_as_city', '[\"SKO\"]', '[\"ソコト\"]'),
(959, 'Souda', 'GR', 'CHQ', 'airport_as_city', '[\"CHQ\"]', '[\"ハニア\",\"ソウダ\"]'),
(960, 'South Tarawa', 'KI', 'TRW', 'airport_as_city', '[\"TRW\"]', '[\"南タラワ\"]'),
(961, 'Spata-Artemida', 'GR', 'ATH', 'airport_as_city', '[\"ATH\"]', '[\"アテネ\",\"スパタ\"]'),
(962, 'Split', 'HR', 'SPU', 'airport_as_city', '[\"SPU\"]', '[\"スプリト\"]'),
(963, 'Spokane', 'US', 'GEG', 'airport_as_city', '[\"GEG\"]', '[\"スポケーン\"]'),
(964, 'Srinagar', 'IN', 'SXR', 'airport_as_city', '[\"SXR\"]', '[\"シュリーナガル\"]'),
(965, 'St. John\'s', 'CA', 'YYT', 'airport_as_city', '[\"YYT\"]', '[\"セントジョンズ\"]'),
(966, 'St Louis', 'US', 'STL', 'airport_as_city', '[\"STL\"]', '[\"セントルイス\"]'),
(967, 'St Lucia', 'SL', 'SLU', 'metropolitan', '[\"SLU\", \"UVF\"]', '[\"セントルシア\"]'),
(968, 'St. Petersburg', 'RU', 'LED', 'airport_as_city', '[\"LED\"]', '[\"サンクトペテルブルク\"]'),
(969, 'Stavanger', 'NO', 'SVG', 'airport_as_city', '[\"SVG\"]', '[\"スタヴァンゲル\"]'),
(970, 'Stockholm', 'SE', 'STO', 'metropolitan', '[\"ARN\", \"BMA\"]', '[\"ストックホルム\"]'),
(971, 'Stockholm / Västerås', 'SE', 'VST', 'airport_as_city', '[\"VST\"]', '[\"ストックホルム\",\"ヴェステロース\"]'),
(972, 'Strasbourg', 'FR', 'SXB', 'airport_as_city', '[\"SXB\"]', '[\"ストラスブール\"]'),
(973, 'Stuttgart', 'DE', 'STR', 'airport_as_city', '[\"STR\"]', '[\"シュトゥットガルト\"]'),
(974, 'Subang', 'MY', 'SZB', 'airport_as_city', '[\"SZB\"]', '[\"スバン\"]'),
(975, 'Suceava', 'RO', 'SCV', 'airport_as_city', '[\"SCV\"]', '[\"スチャヴァ\"]'),
(976, 'Sucre', 'BO', 'SRE', 'airport_as_city', '[\"SRE\"]', '[\"スクレ\"]'),
(977, 'Suhaj', 'EG', 'HMB', 'airport_as_city', '[\"HMB\"]', '[\"スハジ\"]'),
(978, 'Suhar', 'OM', 'OHS', 'airport_as_city', '[\"OHS\"]', '[\"スハール\"]'),
(979, 'Surabaya', 'ID', 'SUB', 'airport_as_city', '[\"SUB\"]', '[\"スラバヤ\"]'),
(980, 'Surakarta', 'ID', 'SOC', 'airport_as_city', '[\"SOC\"]', '[\"スラカルタ\"]'),
(981, 'Surat', 'IN', 'STV', 'airport_as_city', '[\"STV\"]', '[\"スーラト\"]'),
(982, 'Surgut', 'RU', 'SGC', 'airport_as_city', '[\"SGC\"]', '[\"スルグト\"]'),
(983, 'Sydney (Mascot)', 'AU', 'SYD', 'airport_as_city', '[\"SYD\"]', '[\"シドニー\"]'),
(984, 'Sylhet', 'BD', 'ZYL', 'airport_as_city', '[\"ZYL\"]', '[\"シレット\"]'),
(985, 'Syracuse', 'US', 'SYR', 'airport_as_city', '[\"SYR\"]', '[\"シラキュース\"]'),
(986, 'Szczecin(Glewice)', 'PL', 'SZZ', 'airport_as_city', '[\"SZZ\"]', '[\"シュチェチン\"]'),
(987, 'Ta Noun', 'KH', 'DSY', 'airport_as_city', '[\"DSY\"]', '[\"タ名詞\"]'),
(988, 'Tabriz', 'IR', 'TBZ', 'airport_as_city', '[\"TBZ\"]', '[\"タブリーズ\"]'),
(989, 'Tabuk', 'SA', 'TUU', 'airport_as_city', '[\"TUU\"]', '[\"タブーク\"]'),
(990, 'Tachina', 'EC', 'ESM', 'airport_as_city', '[\"ESM\"]', '[\"タチナ\"]'),
(991, 'Tahir', 'DZ', 'GJL', 'airport_as_city', '[\"GJL\"]', '[\"タヒル\"]'),
(992, 'Taichung (Qingshui)', 'TW', 'RMQ', 'airport_as_city', '[\"RMQ\"]', '[\"台中\", \"臺中\"]'),
(993, 'Taif', 'SA', 'TIF', 'airport_as_city', '[\"TIF\"]', '[\"タイフ\"]'),
(994, 'Tainan (Rende)', 'TW', 'TNN', 'airport_as_city', '[\"TNN\"]', '[\"台南\", \"臺南\"]'),
(995, 'Taipei', 'TW', 'TPE', 'metropolitan', '[\"TPE\", \"TSA\"]', '[\"台北\", \"タイペイ\", \"臺北\"]'),
(996, 'Taipei (Songshan)', 'TW', 'TSA', 'airport_as_city', '[\"TSA\"]', '[\"台北\", \"臺北\", \"松山\"]'),
(997, 'Taiyuan', 'CN', 'TYN', 'airport_as_city', '[\"TYN\"]', '[\"太原\"]'),
(998, 'Takamatsu', 'JP', 'TAK', 'airport_as_city', '[\"TAK\"]', '[\"高松\", \"たかまつ\"]'),
(999, 'Tallinn', 'EE', 'TLL', 'airport_as_city', '[\"TLL\"]', '[\"タリン\"]'),
(1000, 'Tamale', 'GH', 'TML', 'airport_as_city', '[\"TML\"]', '[\"タマレ\"]'),
(1001, 'Tamanrasset', 'DZ', 'TMR', 'airport_as_city', '[\"TMR\"]', '[\"タマンラセット\"]'),
(1002, 'Tamchy', 'KG', 'IKU', 'airport_as_city', '[\"IKU\"]', '[\"タムチー\"]'),
(1003, 'Tampa', 'US', 'TPA', 'airport_as_city', '[\"TPA\"]', '[\"タンパ\"]'),
(1004, 'Tampere / Pirkkala', 'FI', 'TMP', 'airport_as_city', '[\"TMP\"]', '[\"タンペレ\",\"ピルッカラ\"]'),
(1005, 'Tangier', 'MA', 'TNG', 'airport_as_city', '[\"TNG\"]', '[\"タンジール\"]'),
(1006, 'Taoyuan', 'TW', 'TPE', 'airport_as_city', '[\"TPE\"]', '[\"桃園\"]'),
(1007, 'Taraz', 'KZ', 'DMB', 'airport_as_city', '[\"DMB\"]', '[\"タラズ\"]'),
(1008, 'Tarsus', 'TR', 'COV', 'airport_as_city', '[\"COV\"]', '[\"チュクロヴァ\",\"タルスス\"]'),
(1009, 'Tashkent', 'UZ', 'TAS', 'airport_as_city', '[\"TAS\"]', '[\"タシケント\"]'),
(1010, 'Tbilisi', 'GE', 'TBS', 'airport_as_city', '[\"TBS\"]', '[\"トビリシ\"]'),
(1011, 'Tehran', 'IR', 'THR', 'metropolitan', '[\"IKA\", \"THR\"]', '[\"テヘラン\"]'),
(1012, 'Tel Aviv', 'IL', 'TLV', 'airport_as_city', '[\"TLV\"]', '[\"テルアビブ\"]'),
(1013, 'Temuco', 'CL', 'ZCO', 'airport_as_city', '[\"ZCO\"]', '[\"テムコ\"]'),
(1014, 'Tenerife', 'ES', 'TCI', 'metropolitan', '[\"TFN\", \"TFS\"]', '[\"テネリフェ島\"]'),
(1015, 'Tete', 'MZ', 'TET', 'airport_as_city', '[\"TET\"]', '[\"テテ\"]'),
(1016, 'Tétouan', 'MA', 'TTU', 'airport_as_city', '[\"TTU\"]', '[\"テトゥアン\"]'),
(1017, 'Thessaloniki', 'GR', 'SKG', 'airport_as_city', '[\"SKG\"]', '[\"テッサロニキ\"]'),
(1018, 'Thiruvananthapuram', 'IN', 'TRV', 'airport_as_city', '[\"TRV\"]', '[\"ティルヴァナンタプラム\"]'),
(1019, 'Tianjin', 'CN', 'TSN', 'airport_as_city', '[\"TSN\"]', '[\"天津\"]'),
(1020, 'Tijuana', 'MX', 'TIJ', 'airport_as_city', '[\"TIJ\"]', '[\"ティファナ\"]'),
(1021, 'Timbuktu', 'ML', 'TOM', 'airport_as_city', '[\"TOM\"]', '[\"トンブクトゥ\"]'),
(1022, 'Timişoara', 'RO', 'TSR', 'airport_as_city', '[\"TSR\"]', '[\"ティミショアラ\"]'),
(1023, 'Tiruchirappalli', 'IN', 'TRZ', 'airport_as_city', '[\"TRZ\"]', '[\"ティルチラパッリ\"]'),
(1024, 'Tirupati', 'IN', 'TIR', 'airport_as_city', '[\"TIR\"]', '[\"ティルパティ\"]'),
(1025, 'Toamasina', 'MG', 'TMM', 'airport_as_city', '[\"TMM\"]', '[\"トアマシナ\"]'),
(1026, 'Tocumen', 'PA', 'PTY', 'airport_as_city', '[\"PTY\"]', '[\"トキュメン\"]'),
(1027, 'Tokoname', 'JP', 'NGO', 'airport_as_city', '[\"NGO\"]', '[\"常滑\"]'),
(1028, 'Tokushima', 'JP', 'TKS', 'airport_as_city', '[\"TKS\"]', '[\"徳島\", \"とくしま\"]'),
(1029, 'Tokyo', 'JP', 'TYO', 'metropolitan', '[\"HND\", \"NRT\"]', '[\"東京\", \"東京23区\", \"とうきょう\"]'),
(1030, 'Toluca', 'MX', 'TLC', 'airport_as_city', '[\"TLC\"]', '[\"トルカ\"]'),
(1031, 'Tomsk', 'RU', 'TOF', 'airport_as_city', '[\"TOF\"]', '[\"トムスク\"]'),
(1032, 'Toowoomba', 'AU', 'WTB', 'airport_as_city', '[\"WTB\"]', '[\"トゥーンバ\"]'),
(1033, 'Toronto', 'CA', 'YTO', 'metropolitan', '[\"YTZ\", \"YYZ\"]', '[\"トロント\"]'),
(1034, 'Toulouse/Blagnac', 'FR', 'TLS', 'airport_as_city', '[\"TLS\"]', '[\"トゥールーズ\",\"ブラニャック\"]'),
(1035, 'Treviso (TV)', 'IT', 'TSF', 'airport_as_city', '[\"TSF\"]', '[\"トレヴィーゾ\"]'),
(1036, 'Tripoli', 'LY', 'MJI', 'airport_as_city', '[\"MJI\"]', '[\"トリポリ\"]'),
(1037, 'Tromsø', 'NO', 'TOS', 'airport_as_city', '[\"TOS\"]', '[\"トロムソ\"]'),
(1038, 'Trondheim', 'NO', 'TRD', 'airport_as_city', '[\"TRD\"]', '[\"トロンハイム\"]'),
(1039, 'Trujillo', 'PE', 'TRU', 'airport_as_city', '[\"TRU\"]', '[\"トルヒーリョ\"]'),
(1040, 'Tucson', 'US', 'TUS', 'airport_as_city', '[\"TUS\"]', '[\"ツーソン\"]'),
(1041, 'Tulsa', 'US', 'TUL', 'airport_as_city', '[\"TUL\"]', '[\"タルサ\"]'),
(1042, 'Tulum', 'MX', 'TQO', 'airport_as_city', '[\"TQO\"]', '[\"トゥルム\"]'),
(1043, 'Tunis', 'TN', 'TUN', 'airport_as_city', '[\"TUN\"]', '[\"チュニス\"]'),
(1044, 'Tunoshna', 'RU', 'IAR', 'airport_as_city', '[\"IAR\"]', '[\"ヤロスラヴリ\",\"トゥノシナ\"]'),
(1045, 'Turbat', 'PK', 'TUK', 'airport_as_city', '[\"TUK\"]', '[\"トゥルバット\"]'),
(1046, 'Turkıstan', 'KZ', 'HSA', 'airport_as_city', '[\"HSA\"]', '[\"トルキスタン\"]'),
(1047, 'Türkmenabat', 'TM', 'CRZ', 'airport_as_city', '[\"CRZ\"]', '[\"テュルクメナバート\"]'),
(1048, 'Turku', 'FI', 'TKU', 'airport_as_city', '[\"TKU\"]', '[\"トゥルク\"]'),
(1049, 'Tymbou (Kirklar)', 'CY', 'ECN', 'airport_as_city', '[\"ECN\"]', '[\"エルジャン\",\"ティンブー\"]'),
(1050, 'Tyumen', 'RU', 'TJM', 'airport_as_city', '[\"TJM\"]', '[\"チュメニ\"]'),
(1051, 'Udon Thani', 'TH', 'UTH', 'airport_as_city', '[\"UTH\"]', '[\"ウドンターニー\"]'),
(1052, 'Ufa', 'RU', 'UFA', 'airport_as_city', '[\"UFA\"]', '[\"ウファ\"]'),
(1053, 'Ulaanbaatar (Sergelen)', 'MN', 'UBN', 'airport_as_city', '[\"UBN\"]', '[\"ウランバートル (セルゲレン)\"]'),
(1054, 'Ulan Ude', 'RU', 'UUD', 'airport_as_city', '[\"UUD\"]', '[\"ウラン・ウデ\"]'),
(1055, 'Umeå', 'SE', 'UME', 'airport_as_city', '[\"UME\"]', '[\"ウメオ\"]'),
(1056, 'Uralsk', 'KZ', 'URA', 'airport_as_city', '[\"URA\"]', '[\"ウラリスク\"]'),
(1057, 'Urgench', 'UZ', 'UGC', 'airport_as_city', '[\"UGC\"]', '[\"ウルゲンチ\"]'),
(1058, 'Ürümqi', 'CN', 'URC', 'airport_as_city', '[\"URC\"]', '[\"烏魯木斉\", \"烏魯木齊\", \"乌鲁木齐\"]'),
(1059, 'Ust-Kamenogorsk (Oskemen)', 'KZ', 'UKK', 'airport_as_city', '[\"UKK\"]', '[\"ウスチ・カメノゴルスク (オスケメン)\"]'),
(1060, 'Uzhhorod', 'UA', 'UDJ', 'airport_as_city', '[\"UDJ\"]', '[\"ウージュホロド\"]'),
(1061, 'Vaasa', 'FI', 'VAA', 'airport_as_city', '[\"VAA\"]', '[\"ヴァーサ\"]'),
(1062, 'Vadodara', 'IN', 'BDQ', 'airport_as_city', '[\"BDQ\"]', '[\"バドダラ\"]'),
(1063, 'Vágar', 'FO', 'FAE', 'airport_as_city', '[\"FAE\"]', '[\"ヴァガル\"]'),
(1064, 'Valencia', 'ES', 'VLC', 'airport_as_city', '[\"VLC\"]', '[\"バレンシア\"]'),
(1065, 'Valencia', 'VE', 'VLN', 'airport_as_city', '[\"VLN\"]', '[\"バレンシア\"]'),
(1066, 'Valletta', 'MT', 'MLA', 'airport_as_city', '[\"MLA\"]', '[\"バレッタ\"]'),
(1067, 'Vancouver', 'CA', 'YVR', 'airport_as_city', '[\"YVR\"]', '[\"バンクーバー\"]'),
(1068, 'Varanasi', 'IN', 'VNS', 'airport_as_city', '[\"VNS\"]', '[\"バラナシ\"]'),
(1069, 'Varna', 'BG', 'VAR', 'airport_as_city', '[\"VAR\"]', '[\"ヴァルナ\"]'),
(1070, 'Vasco da Gama', 'IN', 'GOI', 'airport_as_city', '[\"GOI\"]', '[\"バスコ ダ ガマ\"]'),
(1071, 'Vava\'u Island', 'TO', 'VAV', 'airport_as_city', '[\"VAV\"]', '[\"ババウ島\"]'),
(1072, 'Velika Gorica', 'HR', 'ZAG', 'airport_as_city', '[\"ZAG\"]', '[\"ザグレブ\",\"ヴェリカ・ゴリツァ\"]'),
(1073, 'Venezia (VE)', 'IT', 'VCE', 'airport_as_city', '[\"VCE\"]', '[\"ヴェネツィア\",\"ベネチア\"]'),
(1074, 'Veracruz', 'MX', 'VER', 'airport_as_city', '[\"VER\"]', '[\"ベラクルス\"]'),
(1075, 'Victoria', 'CA', 'YYJ', 'airport_as_city', '[\"YYJ\"]', '[\"ビクトリア\"]'),
(1076, 'Victoria', 'SC', 'SEZ', 'airport_as_city', '[\"SEZ\"]', '[\"ビクトリア\"]'),
(1077, 'Victoria Falls', 'ZW', 'VFA', 'airport_as_city', '[\"VFA\"]', '[\"ビクトリアの滝\"]'),
(1078, 'Vienna', 'AT', 'VIE', 'airport_as_city', '[\"VIE\"]', '[\"ウィーン\"]'),
(1079, 'Vientiane', 'LA', 'VTE', 'airport_as_city', '[\"VTE\"]', '[\"ビエンチャン\"]'),
(1080, 'Vieux Fort', 'LC', 'UVF', 'airport_as_city', '[\"UVF\"]', '[\"ヴュー・フォール\"]'),
(1081, 'Vijayawada', 'IN', 'VGA', 'airport_as_city', '[\"VGA\"]', '[\"ヴィジャヤワダ\"]'),
(1082, 'Villahermosa', 'MX', 'VSA', 'airport_as_city', '[\"VSA\"]', '[\"ビヤエルモサ\"]'),
(1083, 'Vilnius', 'LT', 'VNO', 'airport_as_city', '[\"VNO\"]', '[\"ヴィリニュス\"]'),
(1084, 'Visakhapatnam', 'IN', 'VTZ', 'airport_as_city', '[\"VTZ\"]', '[\"ヴィシャカパトナム\"]'),
(1085, 'Visby', 'SE', 'VBY', 'airport_as_city', '[\"VBY\"]', '[\"ヴィスビュー\"]'),
(1086, 'Vitória', 'BR', 'VIX', 'airport_as_city', '[\"VIX\"]', '[\"ビトリア\"]'),
(1087, 'Volgograd', 'RU', 'VOG', 'airport_as_city', '[\"VOG\"]', '[\"ヴォルゴグラード\"]'),
(1088, 'Wallis Island', 'WF', 'WLS', 'airport_as_city', '[\"WLS\"]', '[\"ウォリス島\"]'),
(1089, 'Walvis Bay(Rooikop)', 'nan', 'WVB', 'airport_as_city', '[\"WVB\"]', '[\"ウォルビスベイ(ロイコップ)\"]'),
(1090, 'Warsaw', 'PL', 'WAW', 'airport_as_city', '[\"WAW\"]', '[\"ワルシャワ\"]'),
(1091, 'Washington', 'US', 'WAS', 'metropolitan', '[\"DCA\", \"IAD\"]', '[\"ワシントンD.C.\",\"ワシントンDC\"]'),
(1092, 'Weeze', 'DE', 'NRN', 'airport_as_city', '[\"NRN\"]', '[\"ヴェーツェ\"]'),
(1093, 'Wellington', 'NZ', 'WLG', 'airport_as_city', '[\"WLG\"]', '[\"ウェリントン\"]'),
(1094, 'Weno Island', 'FM', 'TKK', 'airport_as_city', '[\"TKK\"]', '[\"ウェノ島\"]'),
(1095, 'Wenzhou (Longwan)', 'CN', 'WNZ', 'airport_as_city', '[\"WNZ\"]', '[\"溫州\", \"温州\"]'),
(1096, 'West Island', 'CC', 'CCK', 'airport_as_city', '[\"CCK\"]', '[\"ウェストアイランド\"]'),
(1097, 'West Palm Beach', 'US', 'PBI', 'airport_as_city', '[\"PBI\"]', '[\"ウェストパームビーチ\"]'),
(1098, 'Willemstad', 'CW', 'CUR', 'airport_as_city', '[\"CUR\"]', '[\"ウィレムスタット\"]'),
(1099, 'Williamtown', 'AU', 'NTL', 'airport_as_city', '[\"NTL\"]', '[\"ニューカッスル\",\"ウィリアムタウン\"]'),
(1100, 'Windhoek', 'nan', 'WDH', 'airport_as_city', '[\"WDH\"]', '[\"ウィントフック\"]'),
(1101, 'Winnipeg', 'CA', 'YWG', 'airport_as_city', '[\"YWG\"]', '[\"ウィニペグ\"]'),
(1102, 'Wrocław', 'PL', 'WRO', 'airport_as_city', '[\"WRO\"]', '[\"ヴロツワフ\"]'),
(1103, 'Wuhan (Huangpi)', 'CN', 'WUH', 'airport_as_city', '[\"WUH\"]', '[\"武漢\", \"武汉\"]'),
(1104, 'Wuxi', 'CN', 'WUX', 'airport_as_city', '[\"WUX\"]', '[\"無錫\", \"无锡\"]'),
(1105, 'Xi\'an', 'CN', 'XIY', 'airport_as_city', '[\"XIY\"]', '[\"西安\"]'),
(1106, 'Xiamen', 'CN', 'XMN', 'airport_as_city', '[\"XMN\"]', '[\"廈門\", \"厦門\", \"厦门\"]'),
(1107, 'Xigazê (Samzhubzê)', 'CN', 'RKZ', 'airport_as_city', '[\"RKZ\"]', '[\"日喀則\", \"日喀则\"]'),
(1108, 'Yakutsk', 'RU', 'YKS', 'airport_as_city', '[\"YKS\"]', '[\"ヤクーツク\"]'),
(1109, 'Yanbu', 'SA', 'YNB', 'airport_as_city', '[\"YNB\"]', '[\"ヤンブー\"]'),
(1110, 'Yancheng (Tinghu)', 'CN', 'YNZ', 'airport_as_city', '[\"YNZ\"]', '[\"塩城\", \"鹽城\", \"盐城\"]'),
(1111, 'Yangon', 'MM', 'RGN', 'airport_as_city', '[\"RGN\"]', '[\"ヤンゴン\"]'),
(1112, 'Yantai', 'CN', 'YNT', 'airport_as_city', '[\"YNT\"]', '[\"煙台\", \"煙臺\", \"烟台\"]'),
(1113, 'Yaoundé', 'CM', 'NSI', 'airport_as_city', '[\"NSI\"]', '[\"ヤウンデ\"]'),
(1114, 'Yap Island', 'FM', 'YAP', 'airport_as_city', '[\"YAP\"]', '[\"ヤップ島\"]'),
(1115, 'Yekaterinburg', 'RU', 'SVX', 'airport_as_city', '[\"SVX\"]', '[\"エカテリンブルク\"]'),
(1116, 'Yerevan', 'AM', 'EVN', 'airport_as_city', '[\"EVN\"]', '[\"エレバン\"]'),
(1117, 'Yinchuan', 'CN', 'INC', 'airport_as_city', '[\"INC\"]', '[\"銀川\", \"银川\"]'),
(1118, 'Yiwu/Jinhua', 'CN', 'YIW', 'airport_as_city', '[\"YIW\"]', '[\"義烏\", \"义乌\", \"金華\", \"金华\"]'),
(1119, 'Yogyakarta', 'ID', 'JOG', 'metropolitan', '[\"JOG\", \"YIA\"]', '[\"ジョグジャカルタ\"]'),
(1120, 'Yuncheng (Yanhu)', 'CN', 'YCU', 'airport_as_city', '[\"YCU\"]', '[\"運城\", \"运城\"]'),
(1121, 'Yuzhno-Sakhalinsk', 'RU', 'UUS', 'airport_as_city', '[\"UUS\"]', '[\"ユジノサハリンスク\"]'),
(1122, 'Zadar', 'HR', 'ZAD', 'airport_as_city', '[\"ZAD\"]', '[\"ザダル\"]'),
(1123, 'Zagora', 'MA', 'OZG', 'airport_as_city', '[\"OZG\"]', '[\"ザゴラ\"]'),
(1124, 'Zahedan', 'IR', 'ZAH', 'airport_as_city', '[\"ZAH\"]', '[\"ザヘダン\"]'),
(1125, 'Zamboanga', 'PH', 'ZAM', 'airport_as_city', '[\"ZAM\"]', '[\"サンボアンガ\"]'),
(1126, 'Zanzibar', 'TZ', 'ZNZ', 'airport_as_city', '[\"ZNZ\"]', '[\"ザンジバル\"]'),
(1127, 'Zaragoza', 'ES', 'ZAZ', 'airport_as_city', '[\"ZAZ\"]', '[\"サラゴサ\"]'),
(1128, 'Zaventem', 'BE', 'BRU', 'airport_as_city', '[\"BRU\"]', '[\"ブリュッセル\",\"ザベンテム\"]'),
(1129, 'Zenata', 'DZ', 'TLM', 'airport_as_city', '[\"TLM\"]', '[\"ゼナタ\"]'),
(1130, 'Zgornji Brnik', 'SI', 'LJU', 'airport_as_city', '[\"LJU\"]', '[\"リュブリャナ\",\"ズゴルニ・ブルニク\"]'),
(1131, 'Zhangjiajie (Yongding)', 'CN', 'DYG', 'airport_as_city', '[\"DYG\"]', '[\"張家界\", \"张家界\"]'),
(1132, 'Zhanjiang', 'CN', 'ZHA', 'airport_as_city', '[\"ZHA\"]', '[\"湛江\"]'),
(1133, 'Zhengzhou', 'CN', 'CGO', 'airport_as_city', '[\"CGO\"]', '[\"鄭州\", \"郑州\"]'),
(1134, 'Zhezkazgan', 'KZ', 'DZN', 'airport_as_city', '[\"DZN\"]', '[\"ジェスカズガン\"]'),
(1135, 'Zhoushan', 'CN', 'HSN', 'airport_as_city', '[\"HSN\"]', '[\"舟山\"]'),
(1136, 'Zhuhai (Jinwan)', 'CN', 'ZUH', 'airport_as_city', '[\"ZUH\"]', '[\"珠海\"]'),
(1137, 'Zurich', 'CH', 'ZRH', 'airport_as_city', '[\"ZRH\"]', '[\"チューリッヒ\"]'),
(1138, 'Tokyo Haneda Airport', 'JP', 'HND', 'airport', '[\"HND\"]', '[\"羽田\", \"羽田空港\", \"東京国際空港\", \"Haneda\", \"Haneda Airport\"]'),
(1139, 'Narita International Airport', 'JP', 'NRT', 'airport', '[\"NRT\"]', '[\"成田\", \"成田空港\", \"成田国際空港\", \"Narita\", \"Narita Airport\"]'),
(1140, 'New Chitose Airport', 'JP', 'CTS', 'airport', '[\"CTS\"]', '[\"新千歳\", \"新千歳空港\", \"New Chitose\", \"New Chitose Airport\"]'),
(1141, 'Chubu Centrair International Airport', 'JP', 'NGO', 'airport', '[\"NGO\"]', '[\"中部\", \"中部空港\", \"中部国際空港\", \"セントレア\", \"Centrair\", \"Chubu Centrair\"]'),
(1142, 'Osaka Itami Airport', 'JP', 'ITM', 'airport', '[\"ITM\"]', '[\"伊丹\", \"伊丹空港\", \"大阪国際空港\", \"Itami\", \"Itami Airport\"]'),
(1143, 'Kansai International Airport', 'JP', 'KIX', 'airport', '[\"KIX\"]', '[\"関西\", \"関西空港\", \"関西国際空港\", \"Kansai\", \"Kansai Airport\"]'),
(1144, 'Kobe Airport', 'JP', 'UKB', 'airport', '[\"UKB\"]', '[\"神戸空港\", \"Kobe Airport\"]'),
(1145, 'Obihiro', 'JP', 'OBO', 'airport', '[\"OBO\"]', '[\"帯広\", \"おびひろ\", \"Obihiro\"]'),
(1146, 'Oita', 'JP', 'OIT', 'airport', '[\"OIT\"]', '[\"大分\", \"おおいた\", \"Oita\"]'),
(1147, 'Miyakojima', 'JP', 'MMY', 'city', '[\"MMY\", \"SHI\"]', '[\"宮古\", \"宮古島\", \"みやこ\", \"みやこじま\", \"Miyako\", \"Miyakojima\", \"下地島\", \"しもじしま\", \"Shimoji\", \"Shimojishima\"]');

--
-- ダンプしたテーブルのインデックス
--

--
-- テーブルのインデックス `iata_cities`
--
ALTER TABLE `iata_cities`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `uniq_city_iata` (`city`,`iata`),
  ADD KEY `idx_city` (`city`),
  ADD KEY `idx_iata` (`iata`),
  ADD KEY `idx_country` (`country`);

--
-- ダンプしたテーブルの AUTO_INCREMENT
--

--
-- テーブルの AUTO_INCREMENT `iata_cities`
--
ALTER TABLE `iata_cities`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1148;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
