CREATE TABLE travel_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 origin VARCHAR(100) NOT NULL,
 destination VARCHAR(100) NOT NULL,
 departure_date DATE NOT NULL,
 return_date DATE NULL,
 travelers TINYINT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
