CREATE TABLE travel_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 origin VARCHAR(100) NOT NULL,
 destination VARCHAR(100) NOT NULL,
 departure_date DATE NOT NULL,
 return_date DATE NULL,
 travelers TINYINT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE flight_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 origin VARCHAR(100) NOT NULL,
 destination VARCHAR(100) NOT NULL,
 departure_date DATE NOT NULL,
 return_date DATE NULL,
 travelers TINYINT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE hotel_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 destination VARCHAR(150) NOT NULL,
 check_in DATE NOT NULL,
 check_out DATE NOT NULL,
 adults TINYINT UNSIGNED NOT NULL DEFAULT 1,
 children TINYINT UNSIGNED NOT NULL DEFAULT 0,
 guests TINYINT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
