<section class="panel">
<div class="search-tabs" role="tablist" aria-label="検索タイプ">
<button type="button" class="search-tab<?= $activeTab === 'flight' ? ' is-active' : '' ?>" id="flight-tab" role="tab" aria-selected="<?= $activeTab === 'flight' ? 'true' : 'false' ?>" aria-controls="flight-panel" data-tab="flight-panel"<?= $activeTab !== 'flight' ? ' tabindex="-1"' : '' ?>>✈ 航空券</button>
<button type="button" class="search-tab<?= $activeTab === 'hotel' ? ' is-active' : '' ?>" id="hotel-tab" role="tab" aria-selected="<?= $activeTab === 'hotel' ? 'true' : 'false' ?>" aria-controls="hotel-panel" data-tab="hotel-panel"<?= $activeTab !== 'hotel' ? ' tabindex="-1"' : '' ?>>▣ ホテル</button>
</div>
<div class="tab-panel" id="flight-panel" role="tabpanel" aria-labelledby="flight-tab"<?= $activeTab !== 'flight' ? ' hidden' : '' ?>>
<?php require __DIR__ . '/flight-search-form.php'; ?>
</div>
<div class="tab-panel" id="hotel-panel" role="tabpanel" aria-labelledby="hotel-tab"<?= $activeTab !== 'hotel' ? ' hidden' : '' ?>>
<div class="provider-tabs hotel-provider-tabs" role="tablist" aria-label="ホテル検索範囲"><button type="button" class="provider-tab hotel-provider-tab<?= $activeHotelScope === 'domestic' ? ' is-active' : '' ?>" id="domestic-hotel-tab" role="tab" aria-selected="<?= $activeHotelScope === 'domestic' ? 'true' : 'false' ?>" aria-controls="domestic-hotel-panel" data-provider-panel="domestic-hotel-panel"<?= $activeHotelScope !== 'domestic' ? ' tabindex="-1"' : '' ?>>国内ホテル</button><button type="button" class="provider-tab hotel-provider-tab<?= $activeHotelScope === 'overseas' ? ' is-active' : '' ?>" id="overseas-hotel-tab" role="tab" aria-selected="<?= $activeHotelScope === 'overseas' ? 'true' : 'false' ?>" aria-controls="overseas-hotel-panel" data-provider-panel="overseas-hotel-panel"<?= $activeHotelScope !== 'overseas' ? ' tabindex="-1"' : '' ?>>海外ホテル</button></div>
<?php if($hotelErrors): ?><div class="errors"><b>入力内容をご確認ください</b><ul><?php foreach($hotelErrors as $error): ?><li><?= $h($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<?php foreach(['domestic' => '国内の目的地（例：東京、大阪）', 'overseas' => '海外の目的地（例：台北、ソウル、Dallas）'] as $scope => $placeholder): ?>
<div class="hotel-provider-panel" id="<?= $scope ?>-hotel-panel" role="tabpanel" aria-labelledby="<?= $scope ?>-hotel-tab"<?= $activeHotelScope !== $scope ? ' hidden' : '' ?>><form method="post" class="hotel-search-form hotel-search-form-shared"><input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><input type="hidden" name="hotel_scope" value="<?= $scope ?>"><input type="hidden" name="hotel_place_id"><input type="hidden" name="hotel_place_address"><input type="hidden" name="hotel_place_latitude"><input type="hidden" name="hotel_place_longitude"><input type="hidden" name="hotel_place_country"><div class="hotel-destination-field"><label for="<?= $scope ?>-hotel-destination">目的地</label><span class="hotel-destination-control"><input id="<?= $scope ?>-hotel-destination" name="hotel_destination" value="<?= $h($hotelValues['hotel_destination']) ?>" placeholder="<?= $h($placeholder) ?>" autocomplete="off" aria-autocomplete="list" aria-expanded="false" required><span class="hotel-place-loading" aria-hidden="true" hidden></span></span><div class="hotel-place-suggestions" role="listbox" aria-label="目的地候補" hidden></div><p class="hotel-place-status" aria-live="polite"></p></div><label>チェックイン<input type="date" name="check_in_date" value="<?= $h($hotelValues['check_in_date']) ?>" required></label><label>チェックアウト<input type="date" name="check_out_date" value="<?= $h($hotelValues['check_out_date']) ?>" required></label><label>大人<select name="hotel_adults"><?php for($i=1;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$hotelValues['hotel_adults']===$i?'selected':'' ?>><?= $i ?>名</option><?php endfor ?></select></label><label>子供<select name="hotel_children"><?php for($i=0;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$hotelValues['hotel_children']===$i?'selected':'' ?>><?= $i ?>名</option><?php endfor ?></select></label><div class="hotel-search-actions"><button name="search_type" value="hotel">ホテルを検索</button></div></form></div>
<?php endforeach ?>
</div>
</section>
