<section class="panel">
<div class="search-tabs" role="tablist" aria-label="検索タイプ">
<button type="button" class="search-tab<?= $activeTab === 'flight' ? ' is-active' : '' ?>" id="flight-tab" role="tab" aria-selected="<?= $activeTab === 'flight' ? 'true' : 'false' ?>" aria-controls="flight-panel" data-tab="flight-panel"<?= $activeTab !== 'flight' ? ' tabindex="-1"' : '' ?>>✈ 航空券</button>
<button type="button" class="search-tab<?= $activeTab === 'hotel' ? ' is-active' : '' ?>" id="hotel-tab" role="tab" aria-selected="<?= $activeTab === 'hotel' ? 'true' : 'false' ?>" aria-controls="hotel-panel" data-tab="hotel-panel"<?= $activeTab !== 'hotel' ? ' tabindex="-1"' : '' ?>>▣ ホテル</button></div>
<div class="tab-panel" id="flight-panel" role="tabpanel" aria-labelledby="flight-tab"<?= $activeTab !== 'flight' ? ' hidden' : '' ?>>
<?php if ($errors): ?><div class="errors"><b>入力内容をご確認ください</b><ul><?php foreach ($errors as $error): ?><li><?= $h($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" class="flight-search-form"><input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><input type="hidden" name="search_type" value="flight">
<fieldset class="trip-type"><legend>旅行タイプ</legend><label><input type="radio" name="trip_type" value="roundtrip" <?= $values['return_date'] !== '' || $_SERVER['REQUEST_METHOD'] !== 'POST' ? 'checked' : '' ?>> 往復</label><label><input type="radio" name="trip_type" value="oneway" <?= $values['return_date'] === '' && $_SERVER['REQUEST_METHOD'] === 'POST' && $activeTab === 'flight' ? 'checked' : '' ?>> 片道</label></fieldset>
<label>出発地<input name="origin" value="<?= $h($values['origin']) ?>" placeholder="例：東京" required></label><label>目的地<input name="destination" value="<?= $h($values['destination']) ?>" placeholder="例：バンコク" required></label><label>出発日<input type="date" name="departure_date" value="<?= $h($values['departure_date']) ?>" required></label><label>帰着日<input type="date" name="return_date" value="<?= $h($values['return_date']) ?>"></label><label>人数<select name="travelers"><?php for ($i=1;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$values['travelers']===$i?'selected':'' ?>><?= $i ?></option><?php endfor ?></select></label><button>航空券を検索</button></form></div>
<div class="tab-panel" id="hotel-panel" role="tabpanel" aria-labelledby="hotel-tab"<?= $activeTab !== 'hotel' ? ' hidden' : '' ?>>
<div class="hotel-provider-tabs" role="tablist" aria-label="ホテル検索サービス"><button type="button" class="hotel-provider-tab<?= $activeHotelScope==='domestic'?' is-active':'' ?>" id="domestic-hotel-tab" role="tab" aria-selected="<?= $activeHotelScope==='domestic'?'true':'false' ?>" aria-controls="domestic-hotel-panel" data-provider-panel="domestic-hotel-panel" data-result-provider="<?= $activeHotelScope==='domestic'?$activeHotelProvider:'rakuten' ?>"<?= $activeHotelScope!=='domestic'?' tabindex="-1"':'' ?>>楽天トラベル</button><button type="button" class="hotel-provider-tab<?= $activeHotelScope==='overseas'?' is-active':'' ?>" id="overseas-hotel-tab" role="tab" aria-selected="<?= $activeHotelScope==='overseas'?'true':'false' ?>" aria-controls="overseas-hotel-panel" data-provider-panel="overseas-hotel-panel" data-result-provider="<?= $activeHotelScope==='overseas'?$activeHotelProvider:'google' ?>"<?= $activeHotelScope!=='overseas'?' tabindex="-1"':'' ?>>Googleホテル</button><button type="button" class="hotel-provider-tab" id="trip-hotel-tab" role="tab" aria-selected="false" aria-controls="trip-hotel-panel" data-provider-panel="trip-hotel-panel" tabindex="-1">Trip.com</button><button type="button" class="hotel-provider-tab" id="expedia-hotel-tab" role="tab" aria-selected="false" aria-controls="expedia-hotel-panel" data-provider-panel="expedia-hotel-panel" tabindex="-1">Expedia</button></div>
<?php foreach(['domestic'=>'国内の目的地（例：五所川原、札幌）','overseas'=>'海外の目的地（例：バンコク、パリ）'] as $hotelScope=>$hotelPlaceholder): ?><div class="hotel-provider-panel" id="<?= $hotelScope ?>-hotel-panel" role="tabpanel" aria-labelledby="<?= $hotelScope ?>-hotel-tab"<?= $activeHotelScope!==$hotelScope?' hidden':'' ?>>
<?php if($activeHotelScope===$hotelScope&&($hotelErrors||$rakutenErrors)): ?><div class="errors"><b>入力内容をご確認ください</b><ul><?php foreach(array_merge($hotelErrors,$rakutenErrors) as $error): ?><li><?= $h($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" class="hotel-search-form hotel-search-form-shared"><input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><input type="hidden" name="hotel_scope" value="<?= $hotelScope ?>"><label>目的地<input name="hotel_destination" value="<?= $h($hotelValues['hotel_destination']) ?>" placeholder="<?= $h($hotelPlaceholder) ?>" required></label><label>チェックイン<input type="date" name="check_in_date" value="<?= $h($hotelValues['check_in_date']) ?>" required></label><label>チェックアウト<input type="date" name="check_out_date" value="<?= $h($hotelValues['check_out_date']) ?>" required></label><label>大人<select name="hotel_adults"><?php for($i=1;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$hotelValues['hotel_adults']===$i?'selected':'' ?>><?= $i ?>名</option><?php endfor ?></select></label><label>子供<select name="hotel_children"><?php for($i=0;$i<=9;$i++): ?><option value="<?= $i ?>" <?= (int)$hotelValues['hotel_children']===$i?'selected':'' ?>><?= $i ?>名</option><?php endfor ?></select></label><div class="hotel-search-actions"><button name="search_type" value="hotel">ホテルを検索</button></div></form></div><?php endforeach ?>
<div class="hotel-provider-panel trip-hotel-widget" id="trip-hotel-panel" role="tabpanel" aria-labelledby="trip-hotel-tab" hidden><iframe src="https://jp.trip.com/partners/ad/<?= $h($widgets['trip_hotel_id'] ?? 'S19265451') ?>?Allianceid=<?= $h($tripAllianceId) ?>&amp;SID=<?= $h($tripSid) ?>&amp;trip_sub1=" title="Trip.com ホテル検索" frameborder="0" scrolling="no" loading="lazy" style="width:100%;max-width:900px;height:200px;border:none" id="<?= $h($widgets['trip_hotel_id'] ?? 'S19265451') ?>"></iframe></div>
<div class="hotel-provider-panel expedia-hotel-widget" id="expedia-hotel-panel" role="tabpanel" aria-labelledby="expedia-hotel-tab" hidden><div class="eg-widget" data-widget="search" data-program="<?= $h($widgets['expedia_program'] ?? 'jp-expedia') ?>" data-lobs="stays" data-network="pz" data-camref="<?= $h($widgets['expedia_camref'] ?? '1011l5PxNZ') ?>" data-pubref=""></div></div>
</div></section>
